/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class AbstractConfiguration extends RefCountedObject {
  private long swigCPtr;

  public AbstractConfiguration(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGAbstractConfigurationUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public boolean hasProperty(String key) {
    return MyoushuJNI.AbstractConfiguration_hasProperty(swigCPtr, this, key);
  }

  public boolean hasOption(String key) {
    return MyoushuJNI.AbstractConfiguration_hasOption(swigCPtr, this, key);
  }

  public String getString(String key) {
    return MyoushuJNI.AbstractConfiguration_getString__SWIG_0(swigCPtr, this, key);
  }

  public String getString(String key, String defaultValue) {
    return MyoushuJNI.AbstractConfiguration_getString__SWIG_1(swigCPtr, this, key, defaultValue);
  }

  public String getRawString(String key) {
    return MyoushuJNI.AbstractConfiguration_getRawString__SWIG_0(swigCPtr, this, key);
  }

  public String getRawString(String key, String defaultValue) {
    return MyoushuJNI.AbstractConfiguration_getRawString__SWIG_1(swigCPtr, this, key, defaultValue);
  }

  public int getInt(String key) {
    return MyoushuJNI.AbstractConfiguration_getInt__SWIG_0(swigCPtr, this, key);
  }

  public int getInt(String key, int defaultValue) {
    return MyoushuJNI.AbstractConfiguration_getInt__SWIG_1(swigCPtr, this, key, defaultValue);
  }

  public double getDouble(String key) {
    return MyoushuJNI.AbstractConfiguration_getDouble__SWIG_0(swigCPtr, this, key);
  }

  public double getDouble(String key, double defaultValue) {
    return MyoushuJNI.AbstractConfiguration_getDouble__SWIG_1(swigCPtr, this, key, defaultValue);
  }

  public boolean getBool(String key) {
    return MyoushuJNI.AbstractConfiguration_getBool__SWIG_0(swigCPtr, this, key);
  }

  public boolean getBool(String key, boolean defaultValue) {
    return MyoushuJNI.AbstractConfiguration_getBool__SWIG_1(swigCPtr, this, key, defaultValue);
  }

  public void setString(String key, String value) {
    MyoushuJNI.AbstractConfiguration_setString(swigCPtr, this, key, value);
  }

  public void setInt(String key, int value) {
    MyoushuJNI.AbstractConfiguration_setInt(swigCPtr, this, key, value);
  }

  public void setDouble(String key, double value) {
    MyoushuJNI.AbstractConfiguration_setDouble(swigCPtr, this, key, value);
  }

  public void setBool(String key, boolean value) {
    MyoushuJNI.AbstractConfiguration_setBool(swigCPtr, this, key, value);
  }

  public void keys(VectorString range) {
    MyoushuJNI.AbstractConfiguration_keys__SWIG_0(swigCPtr, this, VectorString.getCPtr(range), range);
  }

  public void keys(String key, VectorString range) {
    MyoushuJNI.AbstractConfiguration_keys__SWIG_1(swigCPtr, this, key, VectorString.getCPtr(range), range);
  }

  public AbstractConfiguration createView(String prefix) {
    long cPtr = MyoushuJNI.AbstractConfiguration_createView__SWIG_0(swigCPtr, this, prefix);
    return (cPtr == 0) ? null : new AbstractConfiguration(cPtr, false);
  }

  public String expand(String value) {
    return MyoushuJNI.AbstractConfiguration_expand(swigCPtr, this, value);
  }

}
