/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class AutoPtr_InputDeviceMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public AutoPtr_InputDeviceMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AutoPtr_InputDeviceMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_AutoPtr_InputDeviceMessage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public AutoPtr_InputDeviceMessage() {
    this(MyoushuJNI.new_AutoPtr_InputDeviceMessage__SWIG_0(), true);
  }

  public AutoPtr_InputDeviceMessage(InputDeviceMessage ptr) {
    this(MyoushuJNI.new_AutoPtr_InputDeviceMessage__SWIG_1(InputDeviceMessage.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_InputDeviceMessage(InputDeviceMessage ptr, boolean shared) {
    this(MyoushuJNI.new_AutoPtr_InputDeviceMessage__SWIG_2(InputDeviceMessage.getCPtr(ptr), ptr, shared), true);
  }

  public AutoPtr_InputDeviceMessage(AutoPtr_InputDeviceMessage ptr) {
    this(MyoushuJNI.new_AutoPtr_InputDeviceMessage__SWIG_3(AutoPtr_InputDeviceMessage.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_InputDeviceMessage assign(InputDeviceMessage ptr) {
    return new AutoPtr_InputDeviceMessage(MyoushuJNI.AutoPtr_InputDeviceMessage_assign__SWIG_0(swigCPtr, this, InputDeviceMessage.getCPtr(ptr), ptr), false);
  }

  public AutoPtr_InputDeviceMessage assign(InputDeviceMessage ptr, boolean shared) {
    return new AutoPtr_InputDeviceMessage(MyoushuJNI.AutoPtr_InputDeviceMessage_assign__SWIG_1(swigCPtr, this, InputDeviceMessage.getCPtr(ptr), ptr, shared), false);
  }

  public AutoPtr_InputDeviceMessage assign(AutoPtr_InputDeviceMessage ptr) {
    return new AutoPtr_InputDeviceMessage(MyoushuJNI.AutoPtr_InputDeviceMessage_assign__SWIG_2(swigCPtr, this, AutoPtr_InputDeviceMessage.getCPtr(ptr), ptr), false);
  }

  public void swap(AutoPtr_InputDeviceMessage ptr) {
    MyoushuJNI.AutoPtr_InputDeviceMessage_swap(swigCPtr, this, AutoPtr_InputDeviceMessage.getCPtr(ptr), ptr);
  }

  public InputDeviceMessage __deref__() {
    long cPtr = MyoushuJNI.AutoPtr_InputDeviceMessage___deref____SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new InputDeviceMessage(cPtr, false);
  }

  public InputDeviceMessage __ref__() {
    return new InputDeviceMessage(MyoushuJNI.AutoPtr_InputDeviceMessage___ref____SWIG_0(swigCPtr, this), false);
  }

  public InputDeviceMessage get() {
    long cPtr = MyoushuJNI.AutoPtr_InputDeviceMessage_get__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new InputDeviceMessage(cPtr, false);
  }

  public boolean isNull() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_isNull(swigCPtr, this);
  }

  public InputDeviceMessage duplicate() {
    long cPtr = MyoushuJNI.AutoPtr_InputDeviceMessage_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new InputDeviceMessage(cPtr, false);
  }

  public long getDS_BUTTON_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_BUTTON_INDEX_get(swigCPtr, this);
  }

  public long getDS_BUTTONS_STATE_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_BUTTONS_STATE_INDEX_get(swigCPtr, this);
  }

  public long getDS_X_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_X_INDEX_get(swigCPtr, this);
  }

  public long getDS_Y_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_Y_INDEX_get(swigCPtr, this);
  }

  public long getDS_Z_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_Z_INDEX_get(swigCPtr, this);
  }

  public long getDS_X_REL_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_X_REL_INDEX_get(swigCPtr, this);
  }

  public long getDS_Y_REL_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_Y_REL_INDEX_get(swigCPtr, this);
  }

  public long getDS_Z_REL_INDEX() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_DS_Z_REL_INDEX_get(swigCPtr, this);
  }

  public String getClassName() {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_getClassName(swigCPtr, this);
  }

  public InputDevice getInputDevice() {
    long cPtr = MyoushuJNI.AutoPtr_InputDeviceMessage_getInputDevice(swigCPtr, this);
    return (cPtr == 0) ? null : new InputDevice(cPtr, false);
  }

  public InputDevice.InputDeviceType getDeviceType() {
    return InputDevice.InputDeviceType.swigToEnum(MyoushuJNI.AutoPtr_InputDeviceMessage_getDeviceType(swigCPtr, this));
  }

  public InputDeviceMessage.DeviceAction getDeviceAction() {
    return InputDeviceMessage.DeviceAction.swigToEnum(MyoushuJNI.AutoPtr_InputDeviceMessage_getDeviceAction(swigCPtr, this));
  }

  public float getActionVector(long index) {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_getActionVector__SWIG_0(swigCPtr, this, index);
  }

  public void getActionVector(Vector3 destVector) {
    MyoushuJNI.AutoPtr_InputDeviceMessage_getActionVector__SWIG_1(swigCPtr, this, Vector3.getCPtr(destVector), destVector);
  }

  public int getDeviceState(long index) {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_getDeviceState(swigCPtr, this, index);
  }

  public String getInputIdentifier(long index) {
    return MyoushuJNI.AutoPtr_InputDeviceMessage_getInputIdentifier(swigCPtr, this, index);
  }

  public void clone(InputDeviceMessage dest) {
    MyoushuJNI.AutoPtr_InputDeviceMessage_clone(swigCPtr, this, InputDeviceMessage.getCPtr(dest), dest);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size, Serializable.SerializationTarget sTarget) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.AutoPtr_InputDeviceMessage_serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size), sTarget.swigValue()), true);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.AutoPtr_InputDeviceMessage_serialize__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size)), true);
  }

  public SWIGTYPE_p_Poco__Net__IPAddress getCreator() {
    return new SWIGTYPE_p_Poco__Net__IPAddress(MyoushuJNI.AutoPtr_InputDeviceMessage_getCreator(swigCPtr, this), true);
  }

}
