/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ColourValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ColourValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ColourValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ColourValue(swigCPtr);
    }
    swigCPtr = 0;
  }

  public static ColourValue getZERO() {
    long cPtr = MyoushuJNI.ColourValue_ZERO_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public static ColourValue getBlack() {
    long cPtr = MyoushuJNI.ColourValue_Black_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public static ColourValue getWhite() {
    long cPtr = MyoushuJNI.ColourValue_White_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public static ColourValue getRed() {
    long cPtr = MyoushuJNI.ColourValue_Red_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public static ColourValue getGreen() {
    long cPtr = MyoushuJNI.ColourValue_Green_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public static ColourValue getBlue() {
    long cPtr = MyoushuJNI.ColourValue_Blue_get();
    return (cPtr == 0) ? null : new ColourValue(cPtr, false);
  }

  public ColourValue(float red, float green, float blue, float alpha) {
    this(MyoushuJNI.new_ColourValue__SWIG_0(red, green, blue, alpha), true);
  }

  public ColourValue(float red, float green, float blue) {
    this(MyoushuJNI.new_ColourValue__SWIG_1(red, green, blue), true);
  }

  public ColourValue(float red, float green) {
    this(MyoushuJNI.new_ColourValue__SWIG_2(red, green), true);
  }

  public ColourValue(float red) {
    this(MyoushuJNI.new_ColourValue__SWIG_3(red), true);
  }

  public ColourValue() {
    this(MyoushuJNI.new_ColourValue__SWIG_4(), true);
  }

  public void setR(float value) {
    MyoushuJNI.ColourValue_r_set(swigCPtr, this, value);
  }

  public float getR() {
    return MyoushuJNI.ColourValue_r_get(swigCPtr, this);
  }

  public void setG(float value) {
    MyoushuJNI.ColourValue_g_set(swigCPtr, this, value);
  }

  public float getG() {
    return MyoushuJNI.ColourValue_g_get(swigCPtr, this);
  }

  public void setB(float value) {
    MyoushuJNI.ColourValue_b_set(swigCPtr, this, value);
  }

  public float getB() {
    return MyoushuJNI.ColourValue_b_get(swigCPtr, this);
  }

  public void setA(float value) {
    MyoushuJNI.ColourValue_a_set(swigCPtr, this, value);
  }

  public float getA() {
    return MyoushuJNI.ColourValue_a_get(swigCPtr, this);
  }

  public long getAsRGBA() {
    return MyoushuJNI.ColourValue_getAsRGBA(swigCPtr, this);
  }

  public long getAsARGB() {
    return MyoushuJNI.ColourValue_getAsARGB(swigCPtr, this);
  }

  public long getAsBGRA() {
    return MyoushuJNI.ColourValue_getAsBGRA(swigCPtr, this);
  }

  public long getAsABGR() {
    return MyoushuJNI.ColourValue_getAsABGR(swigCPtr, this);
  }

  public void setAsRGBA(long val) {
    MyoushuJNI.ColourValue_setAsRGBA(swigCPtr, this, val);
  }

  public void setAsARGB(long val) {
    MyoushuJNI.ColourValue_setAsARGB(swigCPtr, this, val);
  }

  public void setAsBGRA(long val) {
    MyoushuJNI.ColourValue_setAsBGRA(swigCPtr, this, val);
  }

  public void setAsABGR(long val) {
    MyoushuJNI.ColourValue_setAsABGR(swigCPtr, this, val);
  }

  public void saturate() {
    MyoushuJNI.ColourValue_saturate(swigCPtr, this);
  }

  public ColourValue saturateCopy() {
    return new ColourValue(MyoushuJNI.ColourValue_saturateCopy(swigCPtr, this), true);
  }

  public SWIGTYPE_p_float ptr() {
    long cPtr = MyoushuJNI.ColourValue_ptr__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setHSB(float hue, float saturation, float brightness) {
    MyoushuJNI.ColourValue_setHSB(swigCPtr, this, hue, saturation, brightness);
  }

  public void getHSB(SWIGTYPE_p_float hue, SWIGTYPE_p_float saturation, SWIGTYPE_p_float brightness) {
    MyoushuJNI.ColourValue_getHSB(swigCPtr, this, SWIGTYPE_p_float.getCPtr(hue), SWIGTYPE_p_float.getCPtr(saturation), SWIGTYPE_p_float.getCPtr(brightness));
  }

}
