/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ComboBox extends Edit {
  private long swigCPtr;

  public ComboBox(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGComboBoxUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ComboBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ComboBox() {
    this(MyoushuJNI.new_ComboBox(), true);
  }

  public long getItemCount() {
    return MyoushuJNI.ComboBox_getItemCount(swigCPtr, this);
  }

  public void insertItemAt(long _index, UString _name, SWIGTYPE_p_Ogre__Any _data) {
    MyoushuJNI.ComboBox_insertItemAt__SWIG_0(swigCPtr, this, _index, UString.getCPtr(_name), _name, SWIGTYPE_p_Ogre__Any.getCPtr(_data));
  }

  public void insertItemAt(long _index, UString _name) {
    MyoushuJNI.ComboBox_insertItemAt__SWIG_1(swigCPtr, this, _index, UString.getCPtr(_name), _name);
  }

  public void addItem(UString _name, SWIGTYPE_p_Ogre__Any _data) {
    MyoushuJNI.ComboBox_addItem__SWIG_0(swigCPtr, this, UString.getCPtr(_name), _name, SWIGTYPE_p_Ogre__Any.getCPtr(_data));
  }

  public void addItem(UString _name) {
    MyoushuJNI.ComboBox_addItem__SWIG_1(swigCPtr, this, UString.getCPtr(_name), _name);
  }

  public void removeItemAt(long _index) {
    MyoushuJNI.ComboBox_removeItemAt(swigCPtr, this, _index);
  }

  public void removeAllItems() {
    MyoushuJNI.ComboBox_removeAllItems(swigCPtr, this);
  }

  public long findItemIndexWith(UString _name) {
    return MyoushuJNI.ComboBox_findItemIndexWith(swigCPtr, this, UString.getCPtr(_name), _name);
  }

  public long getIndexSelected() {
    return MyoushuJNI.ComboBox_getIndexSelected(swigCPtr, this);
  }

  public void setIndexSelected(long _index) {
    MyoushuJNI.ComboBox_setIndexSelected(swigCPtr, this, _index);
  }

  public void clearIndexSelected() {
    MyoushuJNI.ComboBox_clearIndexSelected(swigCPtr, this);
  }

  public void setItemDataAt(long _index, SWIGTYPE_p_Ogre__Any _data) {
    MyoushuJNI.ComboBox_setItemDataAt(swigCPtr, this, _index, SWIGTYPE_p_Ogre__Any.getCPtr(_data));
  }

  public void clearItemDataAt(long _index) {
    MyoushuJNI.ComboBox_clearItemDataAt(swigCPtr, this, _index);
  }

  public void setItemNameAt(long _index, UString _name) {
    MyoushuJNI.ComboBox_setItemNameAt(swigCPtr, this, _index, UString.getCPtr(_name), _name);
  }

  public UString getItemNameAt(long _index) {
    return new UString(MyoushuJNI.ComboBox_getItemNameAt(swigCPtr, this, _index), false);
  }

  public void beginToItemAt(long _index) {
    MyoushuJNI.ComboBox_beginToItemAt(swigCPtr, this, _index);
  }

  public void beginToItemFirst() {
    MyoushuJNI.ComboBox_beginToItemFirst(swigCPtr, this);
  }

  public void beginToItemLast() {
    MyoushuJNI.ComboBox_beginToItemLast(swigCPtr, this);
  }

  public void beginToItemSelected() {
    MyoushuJNI.ComboBox_beginToItemSelected(swigCPtr, this);
  }

  public void setComboModeDrop(boolean _value) {
    MyoushuJNI.ComboBox_setComboModeDrop(swigCPtr, this, _value);
  }

  public boolean getComboModeDrop() {
    return MyoushuJNI.ComboBox_getComboModeDrop(swigCPtr, this);
  }

  public void setSmoothShow(boolean _value) {
    MyoushuJNI.ComboBox_setSmoothShow(swigCPtr, this, _value);
  }

  public boolean getSmoothShow() {
    return MyoushuJNI.ComboBox_getSmoothShow(swigCPtr, this);
  }

  public void setMaxListHeight(long _value) {
    MyoushuJNI.ComboBox_setMaxListHeight(swigCPtr, this, _value);
  }

  public long getMaxListHeight() {
    return MyoushuJNI.ComboBox_getMaxListHeight(swigCPtr, this);
  }

  public void setProperty(String _key, String _value) {
    MyoushuJNI.ComboBox_setProperty(swigCPtr, this, _key, _value);
  }

  public void setEventComboAccept(SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate1T_MyGUI__WidgetPtr_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t value) {
    MyoushuJNI.ComboBox_eventComboAccept_set(swigCPtr, this, SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate1T_MyGUI__WidgetPtr_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate1T_MyGUI__WidgetPtr_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t getEventComboAccept() {
    long cPtr = MyoushuJNI.ComboBox_eventComboAccept_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate1T_MyGUI__WidgetPtr_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t(cPtr, false);
  }

  public void setEventComboChangePosition(SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate2T_MyGUI__WidgetPtr_size_t_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t value) {
    MyoushuJNI.ComboBox_eventComboChangePosition_set(swigCPtr, this, SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate2T_MyGUI__WidgetPtr_size_t_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate2T_MyGUI__WidgetPtr_size_t_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t getEventComboChangePosition() {
    long cPtr = MyoushuJNI.ComboBox_eventComboChangePosition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyGUI__EventPairT_delegates__CDelegate2T_MyGUI__WidgetPtr_size_t_t_delegates__CDelegate2T_MyGUI__ComboBoxPtr_size_t_t_t(cPtr, false);
  }

  public void _initialise(WidgetStyle _style, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _coord, Align _align, WidgetSkinInfo _info, Widget _parent, ICroppedRectangle _croppedParent, IWidgetCreator _creator, String _name) {
    MyoushuJNI.ComboBox__initialise(swigCPtr, this, WidgetStyle.getCPtr(_style), _style, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_coord), Align.getCPtr(_align), _align, WidgetSkinInfo.getCPtr(_info), _info, Widget.getCPtr(_parent), _parent, ICroppedRectangle.getCPtr(_croppedParent), _croppedParent, IWidgetCreator.getCPtr(_creator), _creator, _name);
  }

  public long getItemIndexSelected() {
    return MyoushuJNI.ComboBox_getItemIndexSelected(swigCPtr, this);
  }

  public void setItemSelectedAt(long _index) {
    MyoushuJNI.ComboBox_setItemSelectedAt(swigCPtr, this, _index);
  }

  public void clearItemSelected() {
    MyoushuJNI.ComboBox_clearItemSelected(swigCPtr, this);
  }

  public void insertItem(long _index, UString _name) {
    MyoushuJNI.ComboBox_insertItem(swigCPtr, this, _index, UString.getCPtr(_name), _name);
  }

  public void setItem(long _index, UString _item) {
    MyoushuJNI.ComboBox_setItem(swigCPtr, this, _index, UString.getCPtr(_item), _item);
  }

  public UString getItem(long _index) {
    return new UString(MyoushuJNI.ComboBox_getItem(swigCPtr, this, _index), false);
  }

  public void deleteItem(long _index) {
    MyoushuJNI.ComboBox_deleteItem(swigCPtr, this, _index);
  }

  public void deleteAllItems() {
    MyoushuJNI.ComboBox_deleteAllItems(swigCPtr, this);
  }

  public long getItemSelect() {
    return MyoushuJNI.ComboBox_getItemSelect(swigCPtr, this);
  }

  public void resetItemSelect() {
    MyoushuJNI.ComboBox_resetItemSelect(swigCPtr, this);
  }

  public void setItemSelect(long _index) {
    MyoushuJNI.ComboBox_setItemSelect(swigCPtr, this, _index);
  }

}
