/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ConcurrentTask extends NamedObject_ConcurrentTask {
  private long swigCPtr;

  public ConcurrentTask(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGConcurrentTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ConcurrentTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_ConcurrentTask(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getClassName() {
    return MyoushuJNI.ConcurrentTask_getClassName(swigCPtr, this);
  }

  public String getName() {
    return MyoushuJNI.ConcurrentTask_getName(swigCPtr, this);
  }

  public void run() {
    MyoushuJNI.ConcurrentTask_run(swigCPtr, this);
  }

}
