/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ControllerTask extends NamedObject_ControllerTask {
  private long swigCPtr;

  public ControllerTask(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGControllerTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ControllerTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_ControllerTask(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ControllerTask(int priority, String name, long executionInterval, long iterationLimit) {
    this(MyoushuJNI.new_ControllerTask__SWIG_0(priority, name, executionInterval, iterationLimit), true);
  }

  public ControllerTask(int priority, String name, long executionInterval) {
    this(MyoushuJNI.new_ControllerTask__SWIG_1(priority, name, executionInterval), true);
  }

  public ControllerTask(int priority, String name) {
    this(MyoushuJNI.new_ControllerTask__SWIG_2(priority, name), true);
  }

  public ControllerTask() {
    this(MyoushuJNI.new_ControllerTask__SWIG_3(), true);
  }

  public String getClassName() {
    return MyoushuJNI.ControllerTask_getClassName(swigCPtr, this);
  }

  public void init() {
    MyoushuJNI.ControllerTask_init(swigCPtr, this);
  }

  public void suspend() {
    MyoushuJNI.ControllerTask_suspend(swigCPtr, this);
  }

  public void execute(long timeDelta) {
    MyoushuJNI.ControllerTask_execute(swigCPtr, this, timeDelta);
  }

  public void kill() {
    MyoushuJNI.ControllerTask_kill(swigCPtr, this);
  }

  public void receiveControllerTaskMessage(AutoPtr_ControllerTaskMessage message) {
    MyoushuJNI.ControllerTask_receiveControllerTaskMessage(swigCPtr, this, AutoPtr_ControllerTaskMessage.getCPtr(message), message);
  }

}
