/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Data() {
    this(MyoushuJNI.new_Data(), true);
  }

  public void setData(SWIGTYPE_p_unsigned_char _data, long _size) {
    MyoushuJNI.Data_setData(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(_data), _size);
  }

  public void setSize(long _size) {
    MyoushuJNI.Data_setSize(swigCPtr, this, _size);
  }

  public void release() {
    MyoushuJNI.Data_release(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = MyoushuJNI.Data_getData(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public long getSize() {
    return MyoushuJNI.Data_getSize(swigCPtr, this);
  }

}
