/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class GameLogEntityEntry extends RefCountedObject {
  private long swigCPtr;

  public GameLogEntityEntry(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGGameLogEntityEntryUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(GameLogEntityEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_GameLogEntityEntry(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public GameLogEntityEntry(VectorString attributeNames) {
    this(MyoushuJNI.new_GameLogEntityEntry(VectorString.getCPtr(attributeNames), attributeNames), true);
  }

  public VectorString getAttributeNames() {
    return new VectorString(MyoushuJNI.GameLogEntityEntry_getAttributeNames(swigCPtr, this), true);
  }

  public String getAttributeName(long index) {
    return MyoushuJNI.GameLogEntityEntry_getAttributeName(swigCPtr, this, index);
  }

  public long getNumberOfAttributes() {
    return MyoushuJNI.GameLogEntityEntry_getNumberOfAttributes(swigCPtr, this);
  }

  public void setValue(String attributeName, Value value) {
    MyoushuJNI.GameLogEntityEntry_setValue__SWIG_0(swigCPtr, this, attributeName, Value.getCPtr(value), value);
  }

  public void setValue(long index, Value value) {
    MyoushuJNI.GameLogEntityEntry_setValue__SWIG_1(swigCPtr, this, index, Value.getCPtr(value), value);
  }

  public Value getValue(String attributeName) {
    return new Value(MyoushuJNI.GameLogEntityEntry_getValue__SWIG_0(swigCPtr, this, attributeName), true);
  }

  public Value getValue(long index) {
    return new Value(MyoushuJNI.GameLogEntityEntry_getValue__SWIG_1(swigCPtr, this, index), true);
  }

  public boolean getChanged() {
    return MyoushuJNI.GameLogEntityEntry_getChanged(swigCPtr, this);
  }

  public void setChanged(boolean changed) {
    MyoushuJNI.GameLogEntityEntry_setChanged(swigCPtr, this, changed);
  }

}
