/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class GameObjectAction extends NamedInstance {
  private long swigCPtr;

  public GameObjectAction(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGGameObjectActionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(GameObjectAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_GameObjectAction(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public GameObjectAction() {
    this(MyoushuJNI.new_GameObjectAction__SWIG_0(), true);
  }

  public GameObjectAction(String name, GameObject gameObject, boolean toggleAction) {
    this(MyoushuJNI.new_GameObjectAction__SWIG_1(name, GameObject.getCPtr(gameObject), gameObject, toggleAction), true);
  }

  public GameObjectAction(String name, GameObject gameObject) {
    this(MyoushuJNI.new_GameObjectAction__SWIG_2(name, GameObject.getCPtr(gameObject), gameObject), true);
  }

  public String getClassName() {
    return MyoushuJNI.GameObjectAction_getClassName(swigCPtr, this);
  }

  public void setStartCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackBaseT_void_Myoushu__GameObjectAction_t startCallback) {
    MyoushuJNI.GameObjectAction_setStartCallback__SWIG_0(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackBaseT_void_Myoushu__GameObjectAction_t.getCPtr(startCallback));
  }

  public void setStartCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackGlobalFunction functionPtr) {
    MyoushuJNI.GameObjectAction_setStartCallback__SWIG_1(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackGlobalFunction.getCPtr(functionPtr));
  }

  public void setStartCallback(String luaFunction) {
    MyoushuJNI.GameObjectAction_setStartCallback__SWIG_2(swigCPtr, this, luaFunction);
  }

  public void setStartCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackLuaFunctor luaFunction) {
    MyoushuJNI.GameObjectAction_setStartCallback__SWIG_3(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackLuaFunctor.getCPtr(luaFunction));
  }

  public void setStopCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackBaseT_void_Myoushu__GameObjectAction_t stopCallback) {
    MyoushuJNI.GameObjectAction_setStopCallback__SWIG_0(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackBaseT_void_Myoushu__GameObjectAction_t.getCPtr(stopCallback));
  }

  public void setStopCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackGlobalFunction functionPtr) {
    MyoushuJNI.GameObjectAction_setStopCallback__SWIG_1(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackGlobalFunction.getCPtr(functionPtr));
  }

  public void setStopCallback(String luaFunction) {
    MyoushuJNI.GameObjectAction_setStopCallback__SWIG_2(swigCPtr, this, luaFunction);
  }

  public void setStopCallback(SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackLuaFunctor luaFunction) {
    MyoushuJNI.GameObjectAction_setStopCallback__SWIG_3(swigCPtr, this, SWIGTYPE_p_Myoushu__ActionStringCallbackT_void_Myoushu__GameObjectAction_t__ActionStringCallbackLuaFunctor.getCPtr(luaFunction));
  }

  public void startAction() {
    MyoushuJNI.GameObjectAction_startAction(swigCPtr, this);
  }

  public void stopAction() {
    MyoushuJNI.GameObjectAction_stopAction(swigCPtr, this);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size, Serializable.SerializationTarget sTarget) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.GameObjectAction_serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size), sTarget.swigValue()), true);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.GameObjectAction_serialize__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size)), true);
  }

  public SWIGTYPE_p_uint32_t populateInstance(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size, Serializable.SerializationTarget sTarget) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.GameObjectAction_populateInstance__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size), sTarget.swigValue()), true);
  }

  public SWIGTYPE_p_uint32_t populateInstance(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.GameObjectAction_populateInstance__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size)), true);
  }

}
