/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class GUIManager extends Singleton_GUIManager {
  private long swigCPtr;

  public GUIManager(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGGUIManagerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(GUIManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_GUIManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GUIManager(SWIGTYPE_p_MyGUI__Gui mGUI) {
    this(MyoushuJNI.new_GUIManager(SWIGTYPE_p_MyGUI__Gui.getCPtr(mGUI)), true);
  }

  public void loadSkin(String skinFile, String resourceGroup) {
    MyoushuJNI.GUIManager_loadSkin__SWIG_0(swigCPtr, this, skinFile, resourceGroup);
  }

  public void loadSkin(String skinFile) {
    MyoushuJNI.GUIManager_loadSkin__SWIG_1(swigCPtr, this, skinFile);
  }

  public void loadLayout(String layoutFile, String resourceGroup, boolean visible) {
    MyoushuJNI.GUIManager_loadLayout__SWIG_0(swigCPtr, this, layoutFile, resourceGroup, visible);
  }

  public void loadLayout(String layoutFile, String resourceGroup) {
    MyoushuJNI.GUIManager_loadLayout__SWIG_1(swigCPtr, this, layoutFile, resourceGroup);
  }

  public void loadLayout(String layoutFile) {
    MyoushuJNI.GUIManager_loadLayout__SWIG_2(swigCPtr, this, layoutFile);
  }

  public void hideWidget(String widgetName) {
    MyoushuJNI.GUIManager_hideWidget(swigCPtr, this, widgetName);
  }

  public void showWidget(String widgetName) {
    MyoushuJNI.GUIManager_showWidget(swigCPtr, this, widgetName);
  }

  public void destroyWidgetDelayed(String widgetName) {
    MyoushuJNI.GUIManager_destroyWidgetDelayed(swigCPtr, this, widgetName);
  }

  public void destroyWidget(String widgetName) {
    MyoushuJNI.GUIManager_destroyWidget(swigCPtr, this, widgetName);
  }

  public Widget getWidget(String widgetName) {
    long cPtr = MyoushuJNI.GUIManager_getWidget(swigCPtr, this, widgetName);
    return (cPtr == 0) ? null : new Widget(cPtr, false);
  }

  public void showCursor() {
    MyoushuJNI.GUIManager_showCursor(swigCPtr, this);
  }

  public void hideCursor() {
    MyoushuJNI.GUIManager_hideCursor(swigCPtr, this);
  }

  public void createWidgetDelayed(String name, String type, Vector2 position, Vector2 size, String text, boolean relative, boolean visible) {
    MyoushuJNI.GUIManager_createWidgetDelayed__SWIG_0(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text, relative, visible);
  }

  public void createWidgetDelayed(String name, String type, Vector2 position, Vector2 size, String text, boolean relative) {
    MyoushuJNI.GUIManager_createWidgetDelayed__SWIG_1(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text, relative);
  }

  public void createWidgetDelayed(String name, String type, Vector2 position, Vector2 size, String text) {
    MyoushuJNI.GUIManager_createWidgetDelayed__SWIG_2(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text);
  }

  public Widget createWidget(String name, String type, Vector2 position, Vector2 size, String text, boolean relative, boolean visible) {
    long cPtr = MyoushuJNI.GUIManager_createWidget__SWIG_0(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text, relative, visible);
    return (cPtr == 0) ? null : new Widget(cPtr, false);
  }

  public Widget createWidget(String name, String type, Vector2 position, Vector2 size, String text, boolean relative) {
    long cPtr = MyoushuJNI.GUIManager_createWidget__SWIG_1(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text, relative);
    return (cPtr == 0) ? null : new Widget(cPtr, false);
  }

  public Widget createWidget(String name, String type, Vector2 position, Vector2 size, String text) {
    long cPtr = MyoushuJNI.GUIManager_createWidget__SWIG_2(swigCPtr, this, name, type, Vector2.getCPtr(position), position, Vector2.getCPtr(size), size, text);
    return (cPtr == 0) ? null : new Widget(cPtr, false);
  }

  public void setMouseFocus(String widgetName) {
    MyoushuJNI.GUIManager_setMouseFocus(swigCPtr, this, widgetName);
  }

  public void setKeyFocus(String widgetName) {
    MyoushuJNI.GUIManager_setKeyFocus(swigCPtr, this, widgetName);
  }

  public void clearMouseFocus() {
    MyoushuJNI.GUIManager_clearMouseFocus(swigCPtr, this);
  }

  public void clearKeyFocus() {
    MyoushuJNI.GUIManager_clearKeyFocus(swigCPtr, this);
  }

  public void translateCaptions() {
    MyoushuJNI.GUIManager_translateCaptions(swigCPtr, this);
  }

  public void translateCaption(String widgetName) {
    MyoushuJNI.GUIManager_translateCaption(swigCPtr, this, widgetName);
  }

  public void registerCallbacks(String widgetName) {
    MyoushuJNI.GUIManager_registerCallbacks(swigCPtr, this, widgetName);
  }

  public void myguiEventMouseButtonClick(Widget widget) {
    MyoushuJNI.GUIManager_myguiEventMouseButtonClick(swigCPtr, this, Widget.getCPtr(widget), widget);
  }

  public void myguiEventMouseButtonDoubleClick(Widget widget) {
    MyoushuJNI.GUIManager_myguiEventMouseButtonDoubleClick(swigCPtr, this, Widget.getCPtr(widget), widget);
  }

  public void myguiEventMouseButtonPressed(Widget widget, int left, int top, MouseButton id) {
    MyoushuJNI.GUIManager_myguiEventMouseButtonPressed(swigCPtr, this, Widget.getCPtr(widget), widget, left, top, MouseButton.getCPtr(id), id);
  }

  public void myguiEventMouseButtonReleased(Widget widget, int left, int top, MouseButton id) {
    MyoushuJNI.GUIManager_myguiEventMouseButtonReleased(swigCPtr, this, Widget.getCPtr(widget), widget, left, top, MouseButton.getCPtr(id), id);
  }

  public void myguiEventMouseSetFocus(Widget sender, Widget old) {
    MyoushuJNI.GUIManager_myguiEventMouseSetFocus(swigCPtr, this, Widget.getCPtr(sender), sender, Widget.getCPtr(old), old);
  }

  public void myguiEventRootMouseChangeFocus(Widget sender, boolean focus) {
    MyoushuJNI.GUIManager_myguiEventRootMouseChangeFocus(swigCPtr, this, Widget.getCPtr(sender), sender, focus);
  }

  public void myguiEventMouseLostFocus(Widget sender, Widget newW) {
    MyoushuJNI.GUIManager_myguiEventMouseLostFocus(swigCPtr, this, Widget.getCPtr(sender), sender, Widget.getCPtr(newW), newW);
  }

  public void myguiEventKeyButtonReleased(Widget widget, KeyCode keyCode) {
    MyoushuJNI.GUIManager_myguiEventKeyButtonReleased(swigCPtr, this, Widget.getCPtr(widget), widget, KeyCode.getCPtr(keyCode), keyCode);
  }

  public void myguiEventRootKeyChangeFocus(Widget sender, boolean focus) {
    MyoushuJNI.GUIManager_myguiEventRootKeyChangeFocus(swigCPtr, this, Widget.getCPtr(sender), sender, focus);
  }

  public void myguiEventEditSelectAccept(Widget sender) {
    MyoushuJNI.GUIManager_myguiEventEditSelectAccept(swigCPtr, this, Widget.getCPtr(sender), sender);
  }

  public void myguiEventEditTextChange(Widget sender) {
    MyoushuJNI.GUIManager_myguiEventEditTextChange(swigCPtr, this, Widget.getCPtr(sender), sender);
  }

  public void myguiEventListSelectAccept(List sender, long index) {
    MyoushuJNI.GUIManager_myguiEventListSelectAccept(swigCPtr, this, List.getCPtr(sender), sender, index);
  }

  public void myguiEventListChangePosition(List sender, long index) {
    MyoushuJNI.GUIManager_myguiEventListChangePosition(swigCPtr, this, List.getCPtr(sender), sender, index);
  }

  public void myguiEventMultiListSelectAccept(MultiList sender, long index) {
    MyoushuJNI.GUIManager_myguiEventMultiListSelectAccept(swigCPtr, this, MultiList.getCPtr(sender), sender, index);
  }

  public void myguiEventMultiListChangePosition(MultiList sender, long index) {
    MyoushuJNI.GUIManager_myguiEventMultiListChangePosition(swigCPtr, this, MultiList.getCPtr(sender), sender, index);
  }

  public void myguiEventComboAccept(ComboBox sender, long index) {
    MyoushuJNI.GUIManager_myguiEventComboAccept(swigCPtr, this, ComboBox.getCPtr(sender), sender, index);
  }

  public void myguiEventComboChangePosition(ComboBox sender, long index) {
    MyoushuJNI.GUIManager_myguiEventComboChangePosition(swigCPtr, this, ComboBox.getCPtr(sender), sender, index);
  }

}
