/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class InputTask extends NamedObject_InputTask {
  private long swigCPtr;

  public InputTask(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGInputTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(InputTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_InputTask(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static float getDEFAULT_MOUSE_SENSITIVITY() {
    return MyoushuJNI.InputTask_DEFAULT_MOUSE_SENSITIVITY_get();
  }

  public InputTask(int priority, String name, long executionInterval, long iterationLimit) {
    this(MyoushuJNI.new_InputTask__SWIG_0(priority, name, executionInterval, iterationLimit), true);
  }

  public InputTask(int priority, String name, long executionInterval) {
    this(MyoushuJNI.new_InputTask__SWIG_1(priority, name, executionInterval), true);
  }

  public InputTask(int priority, String name) {
    this(MyoushuJNI.new_InputTask__SWIG_2(priority, name), true);
  }

  public InputTask() {
    this(MyoushuJNI.new_InputTask__SWIG_3(), true);
  }

  public String getClassName() {
    return MyoushuJNI.InputTask_getClassName(swigCPtr, this);
  }

  public void init() {
    MyoushuJNI.InputTask_init(swigCPtr, this);
  }

  public void suspend() {
    MyoushuJNI.InputTask_suspend(swigCPtr, this);
  }

  public void execute(long timeDelta) {
    MyoushuJNI.InputTask_execute(swigCPtr, this, timeDelta);
  }

  public void kill() {
    MyoushuJNI.InputTask_kill(swigCPtr, this);
  }

  public void receiveInputDeviceMessage(AutoPtr_InputDeviceMessage message) {
    MyoushuJNI.InputTask_receiveInputDeviceMessage(swigCPtr, this, AutoPtr_InputDeviceMessage.getCPtr(message), message);
  }

}
