/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ListUInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ListUInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ListUInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_ListUInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListUInt() {
    this(MyoushuJNI.new_ListUInt__SWIG_0(), true);
  }

  public ListUInt(ListUInt arg0) {
    this(MyoushuJNI.new_ListUInt__SWIG_1(ListUInt.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return MyoushuJNI.ListUInt_size(swigCPtr, this);
  }

  public boolean empty() {
    return MyoushuJNI.ListUInt_empty(swigCPtr, this);
  }

  public void clear() {
    MyoushuJNI.ListUInt_clear(swigCPtr, this);
  }

  public void push_back(long val) {
    MyoushuJNI.ListUInt_push_back(swigCPtr, this, val);
  }

  public void pop_back() {
    MyoushuJNI.ListUInt_pop_back(swigCPtr, this);
  }

  public long front() {
    return MyoushuJNI.ListUInt_front(swigCPtr, this);
  }

  public long back() {
    return MyoushuJNI.ListUInt_back(swigCPtr, this);
  }

}
