/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class MapConfiguration extends AbstractConfiguration {
  private long swigCPtr;

  public MapConfiguration(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGMapConfigurationUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MapConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public MapConfiguration() {
    this(MyoushuJNI.new_MapConfiguration(), true);
  }

  public void clear() {
    MyoushuJNI.MapConfiguration_clear(swigCPtr, this);
  }

}
