/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public enum MouseButtonObsolete {
  MB_Left(MyoushuJNI.MB_Left_get()),
  MB_Right,
  MB_Middle,
  MB_Button0(MyoushuJNI.MB_Button0_get()),
  MB_Button1,
  MB_Button2,
  MB_Button3,
  MB_Button4,
  MB_Button5,
  MB_Button6,
  MB_Button7,
  MB_None(MyoushuJNI.MB_None_get());

  public final int swigValue() {
    return swigValue;
  }

  public static MouseButtonObsolete swigToEnum(int swigValue) {
    MouseButtonObsolete[] swigValues = MouseButtonObsolete.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MouseButtonObsolete swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MouseButtonObsolete.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MouseButtonObsolete() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MouseButtonObsolete(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MouseButtonObsolete(MouseButtonObsolete swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

