/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class NamedObjectFactory_Scene extends NamedObjectFactoryBase {
  private long swigCPtr;

  public NamedObjectFactory_Scene(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGNamedObjectFactory_SceneUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(NamedObjectFactory_Scene obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_NamedObjectFactory_Scene(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__Scene_t_t__const_iterator begin() {
    return new SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__Scene_t_t__const_iterator(MyoushuJNI.NamedObjectFactory_Scene_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__Scene_t_t__const_iterator end() {
    return new SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__Scene_t_t__const_iterator(MyoushuJNI.NamedObjectFactory_Scene_end__SWIG_0(swigCPtr, this), true);
  }

  public void add(Scene obj) {
    MyoushuJNI.NamedObjectFactory_Scene_add(swigCPtr, this, Scene.getCPtr(obj), obj);
  }

  public boolean remove(Scene obj) {
    return MyoushuJNI.NamedObjectFactory_Scene_remove(swigCPtr, this, Scene.getCPtr(obj), obj);
  }

  public boolean removeByName(String name) {
    return MyoushuJNI.NamedObjectFactory_Scene_removeByName(swigCPtr, this, name);
  }

  public Scene find(String name) {
    long cPtr = MyoushuJNI.NamedObjectFactory_Scene_find(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Scene(cPtr, false);
  }

  public NamedInstance findByName(String name) {
    long cPtr = MyoushuJNI.NamedObjectFactory_Scene_findByName(swigCPtr, this, name);
    return (cPtr == 0) ? null : new NamedInstance(cPtr, false);
  }

  public void clear() {
    MyoushuJNI.NamedObjectFactory_Scene_clear(swigCPtr, this);
  }

  public void acquireReadLock() {
    MyoushuJNI.NamedObjectFactory_Scene_acquireReadLock(swigCPtr, this);
  }

  public void releaseLock() {
    MyoushuJNI.NamedObjectFactory_Scene_releaseLock(swigCPtr, this);
  }

}
