/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class NamedObjectFactory_FunctorBase extends NamedObjectFactoryBase {
  private long swigCPtr;

  public NamedObjectFactory_FunctorBase(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGNamedObjectFactory_FunctorBaseUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(NamedObjectFactory_FunctorBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_NamedObjectFactory_FunctorBase(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__FunctorBase_t_t__const_iterator begin() {
    return new SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__FunctorBase_t_t__const_iterator(MyoushuJNI.NamedObjectFactory_FunctorBase_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__FunctorBase_t_t__const_iterator end() {
    return new SWIGTYPE_p_std__mapT_Ogre__String_Poco__AutoPtrT_Myoushu__FunctorBase_t_t__const_iterator(MyoushuJNI.NamedObjectFactory_FunctorBase_end__SWIG_0(swigCPtr, this), true);
  }

  public void add(FunctorBase obj) {
    MyoushuJNI.NamedObjectFactory_FunctorBase_add(swigCPtr, this, FunctorBase.getCPtr(obj), obj);
  }

  public boolean remove(FunctorBase obj) {
    return MyoushuJNI.NamedObjectFactory_FunctorBase_remove(swigCPtr, this, FunctorBase.getCPtr(obj), obj);
  }

  public boolean removeByName(String name) {
    return MyoushuJNI.NamedObjectFactory_FunctorBase_removeByName(swigCPtr, this, name);
  }

  public FunctorBase find(String name) {
    long cPtr = MyoushuJNI.NamedObjectFactory_FunctorBase_find(swigCPtr, this, name);
    return (cPtr == 0) ? null : new FunctorBase(cPtr, false);
  }

  public NamedInstance findByName(String name) {
    long cPtr = MyoushuJNI.NamedObjectFactory_FunctorBase_findByName(swigCPtr, this, name);
    return (cPtr == 0) ? null : new NamedInstance(cPtr, false);
  }

  public void clear() {
    MyoushuJNI.NamedObjectFactory_FunctorBase_clear(swigCPtr, this);
  }

  public void acquireReadLock() {
    MyoushuJNI.NamedObjectFactory_FunctorBase_acquireReadLock(swigCPtr, this);
  }

  public void releaseLock() {
    MyoushuJNI.NamedObjectFactory_FunctorBase_releaseLock(swigCPtr, this);
  }

}
