/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Pose {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Pose(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Pose obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Pose(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pose() {
    this(MyoushuJNI.new_Pose__SWIG_0(), true);
  }

  public Pose(Vector3 arg0) {
    this(MyoushuJNI.new_Pose__SWIG_1(Vector3.getCPtr(arg0), arg0), true);
  }

  public Pose(Quaternion arg0) {
    this(MyoushuJNI.new_Pose__SWIG_2(Quaternion.getCPtr(arg0), arg0), true);
  }

  public Pose(Vector3 arg0, Quaternion arg1) {
    this(MyoushuJNI.new_Pose__SWIG_3(Vector3.getCPtr(arg0), arg0, Quaternion.getCPtr(arg1), arg1), true);
  }

  public Pose(SWIGTYPE_p_NxVec3 arg0, SWIGTYPE_p_NxQuat arg1) {
    this(MyoushuJNI.new_Pose__SWIG_4(SWIGTYPE_p_NxVec3.getCPtr(arg0), SWIGTYPE_p_NxQuat.getCPtr(arg1)), true);
  }

  public Pose(SWIGTYPE_p_NxVec3 arg0) {
    this(MyoushuJNI.new_Pose__SWIG_5(SWIGTYPE_p_NxVec3.getCPtr(arg0)), true);
  }

  public Pose(SWIGTYPE_p_NxQuat arg0) {
    this(MyoushuJNI.new_Pose__SWIG_6(SWIGTYPE_p_NxQuat.getCPtr(arg0)), true);
  }

  public Pose(float _x, float _y, float _z) {
    this(MyoushuJNI.new_Pose__SWIG_7(_x, _y, _z), true);
  }

  public Pose(float _w, float _x, float _y, float _z) {
    this(MyoushuJNI.new_Pose__SWIG_8(_w, _x, _y, _z), true);
  }

  public void id() {
    MyoushuJNI.Pose_id(swigCPtr, this);
  }

  public void set(Vector3 _v) {
    MyoushuJNI.Pose_set__SWIG_0(swigCPtr, this, Vector3.getCPtr(_v), _v);
  }

  public void set(Quaternion _q) {
    MyoushuJNI.Pose_set__SWIG_1(swigCPtr, this, Quaternion.getCPtr(_q), _q);
  }

  public boolean isZero() {
    return MyoushuJNI.Pose_isZero(swigCPtr, this);
  }

  public void fromMat34(SWIGTYPE_p_NxMat34 arg0) {
    MyoushuJNI.Pose_fromMat34(swigCPtr, this, SWIGTYPE_p_NxMat34.getCPtr(arg0));
  }

  public SWIGTYPE_p_NxMat34 toMat34() {
    return new SWIGTYPE_p_NxMat34(MyoushuJNI.Pose_toMat34(swigCPtr, this), true);
  }

  public void fromMat33(SWIGTYPE_p_NxMat33 arg0) {
    MyoushuJNI.Pose_fromMat33(swigCPtr, this, SWIGTYPE_p_NxMat33.getCPtr(arg0));
  }

  public SWIGTYPE_p_NxMat33 toMat33() {
    return new SWIGTYPE_p_NxMat33(MyoushuJNI.Pose_toMat33(swigCPtr, this), true);
  }

  public Vector3 getVector3() {
    return new Vector3(MyoushuJNI.Pose_getVector3(swigCPtr, this), true);
  }

  public SWIGTYPE_p_NxVec3 getVec3() {
    return new SWIGTYPE_p_NxVec3(MyoushuJNI.Pose_getVec3(swigCPtr, this), true);
  }

  public Quaternion getQuaternion() {
    return new Quaternion(MyoushuJNI.Pose_getQuaternion(swigCPtr, this), true);
  }

  public SWIGTYPE_p_NxQuat getQuat() {
    return new SWIGTYPE_p_NxQuat(MyoushuJNI.Pose_getQuat(swigCPtr, this), true);
  }

  public void setV(SWIGTYPE_p_NxVec3 value) {
    MyoushuJNI.Pose_v_set(swigCPtr, this, SWIGTYPE_p_NxVec3.getCPtr(value));
  }

  public SWIGTYPE_p_NxVec3 getV() {
    return new SWIGTYPE_p_NxVec3(MyoushuJNI.Pose_v_get(swigCPtr, this), true);
  }

  public void setQ(SWIGTYPE_p_NxQuat value) {
    MyoushuJNI.Pose_q_set(swigCPtr, this, SWIGTYPE_p_NxQuat.getCPtr(value));
  }

  public SWIGTYPE_p_NxQuat getQ() {
    return new SWIGTYPE_p_NxQuat(MyoushuJNI.Pose_q_get(swigCPtr, this), true);
  }

}
