/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ReplayTaskManager extends Singleton_ReplayTaskManager {
  private long swigCPtr;

  public ReplayTaskManager(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGReplayTaskManagerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ReplayTaskManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ReplayTaskManager(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ReplayTaskManager() {
    this(MyoushuJNI.new_ReplayTaskManager(), true);
  }

  public void play(String replayName, String group) {
    MyoushuJNI.ReplayTaskManager_play__SWIG_0(swigCPtr, this, replayName, group);
  }

  public void play(Replay pReplay) {
    MyoushuJNI.ReplayTaskManager_play__SWIG_1(swigCPtr, this, Replay.getCPtr(pReplay), pReplay);
  }

  public void record(String replayName, String group, boolean overwrite) {
    MyoushuJNI.ReplayTaskManager_record__SWIG_0(swigCPtr, this, replayName, group, overwrite);
  }

  public void record(String replayName, String group) {
    MyoushuJNI.ReplayTaskManager_record__SWIG_1(swigCPtr, this, replayName, group);
  }

  public void record(Replay pReplay, boolean overwrite) {
    MyoushuJNI.ReplayTaskManager_record__SWIG_2(swigCPtr, this, Replay.getCPtr(pReplay), pReplay, overwrite);
  }

  public void record(Replay pReplay) {
    MyoushuJNI.ReplayTaskManager_record__SWIG_3(swigCPtr, this, Replay.getCPtr(pReplay), pReplay);
  }

  public void pause() {
    MyoushuJNI.ReplayTaskManager_pause(swigCPtr, this);
  }

  public void stop() {
    MyoushuJNI.ReplayTaskManager_stop(swigCPtr, this);
  }

}
