/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Scene extends NamedObject_Scene {
  private long swigCPtr;

  public Scene(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGSceneUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Scene obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Scene(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Scene(SWIGTYPE_p_NxOgre__Scene nxScene, SWIGTYPE_p_Ogre__SceneManager sceneManager) {
    this(MyoushuJNI.new_Scene__SWIG_0(SWIGTYPE_p_NxOgre__Scene.getCPtr(nxScene), SWIGTYPE_p_Ogre__SceneManager.getCPtr(sceneManager)), true);
  }

  public Scene(String name, SWIGTYPE_p_NxOgre__World world, SWIGTYPE_p_NxOgre__SceneParams sceneParams, SWIGTYPE_p_Ogre__SceneManager sceneManager) {
    this(MyoushuJNI.new_Scene__SWIG_1(name, SWIGTYPE_p_NxOgre__World.getCPtr(world), SWIGTYPE_p_NxOgre__SceneParams.getCPtr(sceneParams), SWIGTYPE_p_Ogre__SceneManager.getCPtr(sceneManager)), true);
  }

  public Scene(String name, String sceneTypeName, SWIGTYPE_p_NxOgre__World world, SWIGTYPE_p_NxOgre__SceneParams sceneParams) {
    this(MyoushuJNI.new_Scene__SWIG_2(name, sceneTypeName, SWIGTYPE_p_NxOgre__World.getCPtr(world), SWIGTYPE_p_NxOgre__SceneParams.getCPtr(sceneParams)), true);
  }

  public Scene(String name, SWIGTYPE_p_Ogre__SceneTypeMask sceneTypeMask, SWIGTYPE_p_NxOgre__World world, SWIGTYPE_p_NxOgre__SceneParams sceneParams) {
    this(MyoushuJNI.new_Scene__SWIG_3(name, SWIGTYPE_p_Ogre__SceneTypeMask.getCPtr(sceneTypeMask), SWIGTYPE_p_NxOgre__World.getCPtr(world), SWIGTYPE_p_NxOgre__SceneParams.getCPtr(sceneParams)), true);
  }

  public String getClassName() {
    return MyoushuJNI.Scene_getClassName(swigCPtr, this);
  }

  public void acquireLockOnOgreSceneManager(boolean write) {
    MyoushuJNI.Scene_acquireLockOnOgreSceneManager__SWIG_0(swigCPtr, this, write);
  }

  public void acquireLockOnOgreSceneManager() {
    MyoushuJNI.Scene_acquireLockOnOgreSceneManager__SWIG_1(swigCPtr, this);
  }

  public void acquireLockOnNxOgreScene(boolean write) {
    MyoushuJNI.Scene_acquireLockOnNxOgreScene__SWIG_0(swigCPtr, this, write);
  }

  public void acquireLockOnNxOgreScene() {
    MyoushuJNI.Scene_acquireLockOnNxOgreScene__SWIG_1(swigCPtr, this);
  }

  public void releaseLockOnOgreSceneManager() {
    MyoushuJNI.Scene_releaseLockOnOgreSceneManager(swigCPtr, this);
  }

  public void releaseLockOnNxOgreScene() {
    MyoushuJNI.Scene_releaseLockOnNxOgreScene(swigCPtr, this);
  }

  public SWIGTYPE_p_NxOgre__Scene getNxOgreScene() {
    long cPtr = MyoushuJNI.Scene_getNxOgreScene__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Scene(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SceneManager getOgreSceneManager() {
    long cPtr = MyoushuJNI.Scene_getOgreSceneManager__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__SceneManager(cPtr, false);
  }

  public ListGameObject getGameObjectsFromRaycast(Vector3 position, Vector3 direction, float range, SWIGTYPE_p_NxOgre__RayCaster__ActorFilter filter) {
    return new ListGameObject(MyoushuJNI.Scene_getGameObjectsFromRaycast__SWIG_0(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(direction), direction, range, SWIGTYPE_p_NxOgre__RayCaster__ActorFilter.getCPtr(filter)), true);
  }

  public ListGameObject getGameObjectsFromRaycast(Vector3 position, Vector3 direction, float range) {
    return new ListGameObject(MyoushuJNI.Scene_getGameObjectsFromRaycast__SWIG_1(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(direction), direction, range), true);
  }

  public GameObject getClosestGameObjectFromRaycast(Vector3 position, Vector3 direction, float range, SWIGTYPE_p_NxOgre__RayCaster__ActorFilter filter) {
    long cPtr = MyoushuJNI.Scene_getClosestGameObjectFromRaycast__SWIG_0(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(direction), direction, range, SWIGTYPE_p_NxOgre__RayCaster__ActorFilter.getCPtr(filter));
    return (cPtr == 0) ? null : new GameObject(cPtr, false);
  }

  public GameObject getClosestGameObjectFromRaycast(Vector3 position, Vector3 direction, float range) {
    long cPtr = MyoushuJNI.Scene_getClosestGameObjectFromRaycast__SWIG_1(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(direction), direction, range);
    return (cPtr == 0) ? null : new GameObject(cPtr, false);
  }

  public void getGameObjectsInCameraView(Camera camera, ListGameObject gameObjectList) {
    MyoushuJNI.Scene_getGameObjectsInCameraView(swigCPtr, this, Camera.getCPtr(camera), camera, ListGameObject.getCPtr(gameObjectList), gameObjectList);
  }

  public String getTypeName() {
    return MyoushuJNI.Scene_getTypeName(swigCPtr, this);
  }

  public Camera createCamera(String name) {
    long cPtr = MyoushuJNI.Scene_createCamera(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Camera(cPtr, false);
  }

  public Camera getCamera(String name) {
    long cPtr = MyoushuJNI.Scene_getCamera(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Camera(cPtr, false);
  }

  public boolean hasCamera(String name) {
    return MyoushuJNI.Scene_hasCamera(swigCPtr, this, name);
  }

  public void destroyCamera(Camera cam) {
    MyoushuJNI.Scene_destroyCamera__SWIG_0(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public void destroyCamera(String name) {
    MyoushuJNI.Scene_destroyCamera__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllCameras() {
    MyoushuJNI.Scene_destroyAllCameras(swigCPtr, this);
  }

  public Light createLight(String name) {
    long cPtr = MyoushuJNI.Scene_createLight(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Light(cPtr, false);
  }

  public Light getLight(String name) {
    long cPtr = MyoushuJNI.Scene_getLight(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Light(cPtr, false);
  }

  public boolean hasLight(String name) {
    return MyoushuJNI.Scene_hasLight(swigCPtr, this, name);
  }

  public void destroyLight(String name) {
    MyoushuJNI.Scene_destroyLight__SWIG_0(swigCPtr, this, name);
  }

  public void destroyLight(Light light) {
    MyoushuJNI.Scene_destroyLight__SWIG_1(swigCPtr, this, Light.getCPtr(light), light);
  }

  public void destroyAllLights() {
    MyoushuJNI.Scene_destroyAllLights(swigCPtr, this);
  }

  public void _notifyLightsDirty() {
    MyoushuJNI.Scene__notifyLightsDirty(swigCPtr, this);
  }

  public long _getLightsDirtyCounter() {
    return MyoushuJNI.Scene__getLightsDirtyCounter(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__Light_p_t _getLightsAffectingFrustum() {
    return new SWIGTYPE_p_std__vectorT_Ogre__Light_p_t(MyoushuJNI.Scene__getLightsAffectingFrustum(swigCPtr, this), false);
  }

  public void _populateLightList(Vector3 position, float radius, SWIGTYPE_p_std__vectorT_Ogre__Light_p_t destList) {
    MyoushuJNI.Scene__populateLightList(swigCPtr, this, Vector3.getCPtr(position), position, radius, SWIGTYPE_p_std__vectorT_Ogre__Light_p_t.getCPtr(destList));
  }

  public SceneNode createSceneNode() {
    long cPtr = MyoushuJNI.Scene_createSceneNode__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public SceneNode createSceneNode(String name) {
    long cPtr = MyoushuJNI.Scene_createSceneNode__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public void destroySceneNode(String name) {
    MyoushuJNI.Scene_destroySceneNode(swigCPtr, this, name);
  }

  public SceneNode getRootSceneNode() {
    long cPtr = MyoushuJNI.Scene_getRootSceneNode(swigCPtr, this);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public SceneNode getSceneNode(String name) {
    long cPtr = MyoushuJNI.Scene_getSceneNode(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public boolean hasSceneNode(String name) {
    return MyoushuJNI.Scene_hasSceneNode(swigCPtr, this, name);
  }

  public Entity createEntity(String entityName, String meshName) {
    long cPtr = MyoushuJNI.Scene_createEntity__SWIG_0(swigCPtr, this, entityName, meshName);
    return (cPtr == 0) ? null : new Entity(cPtr, false);
  }

  public Entity createEntity(String entityName, SWIGTYPE_p_Ogre__SceneManager__PrefabType ptype) {
    long cPtr = MyoushuJNI.Scene_createEntity__SWIG_1(swigCPtr, this, entityName, SWIGTYPE_p_Ogre__SceneManager__PrefabType.getCPtr(ptype));
    return (cPtr == 0) ? null : new Entity(cPtr, false);
  }

  public Entity getEntity(String name) {
    long cPtr = MyoushuJNI.Scene_getEntity(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Entity(cPtr, false);
  }

  public boolean hasEntity(String name) {
    return MyoushuJNI.Scene_hasEntity(swigCPtr, this, name);
  }

  public void destroyEntity(Entity ent) {
    MyoushuJNI.Scene_destroyEntity__SWIG_0(swigCPtr, this, Entity.getCPtr(ent), ent);
  }

  public void destroyEntity(String name) {
    MyoushuJNI.Scene_destroyEntity__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllEntities() {
    MyoushuJNI.Scene_destroyAllEntities(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__ManualObject createManualObject(String name) {
    long cPtr = MyoushuJNI.Scene_createManualObject(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__ManualObject(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__ManualObject getManualObject(String name) {
    long cPtr = MyoushuJNI.Scene_getManualObject(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__ManualObject(cPtr, false);
  }

  public boolean hasManualObject(String name) {
    return MyoushuJNI.Scene_hasManualObject(swigCPtr, this, name);
  }

  public void destroyManualObject(SWIGTYPE_p_Ogre__ManualObject obj) {
    MyoushuJNI.Scene_destroyManualObject__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__ManualObject.getCPtr(obj));
  }

  public void destroyManualObject(String name) {
    MyoushuJNI.Scene_destroyManualObject__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllManualObjects() {
    MyoushuJNI.Scene_destroyAllManualObjects(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__BillboardChain createBillboardChain(String name) {
    long cPtr = MyoushuJNI.Scene_createBillboardChain(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__BillboardChain(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__BillboardChain getBillboardChain(String name) {
    long cPtr = MyoushuJNI.Scene_getBillboardChain(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__BillboardChain(cPtr, false);
  }

  public boolean hasBillboardChain(String name) {
    return MyoushuJNI.Scene_hasBillboardChain(swigCPtr, this, name);
  }

  public void destroyBillboardChain(SWIGTYPE_p_Ogre__BillboardChain obj) {
    MyoushuJNI.Scene_destroyBillboardChain__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__BillboardChain.getCPtr(obj));
  }

  public void destroyBillboardChain(String name) {
    MyoushuJNI.Scene_destroyBillboardChain__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllBillboardChains() {
    MyoushuJNI.Scene_destroyAllBillboardChains(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__RibbonTrail createRibbonTrail(String name) {
    long cPtr = MyoushuJNI.Scene_createRibbonTrail(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RibbonTrail(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__RibbonTrail getRibbonTrail(String name) {
    long cPtr = MyoushuJNI.Scene_getRibbonTrail(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RibbonTrail(cPtr, false);
  }

  public boolean hasRibbonTrail(String name) {
    return MyoushuJNI.Scene_hasRibbonTrail(swigCPtr, this, name);
  }

  public void destroyRibbonTrail(SWIGTYPE_p_Ogre__RibbonTrail obj) {
    MyoushuJNI.Scene_destroyRibbonTrail__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__RibbonTrail.getCPtr(obj));
  }

  public void destroyRibbonTrail(String name) {
    MyoushuJNI.Scene_destroyRibbonTrail__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllRibbonTrails() {
    MyoushuJNI.Scene_destroyAllRibbonTrails(swigCPtr, this);
  }

  public ParticleSystem createParticleSystem(String name, String templateName) {
    long cPtr = MyoushuJNI.Scene_createParticleSystem__SWIG_0(swigCPtr, this, name, templateName);
    return (cPtr == 0) ? null : new ParticleSystem(cPtr, false);
  }

  public ParticleSystem createParticleSystem(String name, long quota, String resourceGroup) {
    long cPtr = MyoushuJNI.Scene_createParticleSystem__SWIG_1(swigCPtr, this, name, quota, resourceGroup);
    return (cPtr == 0) ? null : new ParticleSystem(cPtr, false);
  }

  public ParticleSystem createParticleSystem(String name, long quota) {
    long cPtr = MyoushuJNI.Scene_createParticleSystem__SWIG_2(swigCPtr, this, name, quota);
    return (cPtr == 0) ? null : new ParticleSystem(cPtr, false);
  }

  public ParticleSystem createParticleSystem(String name) {
    long cPtr = MyoushuJNI.Scene_createParticleSystem__SWIG_3(swigCPtr, this, name);
    return (cPtr == 0) ? null : new ParticleSystem(cPtr, false);
  }

  public ParticleSystem getParticleSystem(String name) {
    long cPtr = MyoushuJNI.Scene_getParticleSystem(swigCPtr, this, name);
    return (cPtr == 0) ? null : new ParticleSystem(cPtr, false);
  }

  public boolean hasParticleSystem(String name) {
    return MyoushuJNI.Scene_hasParticleSystem(swigCPtr, this, name);
  }

  public void destroyParticleSystem(ParticleSystem obj) {
    MyoushuJNI.Scene_destroyParticleSystem__SWIG_0(swigCPtr, this, ParticleSystem.getCPtr(obj), obj);
  }

  public void destroyParticleSystem(String name) {
    MyoushuJNI.Scene_destroyParticleSystem__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllParticleSystems() {
    MyoushuJNI.Scene_destroyAllParticleSystems(swigCPtr, this);
  }

  public void clearScene() {
    MyoushuJNI.Scene_clearScene(swigCPtr, this);
  }

  public void setAmbientLight(ColourValue colour) {
    MyoushuJNI.Scene_setAmbientLight(swigCPtr, this, ColourValue.getCPtr(colour), colour);
  }

  public ColourValue getAmbientLight() {
    return new ColourValue(MyoushuJNI.Scene_getAmbientLight(swigCPtr, this), false);
  }

  public void setWorldGeometry(String filename) {
    MyoushuJNI.Scene_setWorldGeometry__SWIG_0(swigCPtr, this, filename);
  }

  public void setWorldGeometry(SWIGTYPE_p_Ogre__DataStreamPtr stream, String typeName) {
    MyoushuJNI.Scene_setWorldGeometry__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__DataStreamPtr.getCPtr(stream), typeName);
  }

  public void setWorldGeometry(SWIGTYPE_p_Ogre__DataStreamPtr stream) {
    MyoushuJNI.Scene_setWorldGeometry__SWIG_2(swigCPtr, this, SWIGTYPE_p_Ogre__DataStreamPtr.getCPtr(stream));
  }

  public long estimateWorldGeometry(String filename) {
    return MyoushuJNI.Scene_estimateWorldGeometry__SWIG_0(swigCPtr, this, filename);
  }

  public long estimateWorldGeometry(SWIGTYPE_p_Ogre__DataStreamPtr stream, String typeName) {
    return MyoushuJNI.Scene_estimateWorldGeometry__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__DataStreamPtr.getCPtr(stream), typeName);
  }

  public long estimateWorldGeometry(SWIGTYPE_p_Ogre__DataStreamPtr stream) {
    return MyoushuJNI.Scene_estimateWorldGeometry__SWIG_2(swigCPtr, this, SWIGTYPE_p_Ogre__DataStreamPtr.getCPtr(stream));
  }

  public SWIGTYPE_p_Ogre__ViewPoint getSuggestedViewpoint(boolean random) {
    return new SWIGTYPE_p_Ogre__ViewPoint(MyoushuJNI.Scene_getSuggestedViewpoint__SWIG_0(swigCPtr, this, random), true);
  }

  public SWIGTYPE_p_Ogre__ViewPoint getSuggestedViewpoint() {
    return new SWIGTYPE_p_Ogre__ViewPoint(MyoushuJNI.Scene_getSuggestedViewpoint__SWIG_1(swigCPtr, this), true);
  }

  public boolean setOption(String strKey, SWIGTYPE_p_void pValue) {
    return MyoushuJNI.Scene_setOption(swigCPtr, this, strKey, SWIGTYPE_p_void.getCPtr(pValue));
  }

  public boolean getOption(String strKey, SWIGTYPE_p_void pDestValue) {
    return MyoushuJNI.Scene_getOption(swigCPtr, this, strKey, SWIGTYPE_p_void.getCPtr(pDestValue));
  }

  public boolean hasOption(String strKey) {
    return MyoushuJNI.Scene_hasOption(swigCPtr, this, strKey);
  }

  public boolean getOptionValues(String strKey, SWIGTYPE_p_Ogre__StringVector refValueList) {
    return MyoushuJNI.Scene_getOptionValues(swigCPtr, this, strKey, SWIGTYPE_p_Ogre__StringVector.getCPtr(refValueList));
  }

  public boolean getOptionKeys(SWIGTYPE_p_Ogre__StringVector refKeys) {
    return MyoushuJNI.Scene_getOptionKeys(swigCPtr, this, SWIGTYPE_p_Ogre__StringVector.getCPtr(refKeys));
  }

  public void _updateSceneGraph(Camera cam) {
    MyoushuJNI.Scene__updateSceneGraph(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public void _findVisibleObjects(Camera cam, SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo visibleBounds, boolean onlyShadowCasters) {
    MyoushuJNI.Scene__findVisibleObjects(swigCPtr, this, Camera.getCPtr(cam), cam, SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo.getCPtr(visibleBounds), onlyShadowCasters);
  }

  public void _applySceneAnimations() {
    MyoushuJNI.Scene__applySceneAnimations(swigCPtr, this);
  }

  public void _renderVisibleObjects() {
    MyoushuJNI.Scene__renderVisibleObjects(swigCPtr, this);
  }

  public void _renderScene(Camera camera, Viewport vp, boolean includeOverlays) {
    MyoushuJNI.Scene__renderScene(swigCPtr, this, Camera.getCPtr(camera), camera, Viewport.getCPtr(vp), vp, includeOverlays);
  }

  public void _queueSkiesForRendering(Camera cam) {
    MyoushuJNI.Scene__queueSkiesForRendering(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public void _setDestinationRenderSystem(SWIGTYPE_p_Ogre__RenderSystem sys) {
    MyoushuJNI.Scene__setDestinationRenderSystem(swigCPtr, this, SWIGTYPE_p_Ogre__RenderSystem.getCPtr(sys));
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling, boolean drawFirst, float bow, int xsegments, int ysegments, String groupName) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_0(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling, drawFirst, bow, xsegments, ysegments, groupName);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling, boolean drawFirst, float bow, int xsegments, int ysegments) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_1(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling, drawFirst, bow, xsegments, ysegments);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling, boolean drawFirst, float bow, int xsegments) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_2(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling, drawFirst, bow, xsegments);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling, boolean drawFirst, float bow) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_3(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling, drawFirst, bow);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling, boolean drawFirst) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_4(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling, drawFirst);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale, float tiling) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_5(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale, tiling);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName, float scale) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_6(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName, scale);
  }

  public void setSkyPlane(boolean enable, SWIGTYPE_p_Ogre__Plane plane, String materialName) {
    MyoushuJNI.Scene_setSkyPlane__SWIG_7(swigCPtr, this, enable, SWIGTYPE_p_Ogre__Plane.getCPtr(plane), materialName);
  }

  public SceneNode getSkyPlaneNode() {
    long cPtr = MyoushuJNI.Scene_getSkyPlaneNode(swigCPtr, this);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SceneManager__SkyPlaneGenParameters getSkyPlaneGenParameters() {
    return new SWIGTYPE_p_Ogre__SceneManager__SkyPlaneGenParameters(MyoushuJNI.Scene_getSkyPlaneGenParameters(swigCPtr, this), false);
  }

  public void setSkyBox(boolean enable, String materialName, float distance, boolean drawFirst, Quaternion orientation, String groupName) {
    MyoushuJNI.Scene_setSkyBox__SWIG_0(swigCPtr, this, enable, materialName, distance, drawFirst, Quaternion.getCPtr(orientation), orientation, groupName);
  }

  public void setSkyBox(boolean enable, String materialName, float distance, boolean drawFirst, Quaternion orientation) {
    MyoushuJNI.Scene_setSkyBox__SWIG_1(swigCPtr, this, enable, materialName, distance, drawFirst, Quaternion.getCPtr(orientation), orientation);
  }

  public void setSkyBox(boolean enable, String materialName, float distance, boolean drawFirst) {
    MyoushuJNI.Scene_setSkyBox__SWIG_2(swigCPtr, this, enable, materialName, distance, drawFirst);
  }

  public void setSkyBox(boolean enable, String materialName, float distance) {
    MyoushuJNI.Scene_setSkyBox__SWIG_3(swigCPtr, this, enable, materialName, distance);
  }

  public void setSkyBox(boolean enable, String materialName) {
    MyoushuJNI.Scene_setSkyBox__SWIG_4(swigCPtr, this, enable, materialName);
  }

  public boolean isSkyBoxEnabled() {
    return MyoushuJNI.Scene_isSkyBoxEnabled(swigCPtr, this);
  }

  public SceneNode getSkyBoxNode() {
    long cPtr = MyoushuJNI.Scene_getSkyBoxNode(swigCPtr, this);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SceneManager__SkyBoxGenParameters getSkyBoxGenParameters() {
    return new SWIGTYPE_p_Ogre__SceneManager__SkyBoxGenParameters(MyoushuJNI.Scene_getSkyBoxGenParameters(swigCPtr, this), false);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst, Quaternion orientation, int xsegments, int ysegments, int ysegments_keep, String groupName) {
    MyoushuJNI.Scene_setSkyDome__SWIG_0(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst, Quaternion.getCPtr(orientation), orientation, xsegments, ysegments, ysegments_keep, groupName);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst, Quaternion orientation, int xsegments, int ysegments, int ysegments_keep) {
    MyoushuJNI.Scene_setSkyDome__SWIG_1(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst, Quaternion.getCPtr(orientation), orientation, xsegments, ysegments, ysegments_keep);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst, Quaternion orientation, int xsegments, int ysegments) {
    MyoushuJNI.Scene_setSkyDome__SWIG_2(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst, Quaternion.getCPtr(orientation), orientation, xsegments, ysegments);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst, Quaternion orientation, int xsegments) {
    MyoushuJNI.Scene_setSkyDome__SWIG_3(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst, Quaternion.getCPtr(orientation), orientation, xsegments);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst, Quaternion orientation) {
    MyoushuJNI.Scene_setSkyDome__SWIG_4(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst, Quaternion.getCPtr(orientation), orientation);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance, boolean drawFirst) {
    MyoushuJNI.Scene_setSkyDome__SWIG_5(swigCPtr, this, enable, materialName, curvature, tiling, distance, drawFirst);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling, float distance) {
    MyoushuJNI.Scene_setSkyDome__SWIG_6(swigCPtr, this, enable, materialName, curvature, tiling, distance);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature, float tiling) {
    MyoushuJNI.Scene_setSkyDome__SWIG_7(swigCPtr, this, enable, materialName, curvature, tiling);
  }

  public void setSkyDome(boolean enable, String materialName, float curvature) {
    MyoushuJNI.Scene_setSkyDome__SWIG_8(swigCPtr, this, enable, materialName, curvature);
  }

  public void setSkyDome(boolean enable, String materialName) {
    MyoushuJNI.Scene_setSkyDome__SWIG_9(swigCPtr, this, enable, materialName);
  }

  public boolean isSkyDomeEnabled() {
    return MyoushuJNI.Scene_isSkyDomeEnabled(swigCPtr, this);
  }

  public SceneNode getSkyDomeNode() {
    long cPtr = MyoushuJNI.Scene_getSkyDomeNode(swigCPtr, this);
    return (cPtr == 0) ? null : new SceneNode(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SceneManager__SkyDomeGenParameters getSkyDomeGenParameters() {
    return new SWIGTYPE_p_Ogre__SceneManager__SkyDomeGenParameters(MyoushuJNI.Scene_getSkyDomeGenParameters(swigCPtr, this), false);
  }

  public void setFog(FogMode mode, ColourValue colour, float expDensity, float linearStart, float linearEnd) {
    MyoushuJNI.Scene_setFog__SWIG_0(swigCPtr, this, mode.swigValue(), ColourValue.getCPtr(colour), colour, expDensity, linearStart, linearEnd);
  }

  public void setFog(FogMode mode, ColourValue colour, float expDensity, float linearStart) {
    MyoushuJNI.Scene_setFog__SWIG_1(swigCPtr, this, mode.swigValue(), ColourValue.getCPtr(colour), colour, expDensity, linearStart);
  }

  public void setFog(FogMode mode, ColourValue colour, float expDensity) {
    MyoushuJNI.Scene_setFog__SWIG_2(swigCPtr, this, mode.swigValue(), ColourValue.getCPtr(colour), colour, expDensity);
  }

  public void setFog(FogMode mode, ColourValue colour) {
    MyoushuJNI.Scene_setFog__SWIG_3(swigCPtr, this, mode.swigValue(), ColourValue.getCPtr(colour), colour);
  }

  public void setFog(FogMode mode) {
    MyoushuJNI.Scene_setFog__SWIG_4(swigCPtr, this, mode.swigValue());
  }

  public void setFog() {
    MyoushuJNI.Scene_setFog__SWIG_5(swigCPtr, this);
  }

  public FogMode getFogMode() {
    return FogMode.swigToEnum(MyoushuJNI.Scene_getFogMode(swigCPtr, this));
  }

  public ColourValue getFogColour() {
    return new ColourValue(MyoushuJNI.Scene_getFogColour(swigCPtr, this), false);
  }

  public float getFogStart() {
    return MyoushuJNI.Scene_getFogStart(swigCPtr, this);
  }

  public float getFogEnd() {
    return MyoushuJNI.Scene_getFogEnd(swigCPtr, this);
  }

  public float getFogDensity() {
    return MyoushuJNI.Scene_getFogDensity(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__BillboardSet createBillboardSet(String name, long poolSize) {
    long cPtr = MyoushuJNI.Scene_createBillboardSet__SWIG_0(swigCPtr, this, name, poolSize);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__BillboardSet(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__BillboardSet createBillboardSet(String name) {
    long cPtr = MyoushuJNI.Scene_createBillboardSet__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__BillboardSet(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__BillboardSet getBillboardSet(String name) {
    long cPtr = MyoushuJNI.Scene_getBillboardSet(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__BillboardSet(cPtr, false);
  }

  public boolean hasBillboardSet(String name) {
    return MyoushuJNI.Scene_hasBillboardSet(swigCPtr, this, name);
  }

  public void destroyBillboardSet(SWIGTYPE_p_Ogre__BillboardSet set) {
    MyoushuJNI.Scene_destroyBillboardSet__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__BillboardSet.getCPtr(set));
  }

  public void destroyBillboardSet(String name) {
    MyoushuJNI.Scene_destroyBillboardSet__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllBillboardSets() {
    MyoushuJNI.Scene_destroyAllBillboardSets(swigCPtr, this);
  }

  public void setDisplaySceneNodes(boolean display) {
    MyoushuJNI.Scene_setDisplaySceneNodes(swigCPtr, this, display);
  }

  public boolean getDisplaySceneNodes() {
    return MyoushuJNI.Scene_getDisplaySceneNodes(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__Animation createAnimation(String name, float length) {
    long cPtr = MyoushuJNI.Scene_createAnimation(swigCPtr, this, name, length);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__Animation(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__Animation getAnimation(String name) {
    long cPtr = MyoushuJNI.Scene_getAnimation(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__Animation(cPtr, false);
  }

  public boolean hasAnimation(String name) {
    return MyoushuJNI.Scene_hasAnimation(swigCPtr, this, name);
  }

  public void destroyAnimation(String name) {
    MyoushuJNI.Scene_destroyAnimation(swigCPtr, this, name);
  }

  public void destroyAllAnimations() {
    MyoushuJNI.Scene_destroyAllAnimations(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__AnimationState createAnimationState(String animName) {
    long cPtr = MyoushuJNI.Scene_createAnimationState(swigCPtr, this, animName);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__AnimationState(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__AnimationState getAnimationState(String animName) {
    long cPtr = MyoushuJNI.Scene_getAnimationState(swigCPtr, this, animName);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__AnimationState(cPtr, false);
  }

  public boolean hasAnimationState(String name) {
    return MyoushuJNI.Scene_hasAnimationState(swigCPtr, this, name);
  }

  public void destroyAnimationState(String name) {
    MyoushuJNI.Scene_destroyAnimationState(swigCPtr, this, name);
  }

  public void destroyAllAnimationStates() {
    MyoushuJNI.Scene_destroyAllAnimationStates(swigCPtr, this);
  }

  public void manualRender(SWIGTYPE_p_Ogre__RenderOperation rend, SWIGTYPE_p_Ogre__Pass pass, Viewport vp, Matrix4 worldMatrix, Matrix4 viewMatrix, Matrix4 projMatrix, boolean doBeginEndFrame) {
    MyoushuJNI.Scene_manualRender__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__RenderOperation.getCPtr(rend), SWIGTYPE_p_Ogre__Pass.getCPtr(pass), Viewport.getCPtr(vp), vp, Matrix4.getCPtr(worldMatrix), worldMatrix, Matrix4.getCPtr(viewMatrix), viewMatrix, Matrix4.getCPtr(projMatrix), projMatrix, doBeginEndFrame);
  }

  public void manualRender(SWIGTYPE_p_Ogre__RenderOperation rend, SWIGTYPE_p_Ogre__Pass pass, Viewport vp, Matrix4 worldMatrix, Matrix4 viewMatrix, Matrix4 projMatrix) {
    MyoushuJNI.Scene_manualRender__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__RenderOperation.getCPtr(rend), SWIGTYPE_p_Ogre__Pass.getCPtr(pass), Viewport.getCPtr(vp), vp, Matrix4.getCPtr(worldMatrix), worldMatrix, Matrix4.getCPtr(viewMatrix), viewMatrix, Matrix4.getCPtr(projMatrix), projMatrix);
  }

  public SWIGTYPE_p_Ogre__RenderQueue getRenderQueue() {
    long cPtr = MyoushuJNI.Scene_getRenderQueue(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RenderQueue(cPtr, false);
  }

  public void addRenderQueueListener(SWIGTYPE_p_Ogre__RenderQueueListener newListener) {
    MyoushuJNI.Scene_addRenderQueueListener(swigCPtr, this, SWIGTYPE_p_Ogre__RenderQueueListener.getCPtr(newListener));
  }

  public void removeRenderQueueListener(SWIGTYPE_p_Ogre__RenderQueueListener delListener) {
    MyoushuJNI.Scene_removeRenderQueueListener(swigCPtr, this, SWIGTYPE_p_Ogre__RenderQueueListener.getCPtr(delListener));
  }

  public void addSpecialCaseRenderQueue(short qid) {
    MyoushuJNI.Scene_addSpecialCaseRenderQueue(swigCPtr, this, qid);
  }

  public void removeSpecialCaseRenderQueue(short qid) {
    MyoushuJNI.Scene_removeSpecialCaseRenderQueue(swigCPtr, this, qid);
  }

  public void clearSpecialCaseRenderQueues() {
    MyoushuJNI.Scene_clearSpecialCaseRenderQueues(swigCPtr, this);
  }

  public void setSpecialCaseRenderQueueMode(SWIGTYPE_p_Ogre__SceneManager__SpecialCaseRenderQueueMode mode) {
    MyoushuJNI.Scene_setSpecialCaseRenderQueueMode(swigCPtr, this, SWIGTYPE_p_Ogre__SceneManager__SpecialCaseRenderQueueMode.getCPtr(mode));
  }

  public SWIGTYPE_p_Ogre__SceneManager__SpecialCaseRenderQueueMode getSpecialCaseRenderQueueMode() {
    return new SWIGTYPE_p_Ogre__SceneManager__SpecialCaseRenderQueueMode(MyoushuJNI.Scene_getSpecialCaseRenderQueueMode(swigCPtr, this), true);
  }

  public boolean isRenderQueueToBeProcessed(short qid) {
    return MyoushuJNI.Scene_isRenderQueueToBeProcessed(swigCPtr, this, qid);
  }

  public void setWorldGeometryRenderQueue(short qid) {
    MyoushuJNI.Scene_setWorldGeometryRenderQueue(swigCPtr, this, qid);
  }

  public short getWorldGeometryRenderQueue() {
    return MyoushuJNI.Scene_getWorldGeometryRenderQueue(swigCPtr, this);
  }

  public void showBoundingBoxes(boolean bShow) {
    MyoushuJNI.Scene_showBoundingBoxes(swigCPtr, this, bShow);
  }

  public boolean getShowBoundingBoxes() {
    return MyoushuJNI.Scene_getShowBoundingBoxes(swigCPtr, this);
  }

  public void _notifyAutotrackingSceneNode(SceneNode node, boolean autoTrack) {
    MyoushuJNI.Scene__notifyAutotrackingSceneNode(swigCPtr, this, SceneNode.getCPtr(node), node, autoTrack);
  }

  public SWIGTYPE_p_Ogre__AxisAlignedBoxSceneQuery createAABBQuery(SWIGTYPE_p_Ogre__AxisAlignedBox box, long mask) {
    long cPtr = MyoushuJNI.Scene_createAABBQuery__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__AxisAlignedBox.getCPtr(box), mask);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__AxisAlignedBoxSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__AxisAlignedBoxSceneQuery createAABBQuery(SWIGTYPE_p_Ogre__AxisAlignedBox box) {
    long cPtr = MyoushuJNI.Scene_createAABBQuery__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__AxisAlignedBox.getCPtr(box));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__AxisAlignedBoxSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SphereSceneQuery createSphereQuery(SWIGTYPE_p_Ogre__Sphere sphere, long mask) {
    long cPtr = MyoushuJNI.Scene_createSphereQuery__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__Sphere.getCPtr(sphere), mask);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__SphereSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__SphereSceneQuery createSphereQuery(SWIGTYPE_p_Ogre__Sphere sphere) {
    long cPtr = MyoushuJNI.Scene_createSphereQuery__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__Sphere.getCPtr(sphere));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__SphereSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__PlaneBoundedVolumeListSceneQuery createPlaneBoundedVolumeQuery(SWIGTYPE_p_Ogre__PlaneBoundedVolumeList volumes, long mask) {
    long cPtr = MyoushuJNI.Scene_createPlaneBoundedVolumeQuery__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__PlaneBoundedVolumeList.getCPtr(volumes), mask);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__PlaneBoundedVolumeListSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__PlaneBoundedVolumeListSceneQuery createPlaneBoundedVolumeQuery(SWIGTYPE_p_Ogre__PlaneBoundedVolumeList volumes) {
    long cPtr = MyoushuJNI.Scene_createPlaneBoundedVolumeQuery__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__PlaneBoundedVolumeList.getCPtr(volumes));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__PlaneBoundedVolumeListSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__RaySceneQuery createRayQuery(SWIGTYPE_p_Ogre__Ray ray, long mask) {
    long cPtr = MyoushuJNI.Scene_createRayQuery__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__Ray.getCPtr(ray), mask);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RaySceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__RaySceneQuery createRayQuery(SWIGTYPE_p_Ogre__Ray ray) {
    long cPtr = MyoushuJNI.Scene_createRayQuery__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__Ray.getCPtr(ray));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RaySceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__IntersectionSceneQuery createIntersectionQuery(long mask) {
    long cPtr = MyoushuJNI.Scene_createIntersectionQuery__SWIG_0(swigCPtr, this, mask);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__IntersectionSceneQuery(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__IntersectionSceneQuery createIntersectionQuery() {
    long cPtr = MyoushuJNI.Scene_createIntersectionQuery__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__IntersectionSceneQuery(cPtr, false);
  }

  public void destroyQuery(SWIGTYPE_p_Ogre__SceneQuery query) {
    MyoushuJNI.Scene_destroyQuery(swigCPtr, this, SWIGTYPE_p_Ogre__SceneQuery.getCPtr(query));
  }

  public void setShadowTechnique(ShadowTechnique technique) {
    MyoushuJNI.Scene_setShadowTechnique(swigCPtr, this, technique.swigValue());
  }

  public ShadowTechnique getShadowTechnique() {
    return ShadowTechnique.swigToEnum(MyoushuJNI.Scene_getShadowTechnique(swigCPtr, this));
  }

  public void setShowDebugShadows(boolean debug) {
    MyoushuJNI.Scene_setShowDebugShadows(swigCPtr, this, debug);
  }

  public boolean getShowDebugShadows() {
    return MyoushuJNI.Scene_getShowDebugShadows(swigCPtr, this);
  }

  public void setShadowColour(ColourValue colour) {
    MyoushuJNI.Scene_setShadowColour(swigCPtr, this, ColourValue.getCPtr(colour), colour);
  }

  public ColourValue getShadowColour() {
    return new ColourValue(MyoushuJNI.Scene_getShadowColour(swigCPtr, this), false);
  }

  public void setShadowDirectionalLightExtrusionDistance(float dist) {
    MyoushuJNI.Scene_setShadowDirectionalLightExtrusionDistance(swigCPtr, this, dist);
  }

  public float getShadowDirectionalLightExtrusionDistance() {
    return MyoushuJNI.Scene_getShadowDirectionalLightExtrusionDistance(swigCPtr, this);
  }

  public void setShadowFarDistance(float distance) {
    MyoushuJNI.Scene_setShadowFarDistance(swigCPtr, this, distance);
  }

  public float getShadowFarDistance() {
    return MyoushuJNI.Scene_getShadowFarDistance(swigCPtr, this);
  }

  public void setShadowIndexBufferSize(long size) {
    MyoushuJNI.Scene_setShadowIndexBufferSize(swigCPtr, this, size);
  }

  public long getShadowIndexBufferSize() {
    return MyoushuJNI.Scene_getShadowIndexBufferSize(swigCPtr, this);
  }

  public void setShadowTextureSize(int size) {
    MyoushuJNI.Scene_setShadowTextureSize(swigCPtr, this, size);
  }

  public void setShadowTextureConfig(long shadowIndex, int width, int height, SWIGTYPE_p_Ogre__PixelFormat format) {
    MyoushuJNI.Scene_setShadowTextureConfig__SWIG_0(swigCPtr, this, shadowIndex, width, height, SWIGTYPE_p_Ogre__PixelFormat.getCPtr(format));
  }

  public void setShadowTextureConfig(long shadowIndex, SWIGTYPE_p_Ogre__ShadowTextureConfig config) {
    MyoushuJNI.Scene_setShadowTextureConfig__SWIG_1(swigCPtr, this, shadowIndex, SWIGTYPE_p_Ogre__ShadowTextureConfig.getCPtr(config));
  }

  public void setShadowTexturePixelFormat(SWIGTYPE_p_Ogre__PixelFormat fmt) {
    MyoushuJNI.Scene_setShadowTexturePixelFormat(swigCPtr, this, SWIGTYPE_p_Ogre__PixelFormat.getCPtr(fmt));
  }

  public void setShadowTextureCount(long count) {
    MyoushuJNI.Scene_setShadowTextureCount(swigCPtr, this, count);
  }

  public long getShadowTextureCount() {
    return MyoushuJNI.Scene_getShadowTextureCount(swigCPtr, this);
  }

  public void setShadowTextureSettings(int size, int count, SWIGTYPE_p_Ogre__PixelFormat fmt) {
    MyoushuJNI.Scene_setShadowTextureSettings__SWIG_0(swigCPtr, this, size, count, SWIGTYPE_p_Ogre__PixelFormat.getCPtr(fmt));
  }

  public void setShadowTextureSettings(int size, int count) {
    MyoushuJNI.Scene_setShadowTextureSettings__SWIG_1(swigCPtr, this, size, count);
  }

  public SWIGTYPE_p_Ogre__TexturePtr getShadowTexture(long shadowIndex) {
    return new SWIGTYPE_p_Ogre__TexturePtr(MyoushuJNI.Scene_getShadowTexture(swigCPtr, this, shadowIndex), false);
  }

  public void setShadowDirLightTextureOffset(float offset) {
    MyoushuJNI.Scene_setShadowDirLightTextureOffset(swigCPtr, this, offset);
  }

  public float getShadowDirLightTextureOffset() {
    return MyoushuJNI.Scene_getShadowDirLightTextureOffset(swigCPtr, this);
  }

  public void setShadowTextureFadeStart(float fadeStart) {
    MyoushuJNI.Scene_setShadowTextureFadeStart(swigCPtr, this, fadeStart);
  }

  public void setShadowTextureFadeEnd(float fadeEnd) {
    MyoushuJNI.Scene_setShadowTextureFadeEnd(swigCPtr, this, fadeEnd);
  }

  public void setShadowTextureSelfShadow(boolean selfShadow) {
    MyoushuJNI.Scene_setShadowTextureSelfShadow(swigCPtr, this, selfShadow);
  }

  public boolean getShadowTextureSelfShadow() {
    return MyoushuJNI.Scene_getShadowTextureSelfShadow(swigCPtr, this);
  }

  public void setShadowTextureCasterMaterial(String name) {
    MyoushuJNI.Scene_setShadowTextureCasterMaterial(swigCPtr, this, name);
  }

  public void setShadowTextureReceiverMaterial(String name) {
    MyoushuJNI.Scene_setShadowTextureReceiverMaterial(swigCPtr, this, name);
  }

  public void setShadowCasterRenderBackFaces(boolean bf) {
    MyoushuJNI.Scene_setShadowCasterRenderBackFaces(swigCPtr, this, bf);
  }

  public boolean getShadowCasterRenderBackFaces() {
    return MyoushuJNI.Scene_getShadowCasterRenderBackFaces(swigCPtr, this);
  }

  public void setShadowCameraSetup(SWIGTYPE_p_Ogre__ShadowCameraSetupPtr shadowSetup) {
    MyoushuJNI.Scene_setShadowCameraSetup(swigCPtr, this, SWIGTYPE_p_Ogre__ShadowCameraSetupPtr.getCPtr(shadowSetup));
  }

  public SWIGTYPE_p_Ogre__ShadowCameraSetupPtr getShadowCameraSetup() {
    return new SWIGTYPE_p_Ogre__ShadowCameraSetupPtr(MyoushuJNI.Scene_getShadowCameraSetup(swigCPtr, this), false);
  }

  public void setShadowUseInfiniteFarPlane(boolean enable) {
    MyoushuJNI.Scene_setShadowUseInfiniteFarPlane(swigCPtr, this, enable);
  }

  public boolean isShadowTechniqueStencilBased() {
    return MyoushuJNI.Scene_isShadowTechniqueStencilBased(swigCPtr, this);
  }

  public boolean isShadowTechniqueTextureBased() {
    return MyoushuJNI.Scene_isShadowTechniqueTextureBased(swigCPtr, this);
  }

  public boolean isShadowTechniqueModulative() {
    return MyoushuJNI.Scene_isShadowTechniqueModulative(swigCPtr, this);
  }

  public boolean isShadowTechniqueAdditive() {
    return MyoushuJNI.Scene_isShadowTechniqueAdditive(swigCPtr, this);
  }

  public boolean isShadowTechniqueIntegrated() {
    return MyoushuJNI.Scene_isShadowTechniqueIntegrated(swigCPtr, this);
  }

  public boolean isShadowTechniqueInUse() {
    return MyoushuJNI.Scene_isShadowTechniqueInUse(swigCPtr, this);
  }

  public void addListener(SWIGTYPE_p_Ogre__SceneManager__Listener l) {
    MyoushuJNI.Scene_addListener(swigCPtr, this, SWIGTYPE_p_Ogre__SceneManager__Listener.getCPtr(l));
  }

  public void removeListener(SWIGTYPE_p_Ogre__SceneManager__Listener l) {
    MyoushuJNI.Scene_removeListener(swigCPtr, this, SWIGTYPE_p_Ogre__SceneManager__Listener.getCPtr(l));
  }

  public SWIGTYPE_p_Ogre__StaticGeometry createStaticGeometry(String name) {
    long cPtr = MyoushuJNI.Scene_createStaticGeometry(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__StaticGeometry(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__StaticGeometry getStaticGeometry(String name) {
    long cPtr = MyoushuJNI.Scene_getStaticGeometry__SWIG_0(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__StaticGeometry(cPtr, false);
  }

  public boolean hasStaticGeometry(String name) {
    return MyoushuJNI.Scene_hasStaticGeometry(swigCPtr, this, name);
  }

  public void destroyStaticGeometry(SWIGTYPE_p_Ogre__StaticGeometry geom) {
    MyoushuJNI.Scene_destroyStaticGeometry__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__StaticGeometry.getCPtr(geom));
  }

  public void destroyStaticGeometry(String name) {
    MyoushuJNI.Scene_destroyStaticGeometry__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllStaticGeometry() {
    MyoushuJNI.Scene_destroyAllStaticGeometry(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__InstancedGeometry createInstancedGeometry(String name) {
    long cPtr = MyoushuJNI.Scene_createInstancedGeometry(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__InstancedGeometry(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__InstancedGeometry getInstancedGeometry(String name) {
    long cPtr = MyoushuJNI.Scene_getInstancedGeometry(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__InstancedGeometry(cPtr, false);
  }

  public void destroyInstancedGeometry(SWIGTYPE_p_Ogre__InstancedGeometry geom) {
    MyoushuJNI.Scene_destroyInstancedGeometry__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__InstancedGeometry.getCPtr(geom));
  }

  public void destroyInstancedGeometry(String name) {
    MyoushuJNI.Scene_destroyInstancedGeometry__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllInstancedGeometry() {
    MyoushuJNI.Scene_destroyAllInstancedGeometry(swigCPtr, this);
  }

  public MovableObject createMovableObject(String name, String typeName, SWIGTYPE_p_std__mapT_std__string_std__string_t params) {
    long cPtr = MyoushuJNI.Scene_createMovableObject__SWIG_0(swigCPtr, this, name, typeName, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(params));
    return (cPtr == 0) ? null : new MovableObject(cPtr, false);
  }

  public MovableObject createMovableObject(String name, String typeName) {
    long cPtr = MyoushuJNI.Scene_createMovableObject__SWIG_1(swigCPtr, this, name, typeName);
    return (cPtr == 0) ? null : new MovableObject(cPtr, false);
  }

  public void destroyMovableObject(String name, String typeName) {
    MyoushuJNI.Scene_destroyMovableObject__SWIG_0(swigCPtr, this, name, typeName);
  }

  public void destroyMovableObject(MovableObject m) {
    MyoushuJNI.Scene_destroyMovableObject__SWIG_1(swigCPtr, this, MovableObject.getCPtr(m), m);
  }

  public void destroyAllMovableObjectsByType(String typeName) {
    MyoushuJNI.Scene_destroyAllMovableObjectsByType(swigCPtr, this, typeName);
  }

  public void destroyAllMovableObjects() {
    MyoushuJNI.Scene_destroyAllMovableObjects(swigCPtr, this);
  }

  public MovableObject getMovableObject(String name, String typeName) {
    long cPtr = MyoushuJNI.Scene_getMovableObject(swigCPtr, this, name, typeName);
    return (cPtr == 0) ? null : new MovableObject(cPtr, false);
  }

  public boolean hasMovableObject(String name, String typeName) {
    return MyoushuJNI.Scene_hasMovableObject(swigCPtr, this, name, typeName);
  }

  public void injectMovableObject(MovableObject m) {
    MyoushuJNI.Scene_injectMovableObject(swigCPtr, this, MovableObject.getCPtr(m), m);
  }

  public void extractMovableObject(String name, String typeName) {
    MyoushuJNI.Scene_extractMovableObject__SWIG_0(swigCPtr, this, name, typeName);
  }

  public void extractMovableObject(MovableObject m) {
    MyoushuJNI.Scene_extractMovableObject__SWIG_1(swigCPtr, this, MovableObject.getCPtr(m), m);
  }

  public void extractAllMovableObjectsByType(String typeName) {
    MyoushuJNI.Scene_extractAllMovableObjectsByType(swigCPtr, this, typeName);
  }

  public void setVisibilityMask(long vmask) {
    MyoushuJNI.Scene_setVisibilityMask(swigCPtr, this, vmask);
  }

  public long getVisibilityMask() {
    return MyoushuJNI.Scene_getVisibilityMask(swigCPtr, this);
  }

  public long _getCombinedVisibilityMask() {
    return MyoushuJNI.Scene__getCombinedVisibilityMask(swigCPtr, this);
  }

  public void setFindVisibleObjects(boolean find) {
    MyoushuJNI.Scene_setFindVisibleObjects(swigCPtr, this, find);
  }

  public boolean getFindVisibleObjects() {
    return MyoushuJNI.Scene_getFindVisibleObjects(swigCPtr, this);
  }

  public void _injectRenderWithPass(SWIGTYPE_p_Ogre__Pass pass, SWIGTYPE_p_Ogre__Renderable rend, boolean shadowDerivation) {
    MyoushuJNI.Scene__injectRenderWithPass__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__Pass.getCPtr(pass), SWIGTYPE_p_Ogre__Renderable.getCPtr(rend), shadowDerivation);
  }

  public void _injectRenderWithPass(SWIGTYPE_p_Ogre__Pass pass, SWIGTYPE_p_Ogre__Renderable rend) {
    MyoushuJNI.Scene__injectRenderWithPass__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__Pass.getCPtr(pass), SWIGTYPE_p_Ogre__Renderable.getCPtr(rend));
  }

  public void _suppressRenderStateChanges(boolean suppress) {
    MyoushuJNI.Scene__suppressRenderStateChanges(swigCPtr, this, suppress);
  }

  public boolean _areRenderStateChangesSuppressed() {
    return MyoushuJNI.Scene__areRenderStateChangesSuppressed(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__Pass _setPass(SWIGTYPE_p_Ogre__Pass pass, boolean evenIfSuppressed, boolean shadowDerivation) {
    long cPtr = MyoushuJNI.Scene__setPass__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__Pass.getCPtr(pass), evenIfSuppressed, shadowDerivation);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__Pass(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__Pass _setPass(SWIGTYPE_p_Ogre__Pass pass, boolean evenIfSuppressed) {
    long cPtr = MyoushuJNI.Scene__setPass__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__Pass.getCPtr(pass), evenIfSuppressed);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__Pass(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__Pass _setPass(SWIGTYPE_p_Ogre__Pass pass) {
    long cPtr = MyoushuJNI.Scene__setPass__SWIG_2(swigCPtr, this, SWIGTYPE_p_Ogre__Pass.getCPtr(pass));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__Pass(cPtr, false);
  }

  public void _suppressShadows(boolean suppress) {
    MyoushuJNI.Scene__suppressShadows(swigCPtr, this, suppress);
  }

  public boolean _areShadowsSuppressed() {
    return MyoushuJNI.Scene__areShadowsSuppressed(swigCPtr, this);
  }

  public void _renderQueueGroupObjects(SWIGTYPE_p_Ogre__RenderQueueGroup group, SWIGTYPE_p_Ogre__QueuedRenderableCollection__OrganisationMode om) {
    MyoushuJNI.Scene__renderQueueGroupObjects(swigCPtr, this, SWIGTYPE_p_Ogre__RenderQueueGroup.getCPtr(group), SWIGTYPE_p_Ogre__QueuedRenderableCollection__OrganisationMode.getCPtr(om));
  }

  public SWIGTYPE_p_Ogre__RenderSystem getDestinationRenderSystem() {
    long cPtr = MyoushuJNI.Scene_getDestinationRenderSystem(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__RenderSystem(cPtr, false);
  }

  public Viewport getCurrentViewport() {
    long cPtr = MyoushuJNI.Scene_getCurrentViewport(swigCPtr, this);
    return (cPtr == 0) ? null : new Viewport(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo getVisibleObjectsBoundsInfo(Camera cam) {
    return new SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo(MyoushuJNI.Scene_getVisibleObjectsBoundsInfo(swigCPtr, this, Camera.getCPtr(cam), cam), false);
  }

  public SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo getShadowCasterBoundsInfo(Light light) {
    return new SWIGTYPE_p_Ogre__VisibleObjectsBoundsInfo(MyoushuJNI.Scene_getShadowCasterBoundsInfo(swigCPtr, this, Light.getCPtr(light), light), false);
  }

  public SWIGTYPE_p_NxScene getNxScene() {
    long cPtr = MyoushuJNI.Scene_getNxScene(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxScene(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__World getWorld() {
    long cPtr = MyoushuJNI.Scene_getWorld(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__World(cPtr, false);
  }

  public void setSceneController(SWIGTYPE_p_NxOgre__SceneController arg0) {
    MyoushuJNI.Scene_setSceneController(swigCPtr, this, SWIGTYPE_p_NxOgre__SceneController.getCPtr(arg0));
  }

  public void simulate(float arg0) {
    MyoushuJNI.Scene_simulate(swigCPtr, this, arg0);
  }

  public void render(float arg0) {
    MyoushuJNI.Scene_render(swigCPtr, this, arg0);
  }

  public void setGravity(Vector3 arg0) {
    MyoushuJNI.Scene_setGravity(swigCPtr, this, Vector3.getCPtr(arg0), arg0);
  }

  public Vector3 getGravity() {
    return new Vector3(MyoushuJNI.Scene_getGravity(swigCPtr, this), true);
  }

  public NxOgre_Actor createActor(String identifier, ShapeBlueprint arg1, Pose arg2, ActorParams arg3) {
    long cPtr = MyoushuJNI.Scene_createActor__SWIG_0(swigCPtr, this, identifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2, ActorParams.getCPtr(arg3), arg3);
    return (cPtr == 0) ? null : new NxOgre_Actor(cPtr, false);
  }

  public NxOgre_Actor createActor(String identifier, ShapeBlueprint arg1, Pose arg2) {
    long cPtr = MyoushuJNI.Scene_createActor__SWIG_1(swigCPtr, this, identifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2);
    return (cPtr == 0) ? null : new NxOgre_Actor(cPtr, false);
  }

  public void batchCreateActors(String identifierPattern, long nbActors, ShapeBlueprint arg2, Pose poseOrigin, Pose poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg5, ActorParams arg6) {
    MyoushuJNI.Scene_batchCreateActors__SWIG_0(swigCPtr, this, identifierPattern, nbActors, ShapeBlueprint.getCPtr(arg2), arg2, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg5), ActorParams.getCPtr(arg6), arg6);
  }

  public void batchCreateActors(String identifierPattern, long nbActors, ShapeBlueprint arg2, Pose poseOrigin, Pose poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg5) {
    MyoushuJNI.Scene_batchCreateActors__SWIG_1(swigCPtr, this, identifierPattern, nbActors, ShapeBlueprint.getCPtr(arg2), arg2, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg5));
  }

  public void batchCreateActors(String identifierPattern, long nbActors, ShapeBlueprint arg2, Pose poseOrigin, Pose poseDifference) {
    MyoushuJNI.Scene_batchCreateActors__SWIG_2(swigCPtr, this, identifierPattern, nbActors, ShapeBlueprint.getCPtr(arg2), arg2, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference);
  }

  public void destroyActor(String arg0) {
    MyoushuJNI.Scene_destroyActor(swigCPtr, this, arg0);
  }

  public void batchDestroyActor(String identifier, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg1) {
    MyoushuJNI.Scene_batchDestroyActor__SWIG_0(swigCPtr, this, identifier, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg1));
  }

  public void batchDestroyActor(String identifier) {
    MyoushuJNI.Scene_batchDestroyActor__SWIG_1(swigCPtr, this, identifier);
  }

  public void batchDestroyActors(SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t arg0, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg1) {
    MyoushuJNI.Scene_batchDestroyActors__SWIG_0(swigCPtr, this, SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t.getCPtr(arg0), SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg1));
  }

  public void batchDestroyActors(SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t arg0) {
    MyoushuJNI.Scene_batchDestroyActors__SWIG_1(swigCPtr, this, SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t.getCPtr(arg0));
  }

  public NxOgre_Actor getActor(String arg0) {
    long cPtr = MyoushuJNI.Scene_getActor(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new NxOgre_Actor(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActors() {
    long cPtr = MyoushuJNI.Scene_getActors(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActorsFromIdentifier(NxStringOperator arg0, String identifierPattern) {
    return new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(MyoushuJNI.Scene_getActorsFromIdentifier(swigCPtr, this, arg0.swigValue(), identifierPattern), true);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActorsFromFrame(NxComparisonOperator arg0, long frame) {
    return new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(MyoushuJNI.Scene_getActorsFromFrame(swigCPtr, this, arg0.swigValue(), frame), true);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActorsFromRegion(SWIGTYPE_p_NxOgre__SimpleShape arg0, SWIGTYPE_p_NxShapesType arg1) {
    return new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(MyoushuJNI.Scene_getActorsFromRegion(swigCPtr, this, SWIGTYPE_p_NxOgre__SimpleShape.getCPtr(arg0), SWIGTYPE_p_NxShapesType.getCPtr(arg1)), false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActorsFromLastRegion(SWIGTYPE_p_NxShapesType arg0) {
    return new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(MyoushuJNI.Scene_getActorsFromLastRegion(swigCPtr, this, SWIGTYPE_p_NxShapesType.getCPtr(arg0)), false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t getActorsFromRaycast(Vector3 position, Vector3 normal, float range) {
    return new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Actor_p_t(MyoushuJNI.Scene_getActorsFromRaycast(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(normal), normal, range), true);
  }

  public long getNbActors() {
    return MyoushuJNI.Scene_getNbActors(swigCPtr, this);
  }

  public NxOgre_Body createBody(String meshIdentifier, ShapeBlueprint arg1, Pose arg2, ActorParams arg3) {
    long cPtr = MyoushuJNI.Scene_createBody__SWIG_0(swigCPtr, this, meshIdentifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2, ActorParams.getCPtr(arg3), arg3);
    return (cPtr == 0) ? null : new NxOgre_Body(cPtr, false);
  }

  public NxOgre_Body createBody(String meshIdentifier, ShapeBlueprint arg1, Pose arg2) {
    long cPtr = MyoushuJNI.Scene_createBody__SWIG_1(swigCPtr, this, meshIdentifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2);
    return (cPtr == 0) ? null : new NxOgre_Body(cPtr, false);
  }

  public void batchCreateBodies(String identifierPattern, String visualData, long nbActors, ShapeBlueprint arg3, Pose poseOrigin, Pose poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg6, ActorParams arg7) {
    MyoushuJNI.Scene_batchCreateBodies__SWIG_0(swigCPtr, this, identifierPattern, visualData, nbActors, ShapeBlueprint.getCPtr(arg3), arg3, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg6), ActorParams.getCPtr(arg7), arg7);
  }

  public void batchCreateBodies(String identifierPattern, String visualData, long nbActors, ShapeBlueprint arg3, Pose poseOrigin, Pose poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame arg6) {
    MyoushuJNI.Scene_batchCreateBodies__SWIG_1(swigCPtr, this, identifierPattern, visualData, nbActors, ShapeBlueprint.getCPtr(arg3), arg3, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference, SWIGTYPE_p_NxOgre__Scene__BatchActionTimeFrame.getCPtr(arg6));
  }

  public void batchCreateBodies(String identifierPattern, String visualData, long nbActors, ShapeBlueprint arg3, Pose poseOrigin, Pose poseDifference) {
    MyoushuJNI.Scene_batchCreateBodies__SWIG_2(swigCPtr, this, identifierPattern, visualData, nbActors, ShapeBlueprint.getCPtr(arg3), arg3, Pose.getCPtr(poseOrigin), poseOrigin, Pose.getCPtr(poseDifference), poseDifference);
  }

  public void destroyBody(String arg0) {
    MyoushuJNI.Scene_destroyBody(swigCPtr, this, arg0);
  }

  public SWIGTYPE_p_NxOgre__Trigger createTrigger(String identifier, ShapeBlueprint arg1, Pose arg2, ActorParams arg3) {
    long cPtr = MyoushuJNI.Scene_createTrigger__SWIG_0(swigCPtr, this, identifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2, ActorParams.getCPtr(arg3), arg3);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Trigger(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__Trigger createTrigger(String identifier, ShapeBlueprint arg1, Pose arg2) {
    long cPtr = MyoushuJNI.Scene_createTrigger__SWIG_1(swigCPtr, this, identifier, ShapeBlueprint.getCPtr(arg1), arg1, Pose.getCPtr(arg2), arg2);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Trigger(cPtr, false);
  }

  public void destroyTrigger(String arg0) {
    MyoushuJNI.Scene_destroyTrigger(swigCPtr, this, arg0);
  }

  public SWIGTYPE_p_NxOgre__Trigger getTrigger(String arg0) {
    long cPtr = MyoushuJNI.Scene_getTrigger(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Trigger(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Trigger_p_t getTriggers() {
    long cPtr = MyoushuJNI.Scene_getTriggers(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Trigger_p_t(cPtr, false);
  }

  public long getNbTriggers() {
    return MyoushuJNI.Scene_getNbTriggers(swigCPtr, this);
  }

  public SWIGTYPE_p_NxOgre__SphericalJoint createSphericalJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg3) {
    long cPtr = MyoushuJNI.Scene_createSphericalJoint__SWIG_0(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg3));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__SphericalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__SphericalJoint createSphericalJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createSphericalJoint__SWIG_1(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__SphericalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__SphericalJoint createSphericalJoint(NxOgre_Actor arg0, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg2) {
    long cPtr = MyoushuJNI.Scene_createSphericalJoint__SWIG_2(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg2));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__SphericalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__SphericalJoint createSphericalJoint(NxOgre_Actor arg0, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createSphericalJoint__SWIG_3(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__SphericalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__RevoluteJoint createRevoluteJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg4) {
    long cPtr = MyoushuJNI.Scene_createRevoluteJoint__SWIG_0(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg4));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__RevoluteJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__RevoluteJoint createRevoluteJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createRevoluteJoint__SWIG_1(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__RevoluteJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__RevoluteJoint createRevoluteJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg3) {
    long cPtr = MyoushuJNI.Scene_createRevoluteJoint__SWIG_2(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg3));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__RevoluteJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__RevoluteJoint createRevoluteJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createRevoluteJoint__SWIG_3(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__RevoluteJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__PrismaticJoint createPrismaticJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg4) {
    long cPtr = MyoushuJNI.Scene_createPrismaticJoint__SWIG_0(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg4));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__PrismaticJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__PrismaticJoint createPrismaticJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createPrismaticJoint__SWIG_1(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__PrismaticJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__PrismaticJoint createPrismaticJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg3) {
    long cPtr = MyoushuJNI.Scene_createPrismaticJoint__SWIG_2(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg3));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__PrismaticJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__PrismaticJoint createPrismaticJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createPrismaticJoint__SWIG_3(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__PrismaticJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__CylindricalJoint createCylindricalJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg4) {
    long cPtr = MyoushuJNI.Scene_createCylindricalJoint__SWIG_0(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg4));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__CylindricalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__CylindricalJoint createCylindricalJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createCylindricalJoint__SWIG_1(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__CylindricalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__CylindricalJoint createCylindricalJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor, SWIGTYPE_p_NxOgre__JointParams arg3) {
    long cPtr = MyoushuJNI.Scene_createCylindricalJoint__SWIG_2(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg3));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__CylindricalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__CylindricalJoint createCylindricalJoint(NxOgre_Actor arg0, Vector3 axis, Vector3 anchor) {
    long cPtr = MyoushuJNI.Scene_createCylindricalJoint__SWIG_3(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, Vector3.getCPtr(axis), axis, Vector3.getCPtr(anchor), anchor);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__CylindricalJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__FixedJoint createFixedJoint(NxOgre_Actor arg0, NxOgre_Actor arg1, SWIGTYPE_p_NxOgre__JointParams arg2) {
    long cPtr = MyoushuJNI.Scene_createFixedJoint__SWIG_0(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg2));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__FixedJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__FixedJoint createFixedJoint(NxOgre_Actor arg0, NxOgre_Actor arg1) {
    long cPtr = MyoushuJNI.Scene_createFixedJoint__SWIG_1(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, NxOgre_Actor.getCPtr(arg1), arg1);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__FixedJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__FixedJoint createFixedJoint(NxOgre_Actor arg0, SWIGTYPE_p_NxOgre__JointParams arg1) {
    long cPtr = MyoushuJNI.Scene_createFixedJoint__SWIG_2(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0, SWIGTYPE_p_NxOgre__JointParams.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__FixedJoint(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__FixedJoint createFixedJoint(NxOgre_Actor arg0) {
    long cPtr = MyoushuJNI.Scene_createFixedJoint__SWIG_3(swigCPtr, this, NxOgre_Actor.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__FixedJoint(cPtr, false);
  }

  public void releaseJoint(SWIGTYPE_p_NxOgre__Joint arg0) {
    MyoushuJNI.Scene_releaseJoint__SWIG_0(swigCPtr, this, SWIGTYPE_p_NxOgre__Joint.getCPtr(arg0));
  }

  public void releaseJoint(long arg0) {
    MyoushuJNI.Scene_releaseJoint__SWIG_1(swigCPtr, this, arg0);
  }

  public NxOgre_Character createCharacter(String name, Pose p, CharacterParams cp) {
    long cPtr = MyoushuJNI.Scene_createCharacter(swigCPtr, this, name, Pose.getCPtr(p), p, CharacterParams.getCPtr(cp), cp);
    return (cPtr == 0) ? null : new NxOgre_Character(cPtr, false);
  }

  public void destroyCharacter(String arg0) {
    MyoushuJNI.Scene_destroyCharacter(swigCPtr, this, arg0);
  }

  public SWIGTYPE_p_NxOgre__Material createMaterial(String name) {
    long cPtr = MyoushuJNI.Scene_createMaterial(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Material(cPtr, false);
  }

  public void destroyMaterial(String name) {
    MyoushuJNI.Scene_destroyMaterial(swigCPtr, this, name);
  }

  public SWIGTYPE_p_NxOgre__Material getMaterial(String arg0) {
    long cPtr = MyoushuJNI.Scene_getMaterial__SWIG_0(swigCPtr, this, arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Material(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__Material getMaterial(SWIGTYPE_p_NxMaterialIndex arg0) {
    long cPtr = MyoushuJNI.Scene_getMaterial__SWIG_1(swigCPtr, this, SWIGTYPE_p_NxMaterialIndex.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__Material(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Material_p_t getMaterials() {
    long cPtr = MyoushuJNI.Scene_getMaterials(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__Material_p_t(cPtr, false);
  }

  public long getNbMaterials() {
    return MyoushuJNI.Scene_getNbMaterials(swigCPtr, this);
  }

  public SWIGTYPE_p_NxMaterialIndex getMaterialIndex(String arg0) {
    return new SWIGTYPE_p_NxMaterialIndex(MyoushuJNI.Scene_getMaterialIndex(swigCPtr, this, arg0), true);
  }

  public SWIGTYPE_p_NxOgre__ActorGroup createActorGroup(String name) {
    long cPtr = MyoushuJNI.Scene_createActorGroup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ActorGroup(cPtr, false);
  }

  public void destroyActorGroup(String name) {
    MyoushuJNI.Scene_destroyActorGroup(swigCPtr, this, name);
  }

  public long getNbActorGroups() {
    return MyoushuJNI.Scene_getNbActorGroups(swigCPtr, this);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__ActorGroup_p_t getActorGroups() {
    long cPtr = MyoushuJNI.Scene_getActorGroups(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__ActorGroup_p_t(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_NxActorGroup_NxOgre__ActorGroup_p_t getActorGroupsByIndex() {
    long cPtr = MyoushuJNI.Scene_getActorGroupsByIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_NxActorGroup_NxOgre__ActorGroup_p_t(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ActorGroup getActorGroup(String name) {
    long cPtr = MyoushuJNI.Scene_getActorGroup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ActorGroup(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ShapeGroup createShapeGroup(String name) {
    long cPtr = MyoushuJNI.Scene_createShapeGroup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ShapeGroup(cPtr, false);
  }

  public void destroyShapeGroup(String name) {
    MyoushuJNI.Scene_destroyShapeGroup(swigCPtr, this, name);
  }

  public long getNbShapeGroups() {
    return MyoushuJNI.Scene_getNbShapeGroups(swigCPtr, this);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__ShapeGroup_p_t getShapeGroups() {
    long cPtr = MyoushuJNI.Scene_getShapeGroups(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_std__string_NxOgre__ShapeGroup_p_t(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ContainerT_NxCollisionGroup_NxOgre__ShapeGroup_p_t getShapeGroupsByIndex() {
    long cPtr = MyoushuJNI.Scene_getShapeGroupsByIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ContainerT_NxCollisionGroup_NxOgre__ShapeGroup_p_t(cPtr, false);
  }

  public SWIGTYPE_p_NxOgre__ShapeGroup getShapeGroup(String name) {
    long cPtr = MyoushuJNI.Scene_getShapeGroup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxOgre__ShapeGroup(cPtr, false);
  }

  public void addFloor() {
    MyoushuJNI.Scene_addFloor__SWIG_0(swigCPtr, this);
  }

  public void addFloor(float y) {
    MyoushuJNI.Scene_addFloor__SWIG_1(swigCPtr, this, y);
  }

  public void setStaticGeometry(SWIGTYPE_p_Ogre__StaticGeometry arg0) {
    MyoushuJNI.Scene_setStaticGeometry(swigCPtr, this, SWIGTYPE_p_Ogre__StaticGeometry.getCPtr(arg0));
  }

  public SWIGTYPE_p_Ogre__StaticGeometry getStaticGeometry() {
    long cPtr = MyoushuJNI.Scene_getStaticGeometry__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__StaticGeometry(cPtr, false);
  }

  public void removeStaticGeometry() {
    MyoushuJNI.Scene_removeStaticGeometry(swigCPtr, this);
  }

  public void _registerHelper(String name, SWIGTYPE_p_NxOgre__Helper arg1) {
    MyoushuJNI.Scene__registerHelper(swigCPtr, this, name, SWIGTYPE_p_NxOgre__Helper.getCPtr(arg1));
  }

  public void _unregisterHelper(String arg0) {
    MyoushuJNI.Scene__unregisterHelper(swigCPtr, this, arg0);
  }

  public void idle() {
    MyoushuJNI.Scene_idle(swigCPtr, this);
  }

}
