/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Singleton_Application {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Singleton_Application(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Singleton_Application obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Singleton_Application(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Singleton_Application() {
    this(MyoushuJNI.new_Singleton_Application(), true);
  }

  public static Application getSingleton() {
    return new Application(MyoushuJNI.Singleton_Application_getSingleton(), false);
  }

  public static Application getSingletonPtr() {
    long cPtr = MyoushuJNI.Singleton_Application_getSingletonPtr();
    return (cPtr == 0) ? null : new Application(cPtr, false);
  }

}
