/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class SWIGTYPE_p_NxOgre__Scene {
  private long swigCPtr;

  protected SWIGTYPE_p_NxOgre__Scene(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_NxOgre__Scene() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_NxOgre__Scene obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

