/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class VectorInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public VectorInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectorInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_VectorInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorInt() {
    this(MyoushuJNI.new_VectorInt__SWIG_0(), true);
  }

  public VectorInt(long n) {
    this(MyoushuJNI.new_VectorInt__SWIG_1(n), true);
  }

  public long size() {
    return MyoushuJNI.VectorInt_size(swigCPtr, this);
  }

  public long capacity() {
    return MyoushuJNI.VectorInt_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MyoushuJNI.VectorInt_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MyoushuJNI.VectorInt_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MyoushuJNI.VectorInt_clear(swigCPtr, this);
  }

  public void add(int x) {
    MyoushuJNI.VectorInt_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return MyoushuJNI.VectorInt_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    MyoushuJNI.VectorInt_set(swigCPtr, this, i, val);
  }

}
