/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class VectorAutoPtr_Value {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public VectorAutoPtr_Value(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectorAutoPtr_Value obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_VectorAutoPtr_Value(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorAutoPtr_Value() {
    this(MyoushuJNI.new_VectorAutoPtr_Value__SWIG_0(), true);
  }

  public VectorAutoPtr_Value(long n) {
    this(MyoushuJNI.new_VectorAutoPtr_Value__SWIG_1(n), true);
  }

  public long size() {
    return MyoushuJNI.VectorAutoPtr_Value_size(swigCPtr, this);
  }

  public long capacity() {
    return MyoushuJNI.VectorAutoPtr_Value_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MyoushuJNI.VectorAutoPtr_Value_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MyoushuJNI.VectorAutoPtr_Value_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MyoushuJNI.VectorAutoPtr_Value_clear(swigCPtr, this);
  }

  public void add(AutoPtr_Value x) {
    MyoushuJNI.VectorAutoPtr_Value_add(swigCPtr, this, AutoPtr_Value.getCPtr(x), x);
  }

  public AutoPtr_Value get(int i) {
    return new AutoPtr_Value(MyoushuJNI.VectorAutoPtr_Value_get(swigCPtr, this, i), false);
  }

  public void set(int i, AutoPtr_Value val) {
    MyoushuJNI.VectorAutoPtr_Value_set(swigCPtr, this, i, AutoPtr_Value.getCPtr(val), val);
  }

}
