/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ASTTJava;

public class ListFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ListFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ListFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ASTTJNI.delete_ListFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListFloat() {
    this(ASTTJNI.new_ListFloat__SWIG_0(), true);
  }

  public ListFloat(ListFloat arg0) {
    this(ASTTJNI.new_ListFloat__SWIG_1(ListFloat.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return ASTTJNI.ListFloat_size(swigCPtr, this);
  }

  public boolean empty() {
    return ASTTJNI.ListFloat_empty(swigCPtr, this);
  }

  public void clear() {
    ASTTJNI.ListFloat_clear(swigCPtr, this);
  }

  public void push_back(float val) {
    ASTTJNI.ListFloat_push_back(swigCPtr, this, val);
  }

  public void pop_back() {
    ASTTJNI.ListFloat_pop_back(swigCPtr, this);
  }

  public float front() {
    return ASTTJNI.ListFloat_front(swigCPtr, this);
  }

  public float back() {
    return ASTTJNI.ListFloat_back(swigCPtr, this);
  }

}
