/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ASTTJava;

public class ListBool {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ListBool(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ListBool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ASTTJNI.delete_ListBool(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListBool() {
    this(ASTTJNI.new_ListBool__SWIG_0(), true);
  }

  public ListBool(ListBool arg0) {
    this(ASTTJNI.new_ListBool__SWIG_1(ListBool.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return ASTTJNI.ListBool_size(swigCPtr, this);
  }

  public boolean empty() {
    return ASTTJNI.ListBool_empty(swigCPtr, this);
  }

  public void clear() {
    ASTTJNI.ListBool_clear(swigCPtr, this);
  }

  public void push_back(boolean val) {
    ASTTJNI.ListBool_push_back(swigCPtr, this, val);
  }

  public void pop_back() {
    ASTTJNI.ListBool_pop_back(swigCPtr, this);
  }

  public boolean front() {
    return ASTTJNI.ListBool_front(swigCPtr, this);
  }

  public boolean back() {
    return ASTTJNI.ListBool_back(swigCPtr, this);
  }

}
