/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ASTTJava;

public class VectorDouble {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public VectorDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectorDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ASTTJNI.delete_VectorDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorDouble() {
    this(ASTTJNI.new_VectorDouble__SWIG_0(), true);
  }

  public VectorDouble(long n) {
    this(ASTTJNI.new_VectorDouble__SWIG_1(n), true);
  }

  public long size() {
    return ASTTJNI.VectorDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return ASTTJNI.VectorDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ASTTJNI.VectorDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ASTTJNI.VectorDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ASTTJNI.VectorDouble_clear(swigCPtr, this);
  }

  public void add(double x) {
    ASTTJNI.VectorDouble_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return ASTTJNI.VectorDouble_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    ASTTJNI.VectorDouble_set(swigCPtr, this, i, val);
  }

}
