/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class AutoPtr_NetworkMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public AutoPtr_NetworkMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AutoPtr_NetworkMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_AutoPtr_NetworkMessage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public AutoPtr_NetworkMessage() {
    this(MyoushuJNI.new_AutoPtr_NetworkMessage__SWIG_0(), true);
  }

  public AutoPtr_NetworkMessage(NetworkMessage ptr) {
    this(MyoushuJNI.new_AutoPtr_NetworkMessage__SWIG_1(NetworkMessage.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_NetworkMessage(NetworkMessage ptr, boolean shared) {
    this(MyoushuJNI.new_AutoPtr_NetworkMessage__SWIG_2(NetworkMessage.getCPtr(ptr), ptr, shared), true);
  }

  public AutoPtr_NetworkMessage(AutoPtr_NetworkMessage ptr) {
    this(MyoushuJNI.new_AutoPtr_NetworkMessage__SWIG_3(AutoPtr_NetworkMessage.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_NetworkMessage assign(NetworkMessage ptr) {
    return new AutoPtr_NetworkMessage(MyoushuJNI.AutoPtr_NetworkMessage_assign__SWIG_0(swigCPtr, this, NetworkMessage.getCPtr(ptr), ptr), false);
  }

  public AutoPtr_NetworkMessage assign(NetworkMessage ptr, boolean shared) {
    return new AutoPtr_NetworkMessage(MyoushuJNI.AutoPtr_NetworkMessage_assign__SWIG_1(swigCPtr, this, NetworkMessage.getCPtr(ptr), ptr, shared), false);
  }

  public AutoPtr_NetworkMessage assign(AutoPtr_NetworkMessage ptr) {
    return new AutoPtr_NetworkMessage(MyoushuJNI.AutoPtr_NetworkMessage_assign__SWIG_2(swigCPtr, this, AutoPtr_NetworkMessage.getCPtr(ptr), ptr), false);
  }

  public void swap(AutoPtr_NetworkMessage ptr) {
    MyoushuJNI.AutoPtr_NetworkMessage_swap(swigCPtr, this, AutoPtr_NetworkMessage.getCPtr(ptr), ptr);
  }

  public NetworkMessage __deref__() {
    long cPtr = MyoushuJNI.AutoPtr_NetworkMessage___deref____SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new NetworkMessage(cPtr, false);
  }

  public NetworkMessage __ref__() {
    return new NetworkMessage(MyoushuJNI.AutoPtr_NetworkMessage___ref____SWIG_0(swigCPtr, this), false);
  }

  public NetworkMessage get() {
    long cPtr = MyoushuJNI.AutoPtr_NetworkMessage_get__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new NetworkMessage(cPtr, false);
  }

  public boolean isNull() {
    return MyoushuJNI.AutoPtr_NetworkMessage_isNull(swigCPtr, this);
  }

  public NetworkMessage duplicate() {
    long cPtr = MyoushuJNI.AutoPtr_NetworkMessage_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new NetworkMessage(cPtr, false);
  }

  public String getClassName() {
    return MyoushuJNI.AutoPtr_NetworkMessage_getClassName(swigCPtr, this);
  }

  public NetworkMessage.NetworkMessageType getType() {
    return NetworkMessage.NetworkMessageType.swigToEnum(MyoushuJNI.AutoPtr_NetworkMessage_getType(swigCPtr, this));
  }

  public SWIGTYPE_p_Poco__Net__IPAddress getDestination() {
    return new SWIGTYPE_p_Poco__Net__IPAddress(MyoushuJNI.AutoPtr_NetworkMessage_getDestination(swigCPtr, this), true);
  }

  public SWIGTYPE_p_Poco__Net__IPAddress getSource() {
    return new SWIGTYPE_p_Poco__Net__IPAddress(MyoushuJNI.AutoPtr_NetworkMessage_getSource(swigCPtr, this), true);
  }

  public String getSourceAsString() {
    return MyoushuJNI.AutoPtr_NetworkMessage_getSourceAsString(swigCPtr, this);
  }

  public String getObjectName() {
    return MyoushuJNI.AutoPtr_NetworkMessage_getObjectName(swigCPtr, this);
  }

  public String getObjectClassName() {
    return MyoushuJNI.AutoPtr_NetworkMessage_getObjectClassName(swigCPtr, this);
  }

  public void clone(NetworkMessage dest) {
    MyoushuJNI.AutoPtr_NetworkMessage_clone(swigCPtr, this, NetworkMessage.getCPtr(dest), dest);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size, Serializable.SerializationTarget sTarget) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.AutoPtr_NetworkMessage_serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size), sTarget.swigValue()), true);
  }

  public SWIGTYPE_p_uint32_t serialize(SWIGTYPE_p_void pMem, SWIGTYPE_p_uint32_t size) {
    return new SWIGTYPE_p_uint32_t(MyoushuJNI.AutoPtr_NetworkMessage_serialize__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(pMem), SWIGTYPE_p_uint32_t.getCPtr(size)), true);
  }

  public SWIGTYPE_p_Poco__Net__IPAddress getCreator() {
    return new SWIGTYPE_p_Poco__Net__IPAddress(MyoushuJNI.AutoPtr_NetworkMessage_getCreator(swigCPtr, this), true);
  }

}
