/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class AutoPtr_MouseOISInputDevice {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public AutoPtr_MouseOISInputDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AutoPtr_MouseOISInputDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_AutoPtr_MouseOISInputDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AutoPtr_MouseOISInputDevice() {
    this(MyoushuJNI.new_AutoPtr_MouseOISInputDevice__SWIG_0(), true);
  }

  public AutoPtr_MouseOISInputDevice(MouseOISInputDevice ptr) {
    this(MyoushuJNI.new_AutoPtr_MouseOISInputDevice__SWIG_1(MouseOISInputDevice.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_MouseOISInputDevice(MouseOISInputDevice ptr, boolean shared) {
    this(MyoushuJNI.new_AutoPtr_MouseOISInputDevice__SWIG_2(MouseOISInputDevice.getCPtr(ptr), ptr, shared), true);
  }

  public AutoPtr_MouseOISInputDevice(AutoPtr_MouseOISInputDevice ptr) {
    this(MyoushuJNI.new_AutoPtr_MouseOISInputDevice__SWIG_3(AutoPtr_MouseOISInputDevice.getCPtr(ptr), ptr), true);
  }

  public AutoPtr_MouseOISInputDevice assign(MouseOISInputDevice ptr) {
    return new AutoPtr_MouseOISInputDevice(MyoushuJNI.AutoPtr_MouseOISInputDevice_assign__SWIG_0(swigCPtr, this, MouseOISInputDevice.getCPtr(ptr), ptr), false);
  }

  public AutoPtr_MouseOISInputDevice assign(MouseOISInputDevice ptr, boolean shared) {
    return new AutoPtr_MouseOISInputDevice(MyoushuJNI.AutoPtr_MouseOISInputDevice_assign__SWIG_1(swigCPtr, this, MouseOISInputDevice.getCPtr(ptr), ptr, shared), false);
  }

  public AutoPtr_MouseOISInputDevice assign(AutoPtr_MouseOISInputDevice ptr) {
    return new AutoPtr_MouseOISInputDevice(MyoushuJNI.AutoPtr_MouseOISInputDevice_assign__SWIG_2(swigCPtr, this, AutoPtr_MouseOISInputDevice.getCPtr(ptr), ptr), false);
  }

  public void swap(AutoPtr_MouseOISInputDevice ptr) {
    MyoushuJNI.AutoPtr_MouseOISInputDevice_swap(swigCPtr, this, AutoPtr_MouseOISInputDevice.getCPtr(ptr), ptr);
  }

  public MouseOISInputDevice __deref__() {
    long cPtr = MyoushuJNI.AutoPtr_MouseOISInputDevice___deref____SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseOISInputDevice(cPtr, false);
  }

  public MouseOISInputDevice __ref__() {
    return new MouseOISInputDevice(MyoushuJNI.AutoPtr_MouseOISInputDevice___ref____SWIG_0(swigCPtr, this), false);
  }

  public MouseOISInputDevice get() {
    long cPtr = MyoushuJNI.AutoPtr_MouseOISInputDevice_get__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseOISInputDevice(cPtr, false);
  }

  public boolean isNull() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_isNull(swigCPtr, this);
  }

  public MouseOISInputDevice duplicate() {
    long cPtr = MyoushuJNI.AutoPtr_MouseOISInputDevice_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseOISInputDevice(cPtr, false);
  }

  public String getINPUT_DEVICE_NAME() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_INPUT_DEVICE_NAME_get(swigCPtr, this);
  }

  public String getInputEventString(String inputIdentifier) {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_getInputEventString(swigCPtr, this, inputIdentifier);
  }

  public int getInputCodeFromInputIdentifier(String inputIdentifier) {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_getInputCodeFromInputIdentifier(swigCPtr, this, inputIdentifier);
  }

  public String getInputIdentifierFromInputCode(int inputCode) {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_getInputIdentifierFromInputCode(swigCPtr, this, inputCode);
  }

  public String getMI_X_AXIS() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_X_AXIS_get(swigCPtr, this);
  }

  public String getMI_Y_AXIS() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_Y_AXIS_get(swigCPtr, this);
  }

  public String getMI_WHEEL() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_WHEEL_get(swigCPtr, this);
  }

  public String getMI_BUTTON() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_get(swigCPtr, this);
  }

  public String getMI_BUTTON_0() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_0_get(swigCPtr, this);
  }

  public String getMI_BUTTON_1() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_1_get(swigCPtr, this);
  }

  public String getMI_BUTTON_2() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_2_get(swigCPtr, this);
  }

  public String getMI_BUTTON_3() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_3_get(swigCPtr, this);
  }

  public String getMI_BUTTON_4() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_4_get(swigCPtr, this);
  }

  public String getMI_BUTTON_5() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_5_get(swigCPtr, this);
  }

  public String getMI_BUTTON_6() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_6_get(swigCPtr, this);
  }

  public String getMI_BUTTON_7() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_7_get(swigCPtr, this);
  }

  public String getMI_BUTTON_8() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_8_get(swigCPtr, this);
  }

  public String getMI_BUTTON_9() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_MI_BUTTON_9_get(swigCPtr, this);
  }

  public InputDevice.InputDeviceType getDeviceType() {
    return InputDevice.InputDeviceType.swigToEnum(MyoushuJNI.AutoPtr_MouseOISInputDevice_getDeviceType(swigCPtr, this));
  }

  public String getName() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_getName(swigCPtr, this);
  }

  public void release() {
    MyoushuJNI.AutoPtr_MouseOISInputDevice_release(swigCPtr, this);
  }

  public int referenceCount() {
    return MyoushuJNI.AutoPtr_MouseOISInputDevice_referenceCount(swigCPtr, this);
  }

}
