/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Box {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Box(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Box obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Box(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeft(long value) {
    MyoushuJNI.Box_left_set(swigCPtr, this, value);
  }

  public long getLeft() {
    return MyoushuJNI.Box_left_get(swigCPtr, this);
  }

  public void setTop(long value) {
    MyoushuJNI.Box_top_set(swigCPtr, this, value);
  }

  public long getTop() {
    return MyoushuJNI.Box_top_get(swigCPtr, this);
  }

  public void setRight(long value) {
    MyoushuJNI.Box_right_set(swigCPtr, this, value);
  }

  public long getRight() {
    return MyoushuJNI.Box_right_get(swigCPtr, this);
  }

  public void setBottom(long value) {
    MyoushuJNI.Box_bottom_set(swigCPtr, this, value);
  }

  public long getBottom() {
    return MyoushuJNI.Box_bottom_get(swigCPtr, this);
  }

  public void setFront(long value) {
    MyoushuJNI.Box_front_set(swigCPtr, this, value);
  }

  public long getFront() {
    return MyoushuJNI.Box_front_get(swigCPtr, this);
  }

  public void setBack(long value) {
    MyoushuJNI.Box_back_set(swigCPtr, this, value);
  }

  public long getBack() {
    return MyoushuJNI.Box_back_get(swigCPtr, this);
  }

  public Box() {
    this(MyoushuJNI.new_Box__SWIG_0(), true);
  }

  public Box(long l, long t, long r, long b) {
    this(MyoushuJNI.new_Box__SWIG_1(l, t, r, b), true);
  }

  public Box(long l, long t, long ff, long r, long b, long bb) {
    this(MyoushuJNI.new_Box__SWIG_2(l, t, ff, r, b, bb), true);
  }

  public boolean contains(Box def) {
    return MyoushuJNI.Box_contains(swigCPtr, this, Box.getCPtr(def), def);
  }

  public long getWidth() {
    return MyoushuJNI.Box_getWidth(swigCPtr, this);
  }

  public long getHeight() {
    return MyoushuJNI.Box_getHeight(swigCPtr, this);
  }

  public long getDepth() {
    return MyoushuJNI.Box_getDepth(swigCPtr, this);
  }

}
