/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ContentImporter extends NamedInstance {
  private long swigCPtr;

  public ContentImporter(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGContentImporterUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContentImporter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ContentImporter(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getClassName() {
    return MyoushuJNI.ContentImporter_getClassName(swigCPtr, this);
  }

  public void initialize() {
    MyoushuJNI.ContentImporter_initialize(swigCPtr, this);
  }

  public void shutdown() {
    MyoushuJNI.ContentImporter_shutdown(swigCPtr, this);
  }

  public void importContent(Scene pScene, String path, String resourceGroup, SceneNode pRootSceneNode, String importPrefix) {
    MyoushuJNI.ContentImporter_importContent__SWIG_0(swigCPtr, this, Scene.getCPtr(pScene), pScene, path, resourceGroup, SceneNode.getCPtr(pRootSceneNode), pRootSceneNode, importPrefix);
  }

  public void importContent(Scene pScene, String path, String resourceGroup, SceneNode pRootSceneNode) {
    MyoushuJNI.ContentImporter_importContent__SWIG_1(swigCPtr, this, Scene.getCPtr(pScene), pScene, path, resourceGroup, SceneNode.getCPtr(pRootSceneNode), pRootSceneNode);
  }

  public void importContent(Scene pScene, String path, String resourceGroup) {
    MyoushuJNI.ContentImporter_importContent__SWIG_2(swigCPtr, this, Scene.getCPtr(pScene), pScene, path, resourceGroup);
  }

  public void importContent(Scene pScene, String path) {
    MyoushuJNI.ContentImporter_importContent__SWIG_3(swigCPtr, this, Scene.getCPtr(pScene), pScene, path);
  }

}
