/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ConvexShape extends ShapeBlueprint {
  private long swigCPtr;

  public ConvexShape(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGConvexShapeUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ConvexShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ConvexShape(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ConvexShape(String meshName, ShapeParams arg1) {
    this(MyoushuJNI.new_ConvexShape__SWIG_0(meshName, ShapeParams.getCPtr(arg1), arg1), true);
  }

  public ConvexShape(String meshName) {
    this(MyoushuJNI.new_ConvexShape__SWIG_1(meshName), true);
  }

}
