/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ElementEnumerator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ElementEnumerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ElementEnumerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ElementEnumerator(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean next() {
    return MyoushuJNI.ElementEnumerator_next__SWIG_0(swigCPtr, this);
  }

  public boolean next(String _name) {
    return MyoushuJNI.ElementEnumerator_next__SWIG_1(swigCPtr, this, _name);
  }

  public Element __deref__() {
    long cPtr = MyoushuJNI.ElementEnumerator___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public Element current() {
    long cPtr = MyoushuJNI.ElementEnumerator_current(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public boolean nextNode() {
    return MyoushuJNI.ElementEnumerator_nextNode__SWIG_0(swigCPtr, this);
  }

  public boolean nextNode(String _name) {
    return MyoushuJNI.ElementEnumerator_nextNode__SWIG_1(swigCPtr, this, _name);
  }

  public Element currentNode() {
    long cPtr = MyoushuJNI.ElementEnumerator_currentNode(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public Element createChild(String _name, String _content) {
    long cPtr = MyoushuJNI.ElementEnumerator_createChild__SWIG_0(swigCPtr, this, _name, _content);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public Element createChild(String _name) {
    long cPtr = MyoushuJNI.ElementEnumerator_createChild__SWIG_1(swigCPtr, this, _name);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public void addAttributes(String _key, String _value) {
    MyoushuJNI.ElementEnumerator_addAttributes(swigCPtr, this, _key, _value);
  }

  public void addAttribute(String _key, String _value) {
    MyoushuJNI.ElementEnumerator_addAttribute(swigCPtr, this, _key, _value);
  }

  public void removeAttribute(String _key) {
    MyoushuJNI.ElementEnumerator_removeAttribute(swigCPtr, this, _key);
  }

  public void setAttribute(String _key, String _value) {
    MyoushuJNI.ElementEnumerator_setAttribute(swigCPtr, this, _key, _value);
  }

  public void addContent(String _content) {
    MyoushuJNI.ElementEnumerator_addContent(swigCPtr, this, _content);
  }

  public void setContent(String _content) {
    MyoushuJNI.ElementEnumerator_setContent(swigCPtr, this, _content);
  }

  public void addBody(String _content) {
    MyoushuJNI.ElementEnumerator_addBody(swigCPtr, this, _content);
  }

  public void setBody(String _content) {
    MyoushuJNI.ElementEnumerator_setBody(swigCPtr, this, _content);
  }

  public void clear() {
    MyoushuJNI.ElementEnumerator_clear(swigCPtr, this);
  }

  public boolean findAttribute(String _name, SWIGTYPE_p_std__string _value) {
    return MyoushuJNI.ElementEnumerator_findAttribute__SWIG_0(swigCPtr, this, _name, SWIGTYPE_p_std__string.getCPtr(_value));
  }

  public String findAttribute(String _name) {
    return MyoushuJNI.ElementEnumerator_findAttribute__SWIG_1(swigCPtr, this, _name);
  }

  public String getName() {
    return MyoushuJNI.ElementEnumerator_getName(swigCPtr, this);
  }

  public String getContent() {
    return MyoushuJNI.ElementEnumerator_getContent(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t getAttributes() {
    return new SWIGTYPE_p_std__vectorT_std__pairT_std__string_std__string_t_t(MyoushuJNI.ElementEnumerator_getAttributes(swigCPtr, this), false);
  }

  public Element getParent() {
    long cPtr = MyoushuJNI.ElementEnumerator_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public ElementEnumerator getElementEnumerator() {
    return new ElementEnumerator(MyoushuJNI.ElementEnumerator_getElementEnumerator(swigCPtr, this), true);
  }

  public ElementType getType() {
    return new ElementType(MyoushuJNI.ElementEnumerator_getType(swigCPtr, this), true);
  }

  public String getBody() {
    return MyoushuJNI.ElementEnumerator_getBody(swigCPtr, this);
  }

  public ElementEnumerator getNodeIterator() {
    return new ElementEnumerator(MyoushuJNI.ElementEnumerator_getNodeIterator(swigCPtr, this), true);
  }

  public Element createCopy() {
    long cPtr = MyoushuJNI.ElementEnumerator_createCopy(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

}
