/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public enum FrustumPlane {
  FRUSTUM_PLANE_NEAR(MyoushuJNI.FRUSTUM_PLANE_NEAR_get()),
  FRUSTUM_PLANE_FAR(MyoushuJNI.FRUSTUM_PLANE_FAR_get()),
  FRUSTUM_PLANE_LEFT(MyoushuJNI.FRUSTUM_PLANE_LEFT_get()),
  FRUSTUM_PLANE_RIGHT(MyoushuJNI.FRUSTUM_PLANE_RIGHT_get()),
  FRUSTUM_PLANE_TOP(MyoushuJNI.FRUSTUM_PLANE_TOP_get()),
  FRUSTUM_PLANE_BOTTOM(MyoushuJNI.FRUSTUM_PLANE_BOTTOM_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FrustumPlane swigToEnum(int swigValue) {
    FrustumPlane[] swigValues = FrustumPlane.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FrustumPlane swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FrustumPlane.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FrustumPlane() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FrustumPlane(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FrustumPlane(FrustumPlane swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

