/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class GameTask extends Task {
  private long swigCPtr;

  public GameTask(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGGameTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(GameTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_GameTask(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public GameTask(int priority, String name, long executionInterval, long iterationLimit) {
    this(MyoushuJNI.new_GameTask__SWIG_0(priority, name, executionInterval, iterationLimit), true);
  }

  public GameTask(int priority, String name, long executionInterval) {
    this(MyoushuJNI.new_GameTask__SWIG_1(priority, name, executionInterval), true);
  }

  public GameTask(int priority, String name) {
    this(MyoushuJNI.new_GameTask__SWIG_2(priority, name), true);
  }

  public GameTask() {
    this(MyoushuJNI.new_GameTask__SWIG_3(), true);
  }

  public String getClassName() {
    return MyoushuJNI.GameTask_getClassName(swigCPtr, this);
  }

  public void init() {
    MyoushuJNI.GameTask_init(swigCPtr, this);
  }

  public void suspend() {
    MyoushuJNI.GameTask_suspend(swigCPtr, this);
  }

  public void execute(long timeDelta) {
    MyoushuJNI.GameTask_execute(swigCPtr, this, timeDelta);
  }

  public void kill() {
    MyoushuJNI.GameTask_kill(swigCPtr, this);
  }

}
