/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class GroupImage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GroupImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GroupImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_GroupImage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    MyoushuJNI.GroupImage_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return MyoushuJNI.GroupImage_name_get(swigCPtr, this);
  }

  public void setTexture(String value) {
    MyoushuJNI.GroupImage_texture_set(swigCPtr, this, value);
  }

  public String getTexture() {
    return MyoushuJNI.GroupImage_texture_get(swigCPtr, this);
  }

  public void setSize(SWIGTYPE_p_MyGUI__types__TSizeT_int_t value) {
    MyoushuJNI.GroupImage_size_set(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TSizeT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_MyGUI__types__TSizeT_int_t getSize() {
    long cPtr = MyoushuJNI.GroupImage_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyGUI__types__TSizeT_int_t(cPtr, false);
  }

  public void setIndexes(SWIGTYPE_p_std__vectorT_MyGUI__IndexImage_t value) {
    MyoushuJNI.GroupImage_indexes_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_MyGUI__IndexImage_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_MyGUI__IndexImage_t getIndexes() {
    long cPtr = MyoushuJNI.GroupImage_indexes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_MyGUI__IndexImage_t(cPtr, false);
  }

  public GroupImage() {
    this(MyoushuJNI.new_GroupImage(), true);
  }

}
