/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ISubWidgetText extends ISubWidget {
  private long swigCPtr;

  public ISubWidgetText(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGISubWidgetTextUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ISubWidgetText obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ISubWidgetText(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public long getSelectStart() {
    return MyoushuJNI.ISubWidgetText_getSelectStart(swigCPtr, this);
  }

  public long getSelectEnd() {
    return MyoushuJNI.ISubWidgetText_getSelectEnd(swigCPtr, this);
  }

  public void setTextSelect(long _start, long _end) {
    MyoushuJNI.ISubWidgetText_setTextSelect(swigCPtr, this, _start, _end);
  }

  public boolean getSelectBackground() {
    return MyoushuJNI.ISubWidgetText_getSelectBackground(swigCPtr, this);
  }

  public void setSelectBackground(boolean _normal) {
    MyoushuJNI.ISubWidgetText_setSelectBackground(swigCPtr, this, _normal);
  }

  public boolean isCursorShow() {
    return MyoushuJNI.ISubWidgetText_isCursorShow(swigCPtr, this);
  }

  public void setShowCursor(boolean _show) {
    MyoushuJNI.ISubWidgetText_setShowCursor(swigCPtr, this, _show);
  }

  public long getCursorPosition() {
    return MyoushuJNI.ISubWidgetText_getCursorPosition__SWIG_0(swigCPtr, this);
  }

  public void setCursorPosition(long _pos) {
    MyoushuJNI.ISubWidgetText_setCursorPosition(swigCPtr, this, _pos);
  }

  public void setBreakLine(boolean _break) {
    MyoushuJNI.ISubWidgetText_setBreakLine(swigCPtr, this, _break);
  }

  public long getCursorPosition(SWIGTYPE_p_MyGUI__types__TPointT_int_t _point) {
    return MyoushuJNI.ISubWidgetText_getCursorPosition__SWIG_1(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TPointT_int_t.getCPtr(_point));
  }

  public SWIGTYPE_p_MyGUI__types__TCoordT_int_t getCursorCoord(long _position) {
    return new SWIGTYPE_p_MyGUI__types__TCoordT_int_t(MyoushuJNI.ISubWidgetText_getCursorCoord(swigCPtr, this, _position), true);
  }

  public SWIGTYPE_p_MyGUI__types__TPointT_int_t getCursorPoint(long _position) {
    return new SWIGTYPE_p_MyGUI__types__TPointT_int_t(MyoushuJNI.ISubWidgetText_getCursorPoint(swigCPtr, this, _position), true);
  }

  public SWIGTYPE_p_MyGUI__types__TRectT_int_t getCursorRect(long _position) {
    return new SWIGTYPE_p_MyGUI__types__TRectT_int_t(MyoushuJNI.ISubWidgetText_getCursorRect(swigCPtr, this, _position), true);
  }

  public SWIGTYPE_p_MyGUI__types__TSizeT_int_t getTextSize() {
    return new SWIGTYPE_p_MyGUI__types__TSizeT_int_t(MyoushuJNI.ISubWidgetText_getTextSize(swigCPtr, this), true);
  }

  public void setViewOffset(SWIGTYPE_p_MyGUI__types__TPointT_int_t _point) {
    MyoushuJNI.ISubWidgetText_setViewOffset(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TPointT_int_t.getCPtr(_point));
  }

  public SWIGTYPE_p_MyGUI__types__TPointT_int_t getViewOffset() {
    return new SWIGTYPE_p_MyGUI__types__TPointT_int_t(MyoushuJNI.ISubWidgetText_getViewOffset(swigCPtr, this), true);
  }

  public void setCaption(UString _caption) {
    MyoushuJNI.ISubWidgetText_setCaption(swigCPtr, this, UString.getCPtr(_caption), _caption);
  }

  public UString getCaption() {
    return new UString(MyoushuJNI.ISubWidgetText_getCaption(swigCPtr, this), false);
  }

  public void setTextColour(Colour _colour) {
    MyoushuJNI.ISubWidgetText_setTextColour(swigCPtr, this, Colour.getCPtr(_colour), _colour);
  }

  public Colour getTextColour() {
    return new Colour(MyoushuJNI.ISubWidgetText_getTextColour(swigCPtr, this), false);
  }

  public void setFontName(String _font) {
    MyoushuJNI.ISubWidgetText_setFontName(swigCPtr, this, _font);
  }

  public String getFontName() {
    return MyoushuJNI.ISubWidgetText_getFontName(swigCPtr, this);
  }

  public void setFontHeight(int _height) {
    MyoushuJNI.ISubWidgetText_setFontHeight(swigCPtr, this, _height);
  }

  public int getFontHeight() {
    return MyoushuJNI.ISubWidgetText_getFontHeight(swigCPtr, this);
  }

  public void setTextAlign(Align _align) {
    MyoushuJNI.ISubWidgetText_setTextAlign(swigCPtr, this, Align.getCPtr(_align), _align);
  }

  public Align getTextAlign() {
    return new Align(MyoushuJNI.ISubWidgetText_getTextAlign(swigCPtr, this), true);
  }

  public void setShiftText(boolean _shift) {
    MyoushuJNI.ISubWidgetText_setShiftText(swigCPtr, this, _shift);
  }

}
