/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class KernelManager extends Singleton_KernelManager {
  private long swigCPtr;

  public KernelManager(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGKernelManagerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(KernelManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_KernelManager(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public KernelManager() {
    this(MyoushuJNI.new_KernelManager(), true);
  }

  public void stopKernel() {
    MyoushuJNI.KernelManager_stopKernel(swigCPtr, this);
  }

  public void addTask(Task task) {
    MyoushuJNI.KernelManager_addTask(swigCPtr, this, Task.getCPtr(task), task);
  }

  public void suspendTask(Task task) {
    MyoushuJNI.KernelManager_suspendTask__SWIG_0(swigCPtr, this, Task.getCPtr(task), task);
  }

  public void suspendTask(String name) {
    MyoushuJNI.KernelManager_suspendTask__SWIG_1(swigCPtr, this, name);
  }

  public void removeTask(Task task) {
    MyoushuJNI.KernelManager_removeTask__SWIG_0(swigCPtr, this, Task.getCPtr(task), task);
  }

  public void removeTask(String name) {
    MyoushuJNI.KernelManager_removeTask__SWIG_1(swigCPtr, this, name);
  }

  public void initAllTasks() {
    MyoushuJNI.KernelManager_initAllTasks(swigCPtr, this);
  }

  public CallbackTask createCallbackTask(int priority, String name, long executionInterval, long iterationLimit) {
    long cPtr = MyoushuJNI.KernelManager_createCallbackTask__SWIG_0(swigCPtr, this, priority, name, executionInterval, iterationLimit);
    return (cPtr == 0) ? null : new CallbackTask(cPtr, false);
  }

  public CallbackTask createCallbackTask(int priority, String name, long executionInterval) {
    long cPtr = MyoushuJNI.KernelManager_createCallbackTask__SWIG_1(swigCPtr, this, priority, name, executionInterval);
    return (cPtr == 0) ? null : new CallbackTask(cPtr, false);
  }

  public CallbackTask createCallbackTask(int priority, String name) {
    long cPtr = MyoushuJNI.KernelManager_createCallbackTask__SWIG_2(swigCPtr, this, priority, name);
    return (cPtr == 0) ? null : new CallbackTask(cPtr, false);
  }

}
