/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class KeyboardInputDevice extends HumanInputDevice {
  private long swigCPtr;

  public KeyboardInputDevice(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGKeyboardInputDeviceUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(KeyboardInputDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_KeyboardInputDevice(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public static String getKI_UNASSIGNED() {
    return MyoushuJNI.KeyboardInputDevice_KI_UNASSIGNED_get();
  }

  public static String getKI_ESCAPE() {
    return MyoushuJNI.KeyboardInputDevice_KI_ESCAPE_get();
  }

  public static String getKI_1() {
    return MyoushuJNI.KeyboardInputDevice_KI_1_get();
  }

  public static String getKI_2() {
    return MyoushuJNI.KeyboardInputDevice_KI_2_get();
  }

  public static String getKI_3() {
    return MyoushuJNI.KeyboardInputDevice_KI_3_get();
  }

  public static String getKI_4() {
    return MyoushuJNI.KeyboardInputDevice_KI_4_get();
  }

  public static String getKI_5() {
    return MyoushuJNI.KeyboardInputDevice_KI_5_get();
  }

  public static String getKI_6() {
    return MyoushuJNI.KeyboardInputDevice_KI_6_get();
  }

  public static String getKI_7() {
    return MyoushuJNI.KeyboardInputDevice_KI_7_get();
  }

  public static String getKI_8() {
    return MyoushuJNI.KeyboardInputDevice_KI_8_get();
  }

  public static String getKI_9() {
    return MyoushuJNI.KeyboardInputDevice_KI_9_get();
  }

  public static String getKI_0() {
    return MyoushuJNI.KeyboardInputDevice_KI_0_get();
  }

  public static String getKI_MINUS() {
    return MyoushuJNI.KeyboardInputDevice_KI_MINUS_get();
  }

  public static String getKI_EQUALS() {
    return MyoushuJNI.KeyboardInputDevice_KI_EQUALS_get();
  }

  public static String getKI_BACK() {
    return MyoushuJNI.KeyboardInputDevice_KI_BACK_get();
  }

  public static String getKI_TAB() {
    return MyoushuJNI.KeyboardInputDevice_KI_TAB_get();
  }

  public static String getKI_Q() {
    return MyoushuJNI.KeyboardInputDevice_KI_Q_get();
  }

  public static String getKI_W() {
    return MyoushuJNI.KeyboardInputDevice_KI_W_get();
  }

  public static String getKI_E() {
    return MyoushuJNI.KeyboardInputDevice_KI_E_get();
  }

  public static String getKI_R() {
    return MyoushuJNI.KeyboardInputDevice_KI_R_get();
  }

  public static String getKI_T() {
    return MyoushuJNI.KeyboardInputDevice_KI_T_get();
  }

  public static String getKI_Y() {
    return MyoushuJNI.KeyboardInputDevice_KI_Y_get();
  }

  public static String getKI_U() {
    return MyoushuJNI.KeyboardInputDevice_KI_U_get();
  }

  public static String getKI_I() {
    return MyoushuJNI.KeyboardInputDevice_KI_I_get();
  }

  public static String getKI_O() {
    return MyoushuJNI.KeyboardInputDevice_KI_O_get();
  }

  public static String getKI_P() {
    return MyoushuJNI.KeyboardInputDevice_KI_P_get();
  }

  public static String getKI_LBRACKET() {
    return MyoushuJNI.KeyboardInputDevice_KI_LBRACKET_get();
  }

  public static String getKI_RBRACKET() {
    return MyoushuJNI.KeyboardInputDevice_KI_RBRACKET_get();
  }

  public static String getKI_RETURN() {
    return MyoushuJNI.KeyboardInputDevice_KI_RETURN_get();
  }

  public static String getKI_LCONTROL() {
    return MyoushuJNI.KeyboardInputDevice_KI_LCONTROL_get();
  }

  public static String getKI_A() {
    return MyoushuJNI.KeyboardInputDevice_KI_A_get();
  }

  public static String getKI_S() {
    return MyoushuJNI.KeyboardInputDevice_KI_S_get();
  }

  public static String getKI_D() {
    return MyoushuJNI.KeyboardInputDevice_KI_D_get();
  }

  public static String getKI_F() {
    return MyoushuJNI.KeyboardInputDevice_KI_F_get();
  }

  public static String getKI_G() {
    return MyoushuJNI.KeyboardInputDevice_KI_G_get();
  }

  public static String getKI_H() {
    return MyoushuJNI.KeyboardInputDevice_KI_H_get();
  }

  public static String getKI_J() {
    return MyoushuJNI.KeyboardInputDevice_KI_J_get();
  }

  public static String getKI_K() {
    return MyoushuJNI.KeyboardInputDevice_KI_K_get();
  }

  public static String getKI_L() {
    return MyoushuJNI.KeyboardInputDevice_KI_L_get();
  }

  public static String getKI_SEMICOLON() {
    return MyoushuJNI.KeyboardInputDevice_KI_SEMICOLON_get();
  }

  public static String getKI_APOSTROPHE() {
    return MyoushuJNI.KeyboardInputDevice_KI_APOSTROPHE_get();
  }

  public static String getKI_GRAVE() {
    return MyoushuJNI.KeyboardInputDevice_KI_GRAVE_get();
  }

  public static String getKI_LSHIFT() {
    return MyoushuJNI.KeyboardInputDevice_KI_LSHIFT_get();
  }

  public static String getKI_BACKSLASH() {
    return MyoushuJNI.KeyboardInputDevice_KI_BACKSLASH_get();
  }

  public static String getKI_Z() {
    return MyoushuJNI.KeyboardInputDevice_KI_Z_get();
  }

  public static String getKI_X() {
    return MyoushuJNI.KeyboardInputDevice_KI_X_get();
  }

  public static String getKI_C() {
    return MyoushuJNI.KeyboardInputDevice_KI_C_get();
  }

  public static String getKI_V() {
    return MyoushuJNI.KeyboardInputDevice_KI_V_get();
  }

  public static String getKI_B() {
    return MyoushuJNI.KeyboardInputDevice_KI_B_get();
  }

  public static String getKI_N() {
    return MyoushuJNI.KeyboardInputDevice_KI_N_get();
  }

  public static String getKI_M() {
    return MyoushuJNI.KeyboardInputDevice_KI_M_get();
  }

  public static String getKI_COMMA() {
    return MyoushuJNI.KeyboardInputDevice_KI_COMMA_get();
  }

  public static String getKI_PERIOD() {
    return MyoushuJNI.KeyboardInputDevice_KI_PERIOD_get();
  }

  public static String getKI_SLASH() {
    return MyoushuJNI.KeyboardInputDevice_KI_SLASH_get();
  }

  public static String getKI_RSHIFT() {
    return MyoushuJNI.KeyboardInputDevice_KI_RSHIFT_get();
  }

  public static String getKI_MULTIPLY() {
    return MyoushuJNI.KeyboardInputDevice_KI_MULTIPLY_get();
  }

  public static String getKI_LMENU() {
    return MyoushuJNI.KeyboardInputDevice_KI_LMENU_get();
  }

  public static String getKI_SPACE() {
    return MyoushuJNI.KeyboardInputDevice_KI_SPACE_get();
  }

  public static String getKI_CAPITAL() {
    return MyoushuJNI.KeyboardInputDevice_KI_CAPITAL_get();
  }

  public static String getKI_F1() {
    return MyoushuJNI.KeyboardInputDevice_KI_F1_get();
  }

  public static String getKI_F2() {
    return MyoushuJNI.KeyboardInputDevice_KI_F2_get();
  }

  public static String getKI_F3() {
    return MyoushuJNI.KeyboardInputDevice_KI_F3_get();
  }

  public static String getKI_F4() {
    return MyoushuJNI.KeyboardInputDevice_KI_F4_get();
  }

  public static String getKI_F5() {
    return MyoushuJNI.KeyboardInputDevice_KI_F5_get();
  }

  public static String getKI_F6() {
    return MyoushuJNI.KeyboardInputDevice_KI_F6_get();
  }

  public static String getKI_F7() {
    return MyoushuJNI.KeyboardInputDevice_KI_F7_get();
  }

  public static String getKI_F8() {
    return MyoushuJNI.KeyboardInputDevice_KI_F8_get();
  }

  public static String getKI_F9() {
    return MyoushuJNI.KeyboardInputDevice_KI_F9_get();
  }

  public static String getKI_F10() {
    return MyoushuJNI.KeyboardInputDevice_KI_F10_get();
  }

  public static String getKI_NUMLOCK() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMLOCK_get();
  }

  public static String getKI_SCROLL() {
    return MyoushuJNI.KeyboardInputDevice_KI_SCROLL_get();
  }

  public static String getKI_NUMPAD7() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD7_get();
  }

  public static String getKI_NUMPAD8() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD8_get();
  }

  public static String getKI_NUMPAD9() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD9_get();
  }

  public static String getKI_SUBTRACT() {
    return MyoushuJNI.KeyboardInputDevice_KI_SUBTRACT_get();
  }

  public static String getKI_NUMPAD4() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD4_get();
  }

  public static String getKI_NUMPAD5() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD5_get();
  }

  public static String getKI_NUMPAD6() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD6_get();
  }

  public static String getKI_ADD() {
    return MyoushuJNI.KeyboardInputDevice_KI_ADD_get();
  }

  public static String getKI_NUMPAD1() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD1_get();
  }

  public static String getKI_NUMPAD2() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD2_get();
  }

  public static String getKI_NUMPAD3() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD3_get();
  }

  public static String getKI_NUMPAD0() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPAD0_get();
  }

  public static String getKI_DECIMAL() {
    return MyoushuJNI.KeyboardInputDevice_KI_DECIMAL_get();
  }

  public static String getKI_OEM_102() {
    return MyoushuJNI.KeyboardInputDevice_KI_OEM_102_get();
  }

  public static String getKI_F11() {
    return MyoushuJNI.KeyboardInputDevice_KI_F11_get();
  }

  public static String getKI_F12() {
    return MyoushuJNI.KeyboardInputDevice_KI_F12_get();
  }

  public static String getKI_F13() {
    return MyoushuJNI.KeyboardInputDevice_KI_F13_get();
  }

  public static String getKI_F14() {
    return MyoushuJNI.KeyboardInputDevice_KI_F14_get();
  }

  public static String getKI_F15() {
    return MyoushuJNI.KeyboardInputDevice_KI_F15_get();
  }

  public static String getKI_KANA() {
    return MyoushuJNI.KeyboardInputDevice_KI_KANA_get();
  }

  public static String getKI_ABNT_C1() {
    return MyoushuJNI.KeyboardInputDevice_KI_ABNT_C1_get();
  }

  public static String getKI_CONVERT() {
    return MyoushuJNI.KeyboardInputDevice_KI_CONVERT_get();
  }

  public static String getKI_NOCONVERT() {
    return MyoushuJNI.KeyboardInputDevice_KI_NOCONVERT_get();
  }

  public static String getKI_YEN() {
    return MyoushuJNI.KeyboardInputDevice_KI_YEN_get();
  }

  public static String getKI_ABNT_C2() {
    return MyoushuJNI.KeyboardInputDevice_KI_ABNT_C2_get();
  }

  public static String getKI_NUMPADEQUALS() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPADEQUALS_get();
  }

  public static String getKI_PREVTRACK() {
    return MyoushuJNI.KeyboardInputDevice_KI_PREVTRACK_get();
  }

  public static String getKI_AT() {
    return MyoushuJNI.KeyboardInputDevice_KI_AT_get();
  }

  public static String getKI_COLON() {
    return MyoushuJNI.KeyboardInputDevice_KI_COLON_get();
  }

  public static String getKI_UNDERLINE() {
    return MyoushuJNI.KeyboardInputDevice_KI_UNDERLINE_get();
  }

  public static String getKI_KANJI() {
    return MyoushuJNI.KeyboardInputDevice_KI_KANJI_get();
  }

  public static String getKI_STOP() {
    return MyoushuJNI.KeyboardInputDevice_KI_STOP_get();
  }

  public static String getKI_AX() {
    return MyoushuJNI.KeyboardInputDevice_KI_AX_get();
  }

  public static String getKI_UNLABELED() {
    return MyoushuJNI.KeyboardInputDevice_KI_UNLABELED_get();
  }

  public static String getKI_NEXTTRACK() {
    return MyoushuJNI.KeyboardInputDevice_KI_NEXTTRACK_get();
  }

  public static String getKI_NUMPADENTER() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPADENTER_get();
  }

  public static String getKI_RCONTROL() {
    return MyoushuJNI.KeyboardInputDevice_KI_RCONTROL_get();
  }

  public static String getKI_MUTE() {
    return MyoushuJNI.KeyboardInputDevice_KI_MUTE_get();
  }

  public static String getKI_CALCULATOR() {
    return MyoushuJNI.KeyboardInputDevice_KI_CALCULATOR_get();
  }

  public static String getKI_PLAYPAUSE() {
    return MyoushuJNI.KeyboardInputDevice_KI_PLAYPAUSE_get();
  }

  public static String getKI_MEDIASTOP() {
    return MyoushuJNI.KeyboardInputDevice_KI_MEDIASTOP_get();
  }

  public static String getKI_VOLUMEDOWN() {
    return MyoushuJNI.KeyboardInputDevice_KI_VOLUMEDOWN_get();
  }

  public static String getKI_VOLUMEUP() {
    return MyoushuJNI.KeyboardInputDevice_KI_VOLUMEUP_get();
  }

  public static String getKI_WEBHOME() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBHOME_get();
  }

  public static String getKI_NUMPADCOMMA() {
    return MyoushuJNI.KeyboardInputDevice_KI_NUMPADCOMMA_get();
  }

  public static String getKI_DIVIDE() {
    return MyoushuJNI.KeyboardInputDevice_KI_DIVIDE_get();
  }

  public static String getKI_SYSRQ() {
    return MyoushuJNI.KeyboardInputDevice_KI_SYSRQ_get();
  }

  public static String getKI_RMENU() {
    return MyoushuJNI.KeyboardInputDevice_KI_RMENU_get();
  }

  public static String getKI_PAUSE() {
    return MyoushuJNI.KeyboardInputDevice_KI_PAUSE_get();
  }

  public static String getKI_HOME() {
    return MyoushuJNI.KeyboardInputDevice_KI_HOME_get();
  }

  public static String getKI_UP() {
    return MyoushuJNI.KeyboardInputDevice_KI_UP_get();
  }

  public static String getKI_PGUP() {
    return MyoushuJNI.KeyboardInputDevice_KI_PGUP_get();
  }

  public static String getKI_LEFT() {
    return MyoushuJNI.KeyboardInputDevice_KI_LEFT_get();
  }

  public static String getKI_RIGHT() {
    return MyoushuJNI.KeyboardInputDevice_KI_RIGHT_get();
  }

  public static String getKI_END() {
    return MyoushuJNI.KeyboardInputDevice_KI_END_get();
  }

  public static String getKI_DOWN() {
    return MyoushuJNI.KeyboardInputDevice_KI_DOWN_get();
  }

  public static String getKI_PGDOWN() {
    return MyoushuJNI.KeyboardInputDevice_KI_PGDOWN_get();
  }

  public static String getKI_INSERT() {
    return MyoushuJNI.KeyboardInputDevice_KI_INSERT_get();
  }

  public static String getKI_DELETE() {
    return MyoushuJNI.KeyboardInputDevice_KI_DELETE_get();
  }

  public static String getKI_LWIN() {
    return MyoushuJNI.KeyboardInputDevice_KI_LWIN_get();
  }

  public static String getKI_RWIN() {
    return MyoushuJNI.KeyboardInputDevice_KI_RWIN_get();
  }

  public static String getKI_APPS() {
    return MyoushuJNI.KeyboardInputDevice_KI_APPS_get();
  }

  public static String getKI_POWER() {
    return MyoushuJNI.KeyboardInputDevice_KI_POWER_get();
  }

  public static String getKI_SLEEP() {
    return MyoushuJNI.KeyboardInputDevice_KI_SLEEP_get();
  }

  public static String getKI_WAKE() {
    return MyoushuJNI.KeyboardInputDevice_KI_WAKE_get();
  }

  public static String getKI_WEBSEARCH() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBSEARCH_get();
  }

  public static String getKI_WEBFAVORITES() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBFAVORITES_get();
  }

  public static String getKI_WEBREFRESH() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBREFRESH_get();
  }

  public static String getKI_WEBSTOP() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBSTOP_get();
  }

  public static String getKI_WEBFORWARD() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBFORWARD_get();
  }

  public static String getKI_WEBBACK() {
    return MyoushuJNI.KeyboardInputDevice_KI_WEBBACK_get();
  }

  public static String getKI_MYCOMPUTER() {
    return MyoushuJNI.KeyboardInputDevice_KI_MYCOMPUTER_get();
  }

  public static String getKI_MAIL() {
    return MyoushuJNI.KeyboardInputDevice_KI_MAIL_get();
  }

  public static String getKI_MEDIASELECT() {
    return MyoushuJNI.KeyboardInputDevice_KI_MEDIASELECT_get();
  }

}
