/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public enum KeyCodeObsolete {
  KC_UNASSIGNED(MyoushuJNI.KC_UNASSIGNED_get()),
  KC_ESCAPE(MyoushuJNI.KC_ESCAPE_get()),
  KC_1(MyoushuJNI.KC_1_get()),
  KC_2(MyoushuJNI.KC_2_get()),
  KC_3(MyoushuJNI.KC_3_get()),
  KC_4(MyoushuJNI.KC_4_get()),
  KC_5(MyoushuJNI.KC_5_get()),
  KC_6(MyoushuJNI.KC_6_get()),
  KC_7(MyoushuJNI.KC_7_get()),
  KC_8(MyoushuJNI.KC_8_get()),
  KC_9(MyoushuJNI.KC_9_get()),
  KC_0(MyoushuJNI.KC_0_get()),
  KC_MINUS(MyoushuJNI.KC_MINUS_get()),
  KC_EQUALS(MyoushuJNI.KC_EQUALS_get()),
  KC_BACK(MyoushuJNI.KC_BACK_get()),
  KC_TAB(MyoushuJNI.KC_TAB_get()),
  KC_Q(MyoushuJNI.KC_Q_get()),
  KC_W(MyoushuJNI.KC_W_get()),
  KC_E(MyoushuJNI.KC_E_get()),
  KC_R(MyoushuJNI.KC_R_get()),
  KC_T(MyoushuJNI.KC_T_get()),
  KC_Y(MyoushuJNI.KC_Y_get()),
  KC_U(MyoushuJNI.KC_U_get()),
  KC_I(MyoushuJNI.KC_I_get()),
  KC_O(MyoushuJNI.KC_O_get()),
  KC_P(MyoushuJNI.KC_P_get()),
  KC_LBRACKET(MyoushuJNI.KC_LBRACKET_get()),
  KC_RBRACKET(MyoushuJNI.KC_RBRACKET_get()),
  KC_RETURN(MyoushuJNI.KC_RETURN_get()),
  KC_LCONTROL(MyoushuJNI.KC_LCONTROL_get()),
  KC_A(MyoushuJNI.KC_A_get()),
  KC_S(MyoushuJNI.KC_S_get()),
  KC_D(MyoushuJNI.KC_D_get()),
  KC_F(MyoushuJNI.KC_F_get()),
  KC_G(MyoushuJNI.KC_G_get()),
  KC_H(MyoushuJNI.KC_H_get()),
  KC_J(MyoushuJNI.KC_J_get()),
  KC_K(MyoushuJNI.KC_K_get()),
  KC_L(MyoushuJNI.KC_L_get()),
  KC_SEMICOLON(MyoushuJNI.KC_SEMICOLON_get()),
  KC_APOSTROPHE(MyoushuJNI.KC_APOSTROPHE_get()),
  KC_GRAVE(MyoushuJNI.KC_GRAVE_get()),
  KC_LSHIFT(MyoushuJNI.KC_LSHIFT_get()),
  KC_BACKSLASH(MyoushuJNI.KC_BACKSLASH_get()),
  KC_Z(MyoushuJNI.KC_Z_get()),
  KC_X(MyoushuJNI.KC_X_get()),
  KC_C(MyoushuJNI.KC_C_get()),
  KC_V(MyoushuJNI.KC_V_get()),
  KC_B(MyoushuJNI.KC_B_get()),
  KC_N(MyoushuJNI.KC_N_get()),
  KC_M(MyoushuJNI.KC_M_get()),
  KC_COMMA(MyoushuJNI.KC_COMMA_get()),
  KC_PERIOD(MyoushuJNI.KC_PERIOD_get()),
  KC_SLASH(MyoushuJNI.KC_SLASH_get()),
  KC_RSHIFT(MyoushuJNI.KC_RSHIFT_get()),
  KC_MULTIPLY(MyoushuJNI.KC_MULTIPLY_get()),
  KC_LMENU(MyoushuJNI.KC_LMENU_get()),
  KC_SPACE(MyoushuJNI.KC_SPACE_get()),
  KC_CAPITAL(MyoushuJNI.KC_CAPITAL_get()),
  KC_F1(MyoushuJNI.KC_F1_get()),
  KC_F2(MyoushuJNI.KC_F2_get()),
  KC_F3(MyoushuJNI.KC_F3_get()),
  KC_F4(MyoushuJNI.KC_F4_get()),
  KC_F5(MyoushuJNI.KC_F5_get()),
  KC_F6(MyoushuJNI.KC_F6_get()),
  KC_F7(MyoushuJNI.KC_F7_get()),
  KC_F8(MyoushuJNI.KC_F8_get()),
  KC_F9(MyoushuJNI.KC_F9_get()),
  KC_F10(MyoushuJNI.KC_F10_get()),
  KC_NUMLOCK(MyoushuJNI.KC_NUMLOCK_get()),
  KC_SCROLL(MyoushuJNI.KC_SCROLL_get()),
  KC_NUMPAD7(MyoushuJNI.KC_NUMPAD7_get()),
  KC_NUMPAD8(MyoushuJNI.KC_NUMPAD8_get()),
  KC_NUMPAD9(MyoushuJNI.KC_NUMPAD9_get()),
  KC_SUBTRACT(MyoushuJNI.KC_SUBTRACT_get()),
  KC_NUMPAD4(MyoushuJNI.KC_NUMPAD4_get()),
  KC_NUMPAD5(MyoushuJNI.KC_NUMPAD5_get()),
  KC_NUMPAD6(MyoushuJNI.KC_NUMPAD6_get()),
  KC_ADD(MyoushuJNI.KC_ADD_get()),
  KC_NUMPAD1(MyoushuJNI.KC_NUMPAD1_get()),
  KC_NUMPAD2(MyoushuJNI.KC_NUMPAD2_get()),
  KC_NUMPAD3(MyoushuJNI.KC_NUMPAD3_get()),
  KC_NUMPAD0(MyoushuJNI.KC_NUMPAD0_get()),
  KC_DECIMAL(MyoushuJNI.KC_DECIMAL_get()),
  KC_OEM_102(MyoushuJNI.KC_OEM_102_get()),
  KC_F11(MyoushuJNI.KC_F11_get()),
  KC_F12(MyoushuJNI.KC_F12_get()),
  KC_F13(MyoushuJNI.KC_F13_get()),
  KC_F14(MyoushuJNI.KC_F14_get()),
  KC_F15(MyoushuJNI.KC_F15_get()),
  KC_KANA(MyoushuJNI.KC_KANA_get()),
  KC_ABNT_C1(MyoushuJNI.KC_ABNT_C1_get()),
  KC_CONVERT(MyoushuJNI.KC_CONVERT_get()),
  KC_NOCONVERT(MyoushuJNI.KC_NOCONVERT_get()),
  KC_YEN(MyoushuJNI.KC_YEN_get()),
  KC_ABNT_C2(MyoushuJNI.KC_ABNT_C2_get()),
  KC_NUMPADEQUALS(MyoushuJNI.KC_NUMPADEQUALS_get()),
  KC_PREVTRACK(MyoushuJNI.KC_PREVTRACK_get()),
  KC_AT(MyoushuJNI.KC_AT_get()),
  KC_COLON(MyoushuJNI.KC_COLON_get()),
  KC_UNDERLINE(MyoushuJNI.KC_UNDERLINE_get()),
  KC_KANJI(MyoushuJNI.KC_KANJI_get()),
  KC_STOP(MyoushuJNI.KC_STOP_get()),
  KC_AX(MyoushuJNI.KC_AX_get()),
  KC_UNLABELED(MyoushuJNI.KC_UNLABELED_get()),
  KC_NEXTTRACK(MyoushuJNI.KC_NEXTTRACK_get()),
  KC_NUMPADENTER(MyoushuJNI.KC_NUMPADENTER_get()),
  KC_RCONTROL(MyoushuJNI.KC_RCONTROL_get()),
  KC_MUTE(MyoushuJNI.KC_MUTE_get()),
  KC_CALCULATOR(MyoushuJNI.KC_CALCULATOR_get()),
  KC_PLAYPAUSE(MyoushuJNI.KC_PLAYPAUSE_get()),
  KC_MEDIASTOP(MyoushuJNI.KC_MEDIASTOP_get()),
  KC_VOLUMEDOWN(MyoushuJNI.KC_VOLUMEDOWN_get()),
  KC_VOLUMEUP(MyoushuJNI.KC_VOLUMEUP_get()),
  KC_WEBHOME(MyoushuJNI.KC_WEBHOME_get()),
  KC_NUMPADCOMMA(MyoushuJNI.KC_NUMPADCOMMA_get()),
  KC_DIVIDE(MyoushuJNI.KC_DIVIDE_get()),
  KC_SYSRQ(MyoushuJNI.KC_SYSRQ_get()),
  KC_RMENU(MyoushuJNI.KC_RMENU_get()),
  KC_PAUSE(MyoushuJNI.KC_PAUSE_get()),
  KC_HOME(MyoushuJNI.KC_HOME_get()),
  KC_UP(MyoushuJNI.KC_UP_get()),
  KC_PGUP(MyoushuJNI.KC_PGUP_get()),
  KC_LEFT(MyoushuJNI.KC_LEFT_get()),
  KC_RIGHT(MyoushuJNI.KC_RIGHT_get()),
  KC_END(MyoushuJNI.KC_END_get()),
  KC_DOWN(MyoushuJNI.KC_DOWN_get()),
  KC_PGDOWN(MyoushuJNI.KC_PGDOWN_get()),
  KC_INSERT(MyoushuJNI.KC_INSERT_get()),
  KC_DELETE(MyoushuJNI.KC_DELETE_get()),
  KC_LWIN(MyoushuJNI.KC_LWIN_get()),
  KC_RWIN(MyoushuJNI.KC_RWIN_get()),
  KC_APPS(MyoushuJNI.KC_APPS_get()),
  KC_POWER(MyoushuJNI.KC_POWER_get()),
  KC_SLEEP(MyoushuJNI.KC_SLEEP_get()),
  KC_WAKE(MyoushuJNI.KC_WAKE_get()),
  KC_WEBSEARCH(MyoushuJNI.KC_WEBSEARCH_get()),
  KC_WEBFAVORITES(MyoushuJNI.KC_WEBFAVORITES_get()),
  KC_WEBREFRESH(MyoushuJNI.KC_WEBREFRESH_get()),
  KC_WEBSTOP(MyoushuJNI.KC_WEBSTOP_get()),
  KC_WEBFORWARD(MyoushuJNI.KC_WEBFORWARD_get()),
  KC_WEBBACK(MyoushuJNI.KC_WEBBACK_get()),
  KC_MYCOMPUTER(MyoushuJNI.KC_MYCOMPUTER_get()),
  KC_MAIL(MyoushuJNI.KC_MAIL_get()),
  KC_MEDIASELECT(MyoushuJNI.KC_MEDIASELECT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static KeyCodeObsolete swigToEnum(int swigValue) {
    KeyCodeObsolete[] swigValues = KeyCodeObsolete.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (KeyCodeObsolete swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + KeyCodeObsolete.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private KeyCodeObsolete() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private KeyCodeObsolete(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private KeyCodeObsolete(KeyCodeObsolete swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

