/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class LayerManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LayerManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LayerManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_LayerManager(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void initialise() {
    MyoushuJNI.LayerManager_initialise(swigCPtr, this);
  }

  public void shutdown() {
    MyoushuJNI.LayerManager_shutdown(swigCPtr, this);
  }

  public void attachToLayerNode(String _name, Widget _item) {
    MyoushuJNI.LayerManager_attachToLayerNode(swigCPtr, this, _name, Widget.getCPtr(_item), _item);
  }

  public void detachFromLayer(Widget _item) {
    MyoushuJNI.LayerManager_detachFromLayer(swigCPtr, this, Widget.getCPtr(_item), _item);
  }

  public void upLayerItem(Widget _item) {
    MyoushuJNI.LayerManager_upLayerItem(swigCPtr, this, Widget.getCPtr(_item), _item);
  }

  public boolean load(String _file, String _group) {
    return MyoushuJNI.LayerManager_load__SWIG_0(swigCPtr, this, _file, _group);
  }

  public boolean load(String _file) {
    return MyoushuJNI.LayerManager_load__SWIG_1(swigCPtr, this, _file);
  }

  public void _load(Element _node, String _file, Version _version) {
    MyoushuJNI.LayerManager__load(swigCPtr, this, Element.getCPtr(_node), _node, _file, Version.getCPtr(_version), _version);
  }

  public boolean isExist(String _name) {
    return MyoushuJNI.LayerManager_isExist(swigCPtr, this, _name);
  }

  public SWIGTYPE_p_MyGUI__EnumeratorT_std__vectorT_MyGUI__ILayer_p_t_t getEnumerator() {
    return new SWIGTYPE_p_MyGUI__EnumeratorT_std__vectorT_MyGUI__ILayer_p_t_t(MyoushuJNI.LayerManager_getEnumerator(swigCPtr, this), true);
  }

  public Widget getWidgetFromPoint(int _left, int _top) {
    long cPtr = MyoushuJNI.LayerManager_getWidgetFromPoint(swigCPtr, this, _left, _top);
    return (cPtr == 0) ? null : new Widget(cPtr, false);
  }

}
