/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class LuaFunctorBase extends FunctorBase {
  private long swigCPtr;

  public LuaFunctorBase(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGLuaFunctorBaseUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(LuaFunctorBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_LuaFunctorBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getClassName() {
    return MyoushuJNI.LuaFunctorBase_getClassName(swigCPtr, this);
  }

  public String getFunctionName() {
    return MyoushuJNI.LuaFunctorBase_getFunctionName(swigCPtr, this);
  }

  public void setQueue(boolean queue) {
    MyoushuJNI.LuaFunctorBase_setQueue(swigCPtr, this, queue);
  }

  public boolean getQueue() {
    return MyoushuJNI.LuaFunctorBase_getQueue(swigCPtr, this);
  }

}
