/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Myoushu implements MyoushuConstants {
  public static int findCommandLineOpts(int numargs, SWIGTYPE_p_p_char argv, SWIGTYPE_p_std__mapT_std__string_bool_t unaryOptList, SWIGTYPE_p_std__mapT_std__string_std__string_t binOptList) {
    return MyoushuJNI.findCommandLineOpts(numargs, SWIGTYPE_p_p_char.getCPtr(argv), SWIGTYPE_p_std__mapT_std__string_bool_t.getCPtr(unaryOptList), SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(binOptList));
  }

  public static void NxThrow(String arg0, int arg1, String arg2, long arg3) {
    MyoushuJNI.NxThrow(arg0, arg1, arg2, arg3);
  }

  public static SWIGTYPE_p_NxVec3 getNxVec3Axis() {
    long cPtr = MyoushuJNI.NxVec3Axis_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_NxVec3(cPtr, false);
  }

  public static void setNx_Version_Full(String value) {
    MyoushuJNI.Nx_Version_Full_set(value);
  }

  public static String getNx_Version_Full() {
    return MyoushuJNI.Nx_Version_Full_get();
  }

  public static ObjectPool_GUIMessage getObjectPoolGUIMessage() {
    long cPtr = MyoushuJNI.getObjectPoolGUIMessage();
    return (cPtr == 0) ? null : new ObjectPool_GUIMessage(cPtr, false);
  }

  public static ObjectPool_KernelMessage getObjectPoolKernelMessage() {
    long cPtr = MyoushuJNI.getObjectPoolKernelMessage();
    return (cPtr == 0) ? null : new ObjectPool_KernelMessage(cPtr, false);
  }

  public static ObjectPool_AnimationTaskMessage getObjectPoolAnimationTaskMessage() {
    long cPtr = MyoushuJNI.getObjectPoolAnimationTaskMessage();
    return (cPtr == 0) ? null : new ObjectPool_AnimationTaskMessage(cPtr, false);
  }

  public static ObjectPool_ControllerTaskMessage getObjectPoolControllerTaskMessage() {
    long cPtr = MyoushuJNI.getObjectPoolControllerTaskMessage();
    return (cPtr == 0) ? null : new ObjectPool_ControllerTaskMessage(cPtr, false);
  }

  public static ObjectPool_GameLogMessage getObjectPoolGameLogMessage() {
    long cPtr = MyoushuJNI.getObjectPoolGameLogMessage();
    return (cPtr == 0) ? null : new ObjectPool_GameLogMessage(cPtr, false);
  }

  public static ObjectPool_InputDeviceMessage getObjectPoolInputDeviceMessage() {
    long cPtr = MyoushuJNI.getObjectPoolInputDeviceMessage();
    return (cPtr == 0) ? null : new ObjectPool_InputDeviceMessage(cPtr, false);
  }

  public static ObjectPool_InputMessage getObjectPoolInputMessage() {
    long cPtr = MyoushuJNI.getObjectPoolInputMessage();
    return (cPtr == 0) ? null : new ObjectPool_InputMessage(cPtr, false);
  }

  public static ObjectPool_NetworkMessage getObjectPoolNetworkMessage() {
    long cPtr = MyoushuJNI.getObjectPoolNetworkMessage();
    return (cPtr == 0) ? null : new ObjectPool_NetworkMessage(cPtr, false);
  }

  public static ObjectPool_ReplayMessage getObjectPoolReplayMessage() {
    long cPtr = MyoushuJNI.getObjectPoolReplayMessage();
    return (cPtr == 0) ? null : new ObjectPool_ReplayMessage(cPtr, false);
  }

  public static ObjectPool_ScriptMessage getObjectPoolScriptMessage() {
    long cPtr = MyoushuJNI.getObjectPoolScriptMessage();
    return (cPtr == 0) ? null : new ObjectPool_ScriptMessage(cPtr, false);
  }

  public static ObjectPool_TimerTaskMessage getObjectPoolTimerTaskMessage() {
    long cPtr = MyoushuJNI.getObjectPoolTimerTaskMessage();
    return (cPtr == 0) ? null : new ObjectPool_TimerTaskMessage(cPtr, false);
  }

  public static ObjectPool_VideoTaskMessage getObjectPoolVideoTaskMessage() {
    long cPtr = MyoushuJNI.getObjectPoolVideoTaskMessage();
    return (cPtr == 0) ? null : new ObjectPool_VideoTaskMessage(cPtr, false);
  }

  public static int luaPrint(SWIGTYPE_p_lua_State L) {
    return MyoushuJNI.luaPrint(SWIGTYPE_p_lua_State.getCPtr(L));
  }

  public static void JavaFunctor_setMethod(long arg0, Object arg1, Object arg2, String arg3, String arg4) {
    MyoushuJNI.JavaFunctor_setMethod(arg0, arg1, arg2, arg3, arg4);
  }

}
