/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class RandomBase extends Serializable {
  private long swigCPtr;

  public RandomBase(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGRandomBaseUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(RandomBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_RandomBase(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void seed(int seed) {
    MyoushuJNI.RandomBase_seed(swigCPtr, this, seed);
  }

  public long generate() {
    return MyoushuJNI.RandomBase_generate__SWIG_0(swigCPtr, this);
  }

  public int generate(int min, int max) {
    return MyoushuJNI.RandomBase_generate__SWIG_1(swigCPtr, this, min, max);
  }

  public double generateDouble() {
    return MyoushuJNI.RandomBase_generateDouble__SWIG_0(swigCPtr, this);
  }

  public double generateDouble(double min, double max) {
    return MyoushuJNI.RandomBase_generateDouble__SWIG_1(swigCPtr, this, min, max);
  }

}
