/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ReplayTask extends Task {
  private long swigCPtr;

  public ReplayTask(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGReplayTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ReplayTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ReplayTask(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ReplayTask(int priority, String name, long executionInterval, long iterationLimit) {
    this(MyoushuJNI.new_ReplayTask__SWIG_0(priority, name, executionInterval, iterationLimit), true);
  }

  public ReplayTask(int priority, String name, long executionInterval) {
    this(MyoushuJNI.new_ReplayTask__SWIG_1(priority, name, executionInterval), true);
  }

  public ReplayTask(int priority, String name) {
    this(MyoushuJNI.new_ReplayTask__SWIG_2(priority, name), true);
  }

  public ReplayTask() {
    this(MyoushuJNI.new_ReplayTask__SWIG_3(), true);
  }

  public String getClassName() {
    return MyoushuJNI.ReplayTask_getClassName(swigCPtr, this);
  }

  public void init() {
    MyoushuJNI.ReplayTask_init(swigCPtr, this);
  }

  public void suspend() {
    MyoushuJNI.ReplayTask_suspend(swigCPtr, this);
  }

  public void execute(long timeDelta) {
    MyoushuJNI.ReplayTask_execute(swigCPtr, this, timeDelta);
  }

  public void kill() {
    MyoushuJNI.ReplayTask_kill(swigCPtr, this);
  }

  public boolean getPlaying() {
    return MyoushuJNI.ReplayTask_getPlaying(swigCPtr, this);
  }

  public boolean getRecording() {
    return MyoushuJNI.ReplayTask_getRecording(swigCPtr, this);
  }

  public boolean getPaused() {
    return MyoushuJNI.ReplayTask_getPaused(swigCPtr, this);
  }

  public Replay getReplay() {
    long cPtr = MyoushuJNI.ReplayTask_getReplay(swigCPtr, this);
    return (cPtr == 0) ? null : new Replay(cPtr, false);
  }

  public void receiveReplayMessage(AutoPtr_ReplayMessage message) {
    MyoushuJNI.ReplayTask_receiveReplayMessage(swigCPtr, this, AutoPtr_ReplayMessage.getCPtr(message), message);
  }

  public void receiveInputMessage(AutoPtr_InputMessage message) {
    MyoushuJNI.ReplayTask_receiveInputMessage(swigCPtr, this, AutoPtr_InputMessage.getCPtr(message), message);
  }

}
