/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ResourceImageSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ResourceImageSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ResourceImageSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public ImageIndexInfo getIndexInfo(String _group, String _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_0(swigCPtr, this, _group, _index), true);
  }

  public ImageIndexInfo getIndexInfo(long _group, String _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_1(swigCPtr, this, _group, _index), true);
  }

  public ImageIndexInfo getIndexInfo(String _group, long _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_2(swigCPtr, this, _group, _index), true);
  }

  public ImageIndexInfo getIndexInfo(long _group, long _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_3(swigCPtr, this, _group, _index), true);
  }

  public ImageIndexInfo getIndexInfo(SWIGTYPE_p_MyGUI__types__TSizeT_int_t _group, long _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_4(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TSizeT_int_t.getCPtr(_group), _index), true);
  }

  public ImageIndexInfo getIndexInfo(SWIGTYPE_p_MyGUI__types__TSizeT_int_t _group, String _index) {
    return new ImageIndexInfo(MyoushuJNI.ResourceImageSet_getIndexInfo__SWIG_5(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TSizeT_int_t.getCPtr(_group), _index), true);
  }

  public SWIGTYPE_p_MyGUI__EnumeratorT_std__vectorT_MyGUI__GroupImage_t_t getEnumerator() {
    return new SWIGTYPE_p_MyGUI__EnumeratorT_std__vectorT_MyGUI__GroupImage_t_t(MyoushuJNI.ResourceImageSet_getEnumerator(swigCPtr, this), true);
  }

}
