/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class ServerNetworkListenBehaviour extends DefaultNetworkListenBehaviour {
  private long swigCPtr;

  public ServerNetworkListenBehaviour(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGServerNetworkListenBehaviourUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ServerNetworkListenBehaviour obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_ServerNetworkListenBehaviour(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ServerNetworkListenBehaviour() {
    this(MyoushuJNI.new_ServerNetworkListenBehaviour(), true);
  }

  public String getClassName() {
    return MyoushuJNI.ServerNetworkListenBehaviour_getClassName(swigCPtr, this);
  }

  public void processReceivedMessage(SWIGTYPE_p_Poco__Net__IPAddress source, String buffer, int length) {
    MyoushuJNI.ServerNetworkListenBehaviour_processReceivedMessage(swigCPtr, this, SWIGTYPE_p_Poco__Net__IPAddress.getCPtr(source), buffer, length);
  }

}
