/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Singleton_ObjectPool_TimerTaskMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Singleton_ObjectPool_TimerTaskMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Singleton_ObjectPool_TimerTaskMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Singleton_ObjectPool_TimerTaskMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Singleton_ObjectPool_TimerTaskMessage() {
    this(MyoushuJNI.new_Singleton_ObjectPool_TimerTaskMessage(), true);
  }

  public static ObjectPool_TimerTaskMessage getSingleton() {
    return new ObjectPool_TimerTaskMessage(MyoushuJNI.Singleton_ObjectPool_TimerTaskMessage_getSingleton(), false);
  }

  public static ObjectPool_TimerTaskMessage getSingletonPtr() {
    long cPtr = MyoushuJNI.Singleton_ObjectPool_TimerTaskMessage_getSingletonPtr();
    return (cPtr == 0) ? null : new ObjectPool_TimerTaskMessage(cPtr, false);
  }

}
