/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class StaticImage extends Widget {
  private long swigCPtr;

  public StaticImage(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGStaticImageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(StaticImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StaticImage() {
    this(MyoushuJNI.new_StaticImage(), true);
  }

  public void setImageInfo(String _texture, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _coord, SWIGTYPE_p_MyGUI__types__TSizeT_int_t _tile) {
    MyoushuJNI.StaticImage_setImageInfo(swigCPtr, this, _texture, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_coord), SWIGTYPE_p_MyGUI__types__TSizeT_int_t.getCPtr(_tile));
  }

  public void setImageTexture(String _value) {
    MyoushuJNI.StaticImage_setImageTexture(swigCPtr, this, _value);
  }

  public void setImageRect(SWIGTYPE_p_MyGUI__types__TRectT_int_t _value) {
    MyoushuJNI.StaticImage_setImageRect(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TRectT_int_t.getCPtr(_value));
  }

  public void setImageCoord(SWIGTYPE_p_MyGUI__types__TCoordT_int_t _value) {
    MyoushuJNI.StaticImage_setImageCoord(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_value));
  }

  public void setImageTile(SWIGTYPE_p_MyGUI__types__TSizeT_int_t _value) {
    MyoushuJNI.StaticImage_setImageTile(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TSizeT_int_t.getCPtr(_value));
  }

  public void setImageIndex(long _index) {
    MyoushuJNI.StaticImage_setImageIndex(swigCPtr, this, _index);
  }

  public long getImageIndex() {
    return MyoushuJNI.StaticImage_getImageIndex(swigCPtr, this);
  }

  public long getItemCount() {
    return MyoushuJNI.StaticImage_getItemCount(swigCPtr, this);
  }

  public void setItemSelect(long _index) {
    MyoushuJNI.StaticImage_setItemSelect(swigCPtr, this, _index);
  }

  public long getItemSelect() {
    return MyoushuJNI.StaticImage_getItemSelect(swigCPtr, this);
  }

  public void resetItemSelect() {
    MyoushuJNI.StaticImage_resetItemSelect(swigCPtr, this);
  }

  public void insertItem(long _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_insertItem(swigCPtr, this, _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void addItem(SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_addItem(swigCPtr, this, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void setItem(long _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_setItem(swigCPtr, this, _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void deleteItem(long _index) {
    MyoushuJNI.StaticImage_deleteItem(swigCPtr, this, _index);
  }

  public void deleteAllItems() {
    MyoushuJNI.StaticImage_deleteAllItems(swigCPtr, this);
  }

  public void addItemFrame(long _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_addItemFrame(swigCPtr, this, _index, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void insertItemFrame(long _index, long _indexFrame, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_insertItemFrame(swigCPtr, this, _index, _indexFrame, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void addItemFrameDublicate(long _index, long _indexSourceFrame) {
    MyoushuJNI.StaticImage_addItemFrameDublicate(swigCPtr, this, _index, _indexSourceFrame);
  }

  public void insertItemFrameDublicate(long _index, long _indexFrame, long _indexSourceFrame) {
    MyoushuJNI.StaticImage_insertItemFrameDublicate(swigCPtr, this, _index, _indexFrame, _indexSourceFrame);
  }

  public void setItemFrame(long _index, long _indexFrame, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _item) {
    MyoushuJNI.StaticImage_setItemFrame(swigCPtr, this, _index, _indexFrame, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_item));
  }

  public void deleteItemFrame(long _index, long _indexFrame) {
    MyoushuJNI.StaticImage_deleteItemFrame(swigCPtr, this, _index, _indexFrame);
  }

  public void deleteAllItemFrames(long _index) {
    MyoushuJNI.StaticImage_deleteAllItemFrames(swigCPtr, this, _index);
  }

  public void setItemFrameRate(long _index, float _rate) {
    MyoushuJNI.StaticImage_setItemFrameRate(swigCPtr, this, _index, _rate);
  }

  public float getItemFrameRate(long _index) {
    return MyoushuJNI.StaticImage_getItemFrameRate(swigCPtr, this, _index);
  }

  public boolean setItemResource(Guid _id) {
    return MyoushuJNI.StaticImage_setItemResource__SWIG_0(swigCPtr, this, Guid.getCPtr(_id), _id);
  }

  public boolean setItemResource(String _name) {
    return MyoushuJNI.StaticImage_setItemResource__SWIG_1(swigCPtr, this, _name);
  }

  public void setItemGroup(String _value) {
    MyoushuJNI.StaticImage_setItemGroup(swigCPtr, this, _value);
  }

  public void setItemName(String _value) {
    MyoushuJNI.StaticImage_setItemName(swigCPtr, this, _value);
  }

  public void setItemResourcePtr(ResourceImageSet _resource) {
    MyoushuJNI.StaticImage_setItemResourcePtr(swigCPtr, this, ResourceImageSet.getCPtr(_resource), _resource);
  }

  public void setItemResourceInfo(ImageIndexInfo _info) {
    MyoushuJNI.StaticImage_setItemResourceInfo__SWIG_0(swigCPtr, this, ImageIndexInfo.getCPtr(_info), _info);
  }

  public ResourceImageSet getItemResource() {
    long cPtr = MyoushuJNI.StaticImage_getItemResource(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceImageSet(cPtr, false);
  }

  public void setItemResourceInfo(ResourceImageSet _resource, String _group, String _name) {
    MyoushuJNI.StaticImage_setItemResourceInfo__SWIG_1(swigCPtr, this, ResourceImageSet.getCPtr(_resource), _resource, _group, _name);
  }

  public void setProperty(String _key, String _value) {
    MyoushuJNI.StaticImage_setProperty(swigCPtr, this, _key, _value);
  }

  public void _initialise(WidgetStyle _style, SWIGTYPE_p_MyGUI__types__TCoordT_int_t _coord, Align _align, WidgetSkinInfo _info, Widget _parent, ICroppedRectangle _croppedParent, IWidgetCreator _creator, String _name) {
    MyoushuJNI.StaticImage__initialise(swigCPtr, this, WidgetStyle.getCPtr(_style), _style, SWIGTYPE_p_MyGUI__types__TCoordT_int_t.getCPtr(_coord), Align.getCPtr(_align), _align, WidgetSkinInfo.getCPtr(_info), _info, Widget.getCPtr(_parent), _parent, ICroppedRectangle.getCPtr(_croppedParent), _croppedParent, IWidgetCreator.getCPtr(_creator), _creator, _name);
  }

}
