/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Translation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Translation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Translation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_Translation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Translation() {
    this(MyoushuJNI.new_Translation(), true);
  }

  public void loadTranslationFile(String filename, String resourceGroup) {
    MyoushuJNI.Translation_loadTranslationFile(swigCPtr, this, filename, resourceGroup);
  }

  public void clear() {
    MyoushuJNI.Translation_clear(swigCPtr, this);
  }

  public UTFString translate(UTFString untranslatedString, UTFString context) {
    return new UTFString(MyoushuJNI.Translation_translate__SWIG_0(swigCPtr, this, UTFString.getCPtr(untranslatedString), untranslatedString, UTFString.getCPtr(context), context), true);
  }

  public UTFString translate(UTFString untranslatedString) {
    return new UTFString(MyoushuJNI.Translation_translate__SWIG_1(swigCPtr, this, UTFString.getCPtr(untranslatedString), untranslatedString), true);
  }

  public boolean translate(UTFString untranslatedString, UTFString translatedString, UTFString context) {
    return MyoushuJNI.Translation_translate__SWIG_2(swigCPtr, this, UTFString.getCPtr(untranslatedString), untranslatedString, UTFString.getCPtr(translatedString), translatedString, UTFString.getCPtr(context), context);
  }

}
