/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class Utility {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Utility(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Utility obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MyoushuJNI.delete_Utility(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GameObject castGameActorObjectToGameObject(GameActorObject pInstance) {
    long cPtr = MyoushuJNI.Utility_castGameActorObjectToGameObject(GameActorObject.getCPtr(pInstance), pInstance);
    return (cPtr == 0) ? null : new GameObject(cPtr, false);
  }

  public static Actor castGameActorObjectToActor(GameActorObject pInstance) {
    long cPtr = MyoushuJNI.Utility_castGameActorObjectToActor(GameActorObject.getCPtr(pInstance), pInstance);
    return (cPtr == 0) ? null : new Actor(cPtr, false);
  }

  public static GameActorObject castGameBodyObjectToGameActorObject(GameBodyObject pInstance) {
    long cPtr = MyoushuJNI.Utility_castGameBodyObjectToGameActorObject(GameBodyObject.getCPtr(pInstance), pInstance);
    return (cPtr == 0) ? null : new GameActorObject(cPtr, false);
  }

  public static GameObject castGameBodyObjectToGameObject(GameBodyObject pInstance) {
    long cPtr = MyoushuJNI.Utility_castGameBodyObjectToGameObject(GameBodyObject.getCPtr(pInstance), pInstance);
    return (cPtr == 0) ? null : new GameObject(cPtr, false);
  }

  public static Actor castGameBodyObjectToActor(GameBodyObject pInstance) {
    long cPtr = MyoushuJNI.Utility_castGameBodyObjectToActor(GameBodyObject.getCPtr(pInstance), pInstance);
    return (cPtr == 0) ? null : new Actor(cPtr, false);
  }

  public Utility() {
    this(MyoushuJNI.new_Utility(), true);
  }

}
