/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package MyoushuJava;

public class VideoTaskMessage extends Message {
  private long swigCPtr;

  public VideoTaskMessage(long cPtr, boolean cMemoryOwn) {
    super(MyoushuJNI.SWIGVideoTaskMessageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(VideoTaskMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      MyoushuJNI.delete_VideoTaskMessage(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public VideoTaskMessage() {
    this(MyoushuJNI.new_VideoTaskMessage__SWIG_0(), true);
  }

  public VideoTaskMessage(VideoTaskMessage.VideoTaskMessageType type) {
    this(MyoushuJNI.new_VideoTaskMessage__SWIG_1(type.swigValue()), true);
  }

  public String getClassName() {
    return MyoushuJNI.VideoTaskMessage_getClassName(swigCPtr, this);
  }

  public VideoTaskMessage.VideoTaskMessageType getMessageType() {
    return VideoTaskMessage.VideoTaskMessageType.swigToEnum(MyoushuJNI.VideoTaskMessage_getMessageType(swigCPtr, this));
  }

  public void setMessageType(VideoTaskMessage.VideoTaskMessageType type) {
    MyoushuJNI.VideoTaskMessage_setMessageType(swigCPtr, this, type.swigValue());
  }

  public void clear() {
    MyoushuJNI.VideoTaskMessage_clear(swigCPtr, this);
  }

  public enum VideoTaskMessageType {
    VM_UNKNOWN(MyoushuJNI.VideoTaskMessage_VM_UNKNOWN_get()),
    VM_SHOW_FPS,
    VM_HIDE_FPS;

    public final int swigValue() {
      return swigValue;
    }

    public static VideoTaskMessageType swigToEnum(int swigValue) {
      VideoTaskMessageType[] swigValues = VideoTaskMessageType.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (VideoTaskMessageType swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + VideoTaskMessageType.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private VideoTaskMessageType() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private VideoTaskMessageType(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private VideoTaskMessageType(VideoTaskMessageType swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
